/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "byteUnstriping_sintetizado.v:1" *)
module byteUnstriping_sintetizado(valid_0, valid_1, clk, reset, lane_0, lane_1, valid_out_sintetizado, data_out_sintetizado);
  (* src = "byteUnstriping_sintetizado.v:9" *)
  wire [31:0] _000_;
  (* src = "byteUnstriping_sintetizado.v:9" *)
  wire _001_;
  (* src = "byteUnstriping_sintetizado.v:9" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  (* src = "byteUnstriping_sintetizado.v:2" *)
  input clk;
  (* src = "byteUnstriping_sintetizado.v:6" *)
  output [31:0] data_out_sintetizado;
  (* src = "byteUnstriping_sintetizado.v:3" *)
  input [31:0] lane_0;
  (* src = "byteUnstriping_sintetizado.v:4" *)
  input [31:0] lane_1;
  (* src = "byteUnstriping_sintetizado.v:2" *)
  input reset;
  (* src = "byteUnstriping_sintetizado.v:8" *)
  wire selector;
  (* src = "byteUnstriping_sintetizado.v:2" *)
  input valid_0;
  (* src = "byteUnstriping_sintetizado.v:2" *)
  input valid_1;
  (* src = "byteUnstriping_sintetizado.v:5" *)
  output valid_out_sintetizado;
  NOT _299_ (
    .A(valid_0),
    .Y(_003_)
  );
  NOT _300_ (
    .A(data_out_sintetizado[26]),
    .Y(_004_)
  );
  NOT _301_ (
    .A(data_out_sintetizado[29]),
    .Y(_005_)
  );
  NOT _302_ (
    .A(data_out_sintetizado[30]),
    .Y(_006_)
  );
  NOT _303_ (
    .A(lane_1[0]),
    .Y(_007_)
  );
  NOT _304_ (
    .A(valid_1),
    .Y(_008_)
  );
  NOT _305_ (
    .A(data_out_sintetizado[7]),
    .Y(_009_)
  );
  NOT _306_ (
    .A(lane_1[7]),
    .Y(_010_)
  );
  NOT _307_ (
    .A(data_out_sintetizado[12]),
    .Y(_011_)
  );
  NOT _308_ (
    .A(lane_1[12]),
    .Y(_012_)
  );
  NOT _309_ (
    .A(data_out_sintetizado[16]),
    .Y(_013_)
  );
  NOT _310_ (
    .A(lane_1[16]),
    .Y(_014_)
  );
  NOT _311_ (
    .A(data_out_sintetizado[20]),
    .Y(_015_)
  );
  NOT _312_ (
    .A(lane_1[20]),
    .Y(_016_)
  );
  NOT _313_ (
    .A(lane_1[26]),
    .Y(_017_)
  );
  NOT _314_ (
    .A(lane_1[29]),
    .Y(_018_)
  );
  NOT _315_ (
    .A(lane_1[30]),
    .Y(_019_)
  );
  NOT _316_ (
    .A(selector),
    .Y(_020_)
  );
  NOT _317_ (
    .A(reset),
    .Y(_021_)
  );
  NAND _318_ (
    .A(_007_),
    .B(valid_1),
    .Y(_022_)
  );
  NOR _319_ (
    .A(data_out_sintetizado[0]),
    .B(valid_1),
    .Y(_023_)
  );
  NOR _320_ (
    .A(_020_),
    .B(reset),
    .Y(_024_)
  );
  NAND _321_ (
    .A(selector),
    .B(_021_),
    .Y(_025_)
  );
  NOR _322_ (
    .A(_023_),
    .B(_025_),
    .Y(_026_)
  );
  NAND _323_ (
    .A(_022_),
    .B(_026_),
    .Y(_027_)
  );
  NAND _324_ (
    .A(_003_),
    .B(data_out_sintetizado[0]),
    .Y(_028_)
  );
  NAND _325_ (
    .A(valid_0),
    .B(lane_0[0]),
    .Y(_029_)
  );
  NAND _326_ (
    .A(_028_),
    .B(_029_),
    .Y(_030_)
  );
  NOR _327_ (
    .A(selector),
    .B(reset),
    .Y(_001_)
  );
  NAND _328_ (
    .A(_030_),
    .B(_001_),
    .Y(_031_)
  );
  NAND _329_ (
    .A(_027_),
    .B(_031_),
    .Y(_000_[0])
  );
  NAND _330_ (
    .A(valid_1),
    .B(lane_1[1]),
    .Y(_032_)
  );
  NAND _331_ (
    .A(_008_),
    .B(data_out_sintetizado[1]),
    .Y(_033_)
  );
  NAND _332_ (
    .A(_032_),
    .B(_033_),
    .Y(_034_)
  );
  NAND _333_ (
    .A(_024_),
    .B(_034_),
    .Y(_035_)
  );
  NAND _334_ (
    .A(valid_0),
    .B(lane_0[1]),
    .Y(_036_)
  );
  NAND _335_ (
    .A(_003_),
    .B(data_out_sintetizado[1]),
    .Y(_037_)
  );
  NAND _336_ (
    .A(_036_),
    .B(_037_),
    .Y(_038_)
  );
  NAND _337_ (
    .A(_001_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _338_ (
    .A(_035_),
    .B(_039_),
    .Y(_000_[1])
  );
  NOR _339_ (
    .A(valid_0),
    .B(data_out_sintetizado[2]),
    .Y(_040_)
  );
  NOR _340_ (
    .A(_003_),
    .B(lane_0[2]),
    .Y(_041_)
  );
  NOR _341_ (
    .A(_040_),
    .B(_041_),
    .Y(_042_)
  );
  NAND _342_ (
    .A(_001_),
    .B(_042_),
    .Y(_043_)
  );
  NAND _343_ (
    .A(valid_1),
    .B(lane_1[2]),
    .Y(_044_)
  );
  NAND _344_ (
    .A(_008_),
    .B(data_out_sintetizado[2]),
    .Y(_045_)
  );
  NAND _345_ (
    .A(_044_),
    .B(_045_),
    .Y(_046_)
  );
  NAND _346_ (
    .A(_024_),
    .B(_046_),
    .Y(_047_)
  );
  NAND _347_ (
    .A(_043_),
    .B(_047_),
    .Y(_000_[2])
  );
  NAND _348_ (
    .A(valid_1),
    .B(lane_1[3]),
    .Y(_048_)
  );
  NAND _349_ (
    .A(_008_),
    .B(data_out_sintetizado[3]),
    .Y(_049_)
  );
  NAND _350_ (
    .A(_048_),
    .B(_049_),
    .Y(_050_)
  );
  NAND _351_ (
    .A(_024_),
    .B(_050_),
    .Y(_051_)
  );
  NAND _352_ (
    .A(_003_),
    .B(data_out_sintetizado[3]),
    .Y(_052_)
  );
  NAND _353_ (
    .A(valid_0),
    .B(lane_0[3]),
    .Y(_053_)
  );
  NAND _354_ (
    .A(_052_),
    .B(_053_),
    .Y(_054_)
  );
  NAND _355_ (
    .A(_001_),
    .B(_054_),
    .Y(_055_)
  );
  NAND _356_ (
    .A(_051_),
    .B(_055_),
    .Y(_000_[3])
  );
  NAND _357_ (
    .A(valid_1),
    .B(lane_1[4]),
    .Y(_056_)
  );
  NAND _358_ (
    .A(_008_),
    .B(data_out_sintetizado[4]),
    .Y(_057_)
  );
  NAND _359_ (
    .A(_056_),
    .B(_057_),
    .Y(_058_)
  );
  NAND _360_ (
    .A(_024_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _361_ (
    .A(_003_),
    .B(data_out_sintetizado[4]),
    .Y(_060_)
  );
  NAND _362_ (
    .A(valid_0),
    .B(lane_0[4]),
    .Y(_061_)
  );
  NAND _363_ (
    .A(_060_),
    .B(_061_),
    .Y(_062_)
  );
  NAND _364_ (
    .A(_001_),
    .B(_062_),
    .Y(_063_)
  );
  NAND _365_ (
    .A(_059_),
    .B(_063_),
    .Y(_000_[4])
  );
  NOR _366_ (
    .A(valid_0),
    .B(data_out_sintetizado[5]),
    .Y(_064_)
  );
  NOR _367_ (
    .A(_003_),
    .B(lane_0[5]),
    .Y(_065_)
  );
  NOR _368_ (
    .A(_064_),
    .B(_065_),
    .Y(_066_)
  );
  NAND _369_ (
    .A(_001_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _370_ (
    .A(valid_1),
    .B(lane_1[5]),
    .Y(_068_)
  );
  NAND _371_ (
    .A(_008_),
    .B(data_out_sintetizado[5]),
    .Y(_069_)
  );
  NAND _372_ (
    .A(_068_),
    .B(_069_),
    .Y(_070_)
  );
  NAND _373_ (
    .A(_024_),
    .B(_070_),
    .Y(_071_)
  );
  NAND _374_ (
    .A(_067_),
    .B(_071_),
    .Y(_000_[5])
  );
  NAND _375_ (
    .A(valid_1),
    .B(lane_1[6]),
    .Y(_072_)
  );
  NAND _376_ (
    .A(_008_),
    .B(data_out_sintetizado[6]),
    .Y(_073_)
  );
  NAND _377_ (
    .A(_072_),
    .B(_073_),
    .Y(_074_)
  );
  NAND _378_ (
    .A(_024_),
    .B(_074_),
    .Y(_075_)
  );
  NAND _379_ (
    .A(_003_),
    .B(data_out_sintetizado[6]),
    .Y(_076_)
  );
  NAND _380_ (
    .A(valid_0),
    .B(lane_0[6]),
    .Y(_077_)
  );
  NAND _381_ (
    .A(_076_),
    .B(_077_),
    .Y(_078_)
  );
  NAND _382_ (
    .A(_001_),
    .B(_078_),
    .Y(_079_)
  );
  NAND _383_ (
    .A(_075_),
    .B(_079_),
    .Y(_000_[6])
  );
  NOR _384_ (
    .A(_008_),
    .B(_010_),
    .Y(_080_)
  );
  NOR _385_ (
    .A(valid_1),
    .B(_009_),
    .Y(_081_)
  );
  NOR _386_ (
    .A(_080_),
    .B(_081_),
    .Y(_082_)
  );
  NOR _387_ (
    .A(_020_),
    .B(_082_),
    .Y(_083_)
  );
  NAND _388_ (
    .A(valid_0),
    .B(lane_0[7]),
    .Y(_084_)
  );
  NOT _389_ (
    .A(_084_),
    .Y(_085_)
  );
  NOR _390_ (
    .A(valid_0),
    .B(_009_),
    .Y(_086_)
  );
  NOR _391_ (
    .A(_085_),
    .B(_086_),
    .Y(_087_)
  );
  NOR _392_ (
    .A(selector),
    .B(_087_),
    .Y(_088_)
  );
  NOR _393_ (
    .A(_083_),
    .B(_088_),
    .Y(_089_)
  );
  NOR _394_ (
    .A(reset),
    .B(_089_),
    .Y(_000_[7])
  );
  NOR _395_ (
    .A(valid_0),
    .B(data_out_sintetizado[8]),
    .Y(_090_)
  );
  NOR _396_ (
    .A(_003_),
    .B(lane_0[8]),
    .Y(_091_)
  );
  NOR _397_ (
    .A(_090_),
    .B(_091_),
    .Y(_092_)
  );
  NAND _398_ (
    .A(_001_),
    .B(_092_),
    .Y(_093_)
  );
  NAND _399_ (
    .A(valid_1),
    .B(lane_1[8]),
    .Y(_094_)
  );
  NAND _400_ (
    .A(_008_),
    .B(data_out_sintetizado[8]),
    .Y(_095_)
  );
  NAND _401_ (
    .A(_094_),
    .B(_095_),
    .Y(_096_)
  );
  NAND _402_ (
    .A(_024_),
    .B(_096_),
    .Y(_097_)
  );
  NAND _403_ (
    .A(_093_),
    .B(_097_),
    .Y(_000_[8])
  );
  NAND _404_ (
    .A(valid_0),
    .B(lane_0[9]),
    .Y(_098_)
  );
  NAND _405_ (
    .A(_003_),
    .B(data_out_sintetizado[9]),
    .Y(_099_)
  );
  NAND _406_ (
    .A(_098_),
    .B(_099_),
    .Y(_100_)
  );
  NAND _407_ (
    .A(_001_),
    .B(_100_),
    .Y(_101_)
  );
  NAND _408_ (
    .A(_008_),
    .B(data_out_sintetizado[9]),
    .Y(_102_)
  );
  NAND _409_ (
    .A(valid_1),
    .B(lane_1[9]),
    .Y(_103_)
  );
  NAND _410_ (
    .A(_102_),
    .B(_103_),
    .Y(_104_)
  );
  NAND _411_ (
    .A(_024_),
    .B(_104_),
    .Y(_105_)
  );
  NAND _412_ (
    .A(_101_),
    .B(_105_),
    .Y(_000_[9])
  );
  NAND _413_ (
    .A(valid_1),
    .B(lane_1[10]),
    .Y(_106_)
  );
  NAND _414_ (
    .A(_008_),
    .B(data_out_sintetizado[10]),
    .Y(_107_)
  );
  NAND _415_ (
    .A(_106_),
    .B(_107_),
    .Y(_108_)
  );
  NAND _416_ (
    .A(_024_),
    .B(_108_),
    .Y(_109_)
  );
  NOR _417_ (
    .A(_003_),
    .B(lane_0[10]),
    .Y(_110_)
  );
  NOR _418_ (
    .A(valid_0),
    .B(data_out_sintetizado[10]),
    .Y(_111_)
  );
  NOR _419_ (
    .A(_110_),
    .B(_111_),
    .Y(_112_)
  );
  NAND _420_ (
    .A(_001_),
    .B(_112_),
    .Y(_113_)
  );
  NAND _421_ (
    .A(_109_),
    .B(_113_),
    .Y(_000_[10])
  );
  NAND _422_ (
    .A(valid_1),
    .B(lane_1[11]),
    .Y(_114_)
  );
  NAND _423_ (
    .A(_008_),
    .B(data_out_sintetizado[11]),
    .Y(_115_)
  );
  NAND _424_ (
    .A(_114_),
    .B(_115_),
    .Y(_116_)
  );
  NAND _425_ (
    .A(_024_),
    .B(_116_),
    .Y(_117_)
  );
  NOR _426_ (
    .A(_003_),
    .B(lane_0[11]),
    .Y(_118_)
  );
  NOR _427_ (
    .A(valid_0),
    .B(data_out_sintetizado[11]),
    .Y(_119_)
  );
  NOR _428_ (
    .A(_118_),
    .B(_119_),
    .Y(_120_)
  );
  NAND _429_ (
    .A(_001_),
    .B(_120_),
    .Y(_121_)
  );
  NAND _430_ (
    .A(_117_),
    .B(_121_),
    .Y(_000_[11])
  );
  NOR _431_ (
    .A(_008_),
    .B(_012_),
    .Y(_122_)
  );
  NOR _432_ (
    .A(valid_1),
    .B(_011_),
    .Y(_123_)
  );
  NOR _433_ (
    .A(_122_),
    .B(_123_),
    .Y(_124_)
  );
  NOR _434_ (
    .A(_020_),
    .B(_124_),
    .Y(_125_)
  );
  NAND _435_ (
    .A(valid_0),
    .B(lane_0[12]),
    .Y(_126_)
  );
  NOT _436_ (
    .A(_126_),
    .Y(_127_)
  );
  NOR _437_ (
    .A(valid_0),
    .B(_011_),
    .Y(_128_)
  );
  NOR _438_ (
    .A(_127_),
    .B(_128_),
    .Y(_129_)
  );
  NOR _439_ (
    .A(selector),
    .B(_129_),
    .Y(_130_)
  );
  NOR _440_ (
    .A(_125_),
    .B(_130_),
    .Y(_131_)
  );
  NOR _441_ (
    .A(reset),
    .B(_131_),
    .Y(_000_[12])
  );
  NAND _442_ (
    .A(valid_1),
    .B(lane_1[13]),
    .Y(_132_)
  );
  NAND _443_ (
    .A(_008_),
    .B(data_out_sintetizado[13]),
    .Y(_133_)
  );
  NAND _444_ (
    .A(_132_),
    .B(_133_),
    .Y(_134_)
  );
  NAND _445_ (
    .A(_024_),
    .B(_134_),
    .Y(_135_)
  );
  NAND _446_ (
    .A(valid_0),
    .B(lane_0[13]),
    .Y(_136_)
  );
  NAND _447_ (
    .A(_003_),
    .B(data_out_sintetizado[13]),
    .Y(_137_)
  );
  NAND _448_ (
    .A(_136_),
    .B(_137_),
    .Y(_138_)
  );
  NAND _449_ (
    .A(_001_),
    .B(_138_),
    .Y(_139_)
  );
  NAND _450_ (
    .A(_135_),
    .B(_139_),
    .Y(_000_[13])
  );
  NAND _451_ (
    .A(valid_1),
    .B(lane_1[14]),
    .Y(_140_)
  );
  NAND _452_ (
    .A(_008_),
    .B(data_out_sintetizado[14]),
    .Y(_141_)
  );
  NAND _453_ (
    .A(_140_),
    .B(_141_),
    .Y(_142_)
  );
  NAND _454_ (
    .A(_024_),
    .B(_142_),
    .Y(_143_)
  );
  NOR _455_ (
    .A(_003_),
    .B(lane_0[14]),
    .Y(_144_)
  );
  NOR _456_ (
    .A(valid_0),
    .B(data_out_sintetizado[14]),
    .Y(_145_)
  );
  NOR _457_ (
    .A(_144_),
    .B(_145_),
    .Y(_146_)
  );
  NAND _458_ (
    .A(_001_),
    .B(_146_),
    .Y(_147_)
  );
  NAND _459_ (
    .A(_143_),
    .B(_147_),
    .Y(_000_[14])
  );
  NAND _460_ (
    .A(valid_1),
    .B(lane_1[15]),
    .Y(_148_)
  );
  NAND _461_ (
    .A(_008_),
    .B(data_out_sintetizado[15]),
    .Y(_149_)
  );
  NAND _462_ (
    .A(_148_),
    .B(_149_),
    .Y(_150_)
  );
  NAND _463_ (
    .A(_024_),
    .B(_150_),
    .Y(_151_)
  );
  NOR _464_ (
    .A(_003_),
    .B(lane_0[15]),
    .Y(_152_)
  );
  NOR _465_ (
    .A(valid_0),
    .B(data_out_sintetizado[15]),
    .Y(_153_)
  );
  NOR _466_ (
    .A(_152_),
    .B(_153_),
    .Y(_154_)
  );
  NAND _467_ (
    .A(_001_),
    .B(_154_),
    .Y(_155_)
  );
  NAND _468_ (
    .A(_151_),
    .B(_155_),
    .Y(_000_[15])
  );
  NOR _469_ (
    .A(_008_),
    .B(_014_),
    .Y(_156_)
  );
  NOR _470_ (
    .A(valid_1),
    .B(_013_),
    .Y(_157_)
  );
  NOR _471_ (
    .A(_156_),
    .B(_157_),
    .Y(_158_)
  );
  NOR _472_ (
    .A(_020_),
    .B(_158_),
    .Y(_159_)
  );
  NAND _473_ (
    .A(valid_0),
    .B(lane_0[16]),
    .Y(_160_)
  );
  NOT _474_ (
    .A(_160_),
    .Y(_161_)
  );
  NOR _475_ (
    .A(valid_0),
    .B(_013_),
    .Y(_162_)
  );
  NOR _476_ (
    .A(_161_),
    .B(_162_),
    .Y(_163_)
  );
  NOR _477_ (
    .A(selector),
    .B(_163_),
    .Y(_164_)
  );
  NOR _478_ (
    .A(_159_),
    .B(_164_),
    .Y(_165_)
  );
  NOR _479_ (
    .A(reset),
    .B(_165_),
    .Y(_000_[16])
  );
  NOR _480_ (
    .A(_003_),
    .B(lane_0[17]),
    .Y(_166_)
  );
  NOR _481_ (
    .A(valid_0),
    .B(data_out_sintetizado[17]),
    .Y(_167_)
  );
  NOR _482_ (
    .A(_166_),
    .B(_167_),
    .Y(_168_)
  );
  NAND _483_ (
    .A(_001_),
    .B(_168_),
    .Y(_169_)
  );
  NAND _484_ (
    .A(_008_),
    .B(data_out_sintetizado[17]),
    .Y(_170_)
  );
  NAND _485_ (
    .A(valid_1),
    .B(lane_1[17]),
    .Y(_171_)
  );
  NAND _486_ (
    .A(_170_),
    .B(_171_),
    .Y(_172_)
  );
  NAND _487_ (
    .A(_024_),
    .B(_172_),
    .Y(_173_)
  );
  NAND _488_ (
    .A(_169_),
    .B(_173_),
    .Y(_000_[17])
  );
  NAND _489_ (
    .A(valid_1),
    .B(lane_1[18]),
    .Y(_174_)
  );
  NAND _490_ (
    .A(_008_),
    .B(data_out_sintetizado[18]),
    .Y(_175_)
  );
  NAND _491_ (
    .A(_174_),
    .B(_175_),
    .Y(_176_)
  );
  NAND _492_ (
    .A(_024_),
    .B(_176_),
    .Y(_177_)
  );
  NAND _493_ (
    .A(valid_0),
    .B(lane_0[18]),
    .Y(_178_)
  );
  NAND _494_ (
    .A(_003_),
    .B(data_out_sintetizado[18]),
    .Y(_179_)
  );
  NAND _495_ (
    .A(_178_),
    .B(_179_),
    .Y(_180_)
  );
  NAND _496_ (
    .A(_001_),
    .B(_180_),
    .Y(_181_)
  );
  NAND _497_ (
    .A(_177_),
    .B(_181_),
    .Y(_000_[18])
  );
  NAND _498_ (
    .A(valid_1),
    .B(lane_1[19]),
    .Y(_182_)
  );
  NAND _499_ (
    .A(_008_),
    .B(data_out_sintetizado[19]),
    .Y(_183_)
  );
  NAND _500_ (
    .A(_182_),
    .B(_183_),
    .Y(_184_)
  );
  NAND _501_ (
    .A(_024_),
    .B(_184_),
    .Y(_185_)
  );
  NOR _502_ (
    .A(_003_),
    .B(lane_0[19]),
    .Y(_186_)
  );
  NOR _503_ (
    .A(valid_0),
    .B(data_out_sintetizado[19]),
    .Y(_187_)
  );
  NOR _504_ (
    .A(_186_),
    .B(_187_),
    .Y(_188_)
  );
  NAND _505_ (
    .A(_001_),
    .B(_188_),
    .Y(_189_)
  );
  NAND _506_ (
    .A(_185_),
    .B(_189_),
    .Y(_000_[19])
  );
  NOR _507_ (
    .A(_008_),
    .B(_016_),
    .Y(_190_)
  );
  NOR _508_ (
    .A(valid_1),
    .B(_015_),
    .Y(_191_)
  );
  NOR _509_ (
    .A(_190_),
    .B(_191_),
    .Y(_192_)
  );
  NOR _510_ (
    .A(_020_),
    .B(_192_),
    .Y(_193_)
  );
  NAND _511_ (
    .A(valid_0),
    .B(lane_0[20]),
    .Y(_194_)
  );
  NOT _512_ (
    .A(_194_),
    .Y(_195_)
  );
  NOR _513_ (
    .A(valid_0),
    .B(_015_),
    .Y(_196_)
  );
  NOR _514_ (
    .A(_195_),
    .B(_196_),
    .Y(_197_)
  );
  NOR _515_ (
    .A(selector),
    .B(_197_),
    .Y(_198_)
  );
  NOR _516_ (
    .A(_193_),
    .B(_198_),
    .Y(_199_)
  );
  NOR _517_ (
    .A(reset),
    .B(_199_),
    .Y(_000_[20])
  );
  NOR _518_ (
    .A(valid_0),
    .B(data_out_sintetizado[21]),
    .Y(_200_)
  );
  NOR _519_ (
    .A(_003_),
    .B(lane_0[21]),
    .Y(_201_)
  );
  NOR _520_ (
    .A(_200_),
    .B(_201_),
    .Y(_202_)
  );
  NAND _521_ (
    .A(_001_),
    .B(_202_),
    .Y(_203_)
  );
  NAND _522_ (
    .A(valid_1),
    .B(lane_1[21]),
    .Y(_204_)
  );
  NAND _523_ (
    .A(_008_),
    .B(data_out_sintetizado[21]),
    .Y(_205_)
  );
  NAND _524_ (
    .A(_204_),
    .B(_205_),
    .Y(_206_)
  );
  NAND _525_ (
    .A(_024_),
    .B(_206_),
    .Y(_207_)
  );
  NAND _526_ (
    .A(_203_),
    .B(_207_),
    .Y(_000_[21])
  );
  NOR _527_ (
    .A(valid_0),
    .B(data_out_sintetizado[22]),
    .Y(_208_)
  );
  NOR _528_ (
    .A(_003_),
    .B(lane_0[22]),
    .Y(_209_)
  );
  NOR _529_ (
    .A(_208_),
    .B(_209_),
    .Y(_210_)
  );
  NAND _530_ (
    .A(_001_),
    .B(_210_),
    .Y(_211_)
  );
  NAND _531_ (
    .A(_008_),
    .B(data_out_sintetizado[22]),
    .Y(_212_)
  );
  NAND _532_ (
    .A(valid_1),
    .B(lane_1[22]),
    .Y(_213_)
  );
  NAND _533_ (
    .A(_212_),
    .B(_213_),
    .Y(_214_)
  );
  NAND _534_ (
    .A(_024_),
    .B(_214_),
    .Y(_215_)
  );
  NAND _535_ (
    .A(_211_),
    .B(_215_),
    .Y(_000_[22])
  );
  NOR _536_ (
    .A(valid_0),
    .B(data_out_sintetizado[23]),
    .Y(_216_)
  );
  NOR _537_ (
    .A(_003_),
    .B(lane_0[23]),
    .Y(_217_)
  );
  NOR _538_ (
    .A(_216_),
    .B(_217_),
    .Y(_218_)
  );
  NAND _539_ (
    .A(_001_),
    .B(_218_),
    .Y(_219_)
  );
  NAND _540_ (
    .A(valid_1),
    .B(lane_1[23]),
    .Y(_220_)
  );
  NAND _541_ (
    .A(_008_),
    .B(data_out_sintetizado[23]),
    .Y(_221_)
  );
  NAND _542_ (
    .A(_220_),
    .B(_221_),
    .Y(_222_)
  );
  NAND _543_ (
    .A(_024_),
    .B(_222_),
    .Y(_223_)
  );
  NAND _544_ (
    .A(_219_),
    .B(_223_),
    .Y(_000_[23])
  );
  NAND _545_ (
    .A(valid_1),
    .B(lane_1[24]),
    .Y(_224_)
  );
  NAND _546_ (
    .A(_008_),
    .B(data_out_sintetizado[24]),
    .Y(_225_)
  );
  NAND _547_ (
    .A(_224_),
    .B(_225_),
    .Y(_226_)
  );
  NAND _548_ (
    .A(_024_),
    .B(_226_),
    .Y(_227_)
  );
  NOR _549_ (
    .A(_003_),
    .B(lane_0[24]),
    .Y(_228_)
  );
  NOR _550_ (
    .A(valid_0),
    .B(data_out_sintetizado[24]),
    .Y(_229_)
  );
  NOR _551_ (
    .A(_228_),
    .B(_229_),
    .Y(_230_)
  );
  NAND _552_ (
    .A(_001_),
    .B(_230_),
    .Y(_231_)
  );
  NAND _553_ (
    .A(_227_),
    .B(_231_),
    .Y(_000_[24])
  );
  NAND _554_ (
    .A(valid_1),
    .B(lane_1[25]),
    .Y(_232_)
  );
  NAND _555_ (
    .A(data_out_sintetizado[25]),
    .B(_008_),
    .Y(_233_)
  );
  NAND _556_ (
    .A(_232_),
    .B(_233_),
    .Y(_234_)
  );
  NAND _557_ (
    .A(_024_),
    .B(_234_),
    .Y(_235_)
  );
  NOR _558_ (
    .A(lane_0[25]),
    .B(_003_),
    .Y(_236_)
  );
  NOR _559_ (
    .A(data_out_sintetizado[25]),
    .B(valid_0),
    .Y(_237_)
  );
  NOR _560_ (
    .A(_236_),
    .B(_237_),
    .Y(_238_)
  );
  NAND _561_ (
    .A(_001_),
    .B(_238_),
    .Y(_239_)
  );
  NAND _562_ (
    .A(_235_),
    .B(_239_),
    .Y(_000_[25])
  );
  NOR _563_ (
    .A(_008_),
    .B(_017_),
    .Y(_240_)
  );
  NOR _564_ (
    .A(_004_),
    .B(valid_1),
    .Y(_241_)
  );
  NOR _565_ (
    .A(_240_),
    .B(_241_),
    .Y(_242_)
  );
  NOR _566_ (
    .A(_020_),
    .B(_242_),
    .Y(_243_)
  );
  NAND _567_ (
    .A(valid_0),
    .B(lane_0[26]),
    .Y(_244_)
  );
  NOT _568_ (
    .A(_244_),
    .Y(_245_)
  );
  NOR _569_ (
    .A(valid_0),
    .B(_004_),
    .Y(_246_)
  );
  NOR _570_ (
    .A(_245_),
    .B(_246_),
    .Y(_247_)
  );
  NOR _571_ (
    .A(selector),
    .B(_247_),
    .Y(_248_)
  );
  NOR _572_ (
    .A(_243_),
    .B(_248_),
    .Y(_249_)
  );
  NOR _573_ (
    .A(reset),
    .B(_249_),
    .Y(_000_[26])
  );
  NAND _574_ (
    .A(valid_1),
    .B(lane_1[27]),
    .Y(_250_)
  );
  NAND _575_ (
    .A(data_out_sintetizado[27]),
    .B(_008_),
    .Y(_251_)
  );
  NAND _576_ (
    .A(_250_),
    .B(_251_),
    .Y(_252_)
  );
  NAND _577_ (
    .A(_024_),
    .B(_252_),
    .Y(_253_)
  );
  NOR _578_ (
    .A(_003_),
    .B(lane_0[27]),
    .Y(_254_)
  );
  NOR _579_ (
    .A(valid_0),
    .B(data_out_sintetizado[27]),
    .Y(_255_)
  );
  NOR _580_ (
    .A(_254_),
    .B(_255_),
    .Y(_256_)
  );
  NAND _581_ (
    .A(_001_),
    .B(_256_),
    .Y(_257_)
  );
  NAND _582_ (
    .A(_253_),
    .B(_257_),
    .Y(_000_[27])
  );
  NAND _583_ (
    .A(valid_1),
    .B(lane_1[28]),
    .Y(_258_)
  );
  NAND _584_ (
    .A(data_out_sintetizado[28]),
    .B(_008_),
    .Y(_259_)
  );
  NAND _585_ (
    .A(_258_),
    .B(_259_),
    .Y(_260_)
  );
  NAND _586_ (
    .A(_024_),
    .B(_260_),
    .Y(_261_)
  );
  NOR _587_ (
    .A(_003_),
    .B(lane_0[28]),
    .Y(_262_)
  );
  NOR _588_ (
    .A(valid_0),
    .B(data_out_sintetizado[28]),
    .Y(_263_)
  );
  NOR _589_ (
    .A(_262_),
    .B(_263_),
    .Y(_264_)
  );
  NAND _590_ (
    .A(_001_),
    .B(_264_),
    .Y(_265_)
  );
  NAND _591_ (
    .A(_261_),
    .B(_265_),
    .Y(_000_[28])
  );
  NOR _592_ (
    .A(_008_),
    .B(_018_),
    .Y(_266_)
  );
  NOR _593_ (
    .A(_005_),
    .B(valid_1),
    .Y(_267_)
  );
  NOR _594_ (
    .A(_266_),
    .B(_267_),
    .Y(_268_)
  );
  NOR _595_ (
    .A(_020_),
    .B(_268_),
    .Y(_269_)
  );
  NAND _596_ (
    .A(valid_0),
    .B(lane_0[29]),
    .Y(_270_)
  );
  NOT _597_ (
    .A(_270_),
    .Y(_271_)
  );
  NOR _598_ (
    .A(valid_0),
    .B(_005_),
    .Y(_272_)
  );
  NOR _599_ (
    .A(_271_),
    .B(_272_),
    .Y(_273_)
  );
  NOR _600_ (
    .A(selector),
    .B(_273_),
    .Y(_274_)
  );
  NOR _601_ (
    .A(_269_),
    .B(_274_),
    .Y(_275_)
  );
  NOR _602_ (
    .A(reset),
    .B(_275_),
    .Y(_000_[29])
  );
  NOR _603_ (
    .A(_008_),
    .B(_019_),
    .Y(_276_)
  );
  NOR _604_ (
    .A(_006_),
    .B(valid_1),
    .Y(_277_)
  );
  NOR _605_ (
    .A(_276_),
    .B(_277_),
    .Y(_278_)
  );
  NOR _606_ (
    .A(_020_),
    .B(_278_),
    .Y(_279_)
  );
  NAND _607_ (
    .A(valid_0),
    .B(lane_0[30]),
    .Y(_280_)
  );
  NOT _608_ (
    .A(_280_),
    .Y(_281_)
  );
  NOR _609_ (
    .A(valid_0),
    .B(_006_),
    .Y(_282_)
  );
  NOR _610_ (
    .A(_281_),
    .B(_282_),
    .Y(_283_)
  );
  NOR _611_ (
    .A(selector),
    .B(_283_),
    .Y(_284_)
  );
  NOR _612_ (
    .A(_279_),
    .B(_284_),
    .Y(_285_)
  );
  NOR _613_ (
    .A(reset),
    .B(_285_),
    .Y(_000_[30])
  );
  NAND _614_ (
    .A(valid_1),
    .B(lane_1[31]),
    .Y(_286_)
  );
  NAND _615_ (
    .A(data_out_sintetizado[31]),
    .B(_008_),
    .Y(_287_)
  );
  NAND _616_ (
    .A(_286_),
    .B(_287_),
    .Y(_288_)
  );
  NAND _617_ (
    .A(_024_),
    .B(_288_),
    .Y(_289_)
  );
  NOR _618_ (
    .A(_003_),
    .B(lane_0[31]),
    .Y(_290_)
  );
  NOR _619_ (
    .A(valid_0),
    .B(data_out_sintetizado[31]),
    .Y(_291_)
  );
  NOR _620_ (
    .A(_290_),
    .B(_291_),
    .Y(_292_)
  );
  NAND _621_ (
    .A(_001_),
    .B(_292_),
    .Y(_293_)
  );
  NAND _622_ (
    .A(_289_),
    .B(_293_),
    .Y(_000_[31])
  );
  NOR _623_ (
    .A(valid_0),
    .B(selector),
    .Y(_294_)
  );
  NOR _624_ (
    .A(reset),
    .B(_294_),
    .Y(_295_)
  );
  NOR _625_ (
    .A(valid_1),
    .B(valid_out_sintetizado),
    .Y(_296_)
  );
  NAND _626_ (
    .A(selector),
    .B(_296_),
    .Y(_297_)
  );
  NAND _627_ (
    .A(_295_),
    .B(_297_),
    .Y(_298_)
  );
  NOT _628_ (
    .A(_298_),
    .Y(_002_)
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _629_ (
    .C(clk),
    .D(_002_),
    .Q(valid_out_sintetizado)
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _630_ (
    .C(clk),
    .D(_000_[0]),
    .Q(data_out_sintetizado[0])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _631_ (
    .C(clk),
    .D(_000_[1]),
    .Q(data_out_sintetizado[1])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _632_ (
    .C(clk),
    .D(_000_[2]),
    .Q(data_out_sintetizado[2])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _633_ (
    .C(clk),
    .D(_000_[3]),
    .Q(data_out_sintetizado[3])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _634_ (
    .C(clk),
    .D(_000_[4]),
    .Q(data_out_sintetizado[4])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _635_ (
    .C(clk),
    .D(_000_[5]),
    .Q(data_out_sintetizado[5])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _636_ (
    .C(clk),
    .D(_000_[6]),
    .Q(data_out_sintetizado[6])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _637_ (
    .C(clk),
    .D(_000_[7]),
    .Q(data_out_sintetizado[7])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _638_ (
    .C(clk),
    .D(_000_[8]),
    .Q(data_out_sintetizado[8])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _639_ (
    .C(clk),
    .D(_000_[9]),
    .Q(data_out_sintetizado[9])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _640_ (
    .C(clk),
    .D(_000_[10]),
    .Q(data_out_sintetizado[10])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _641_ (
    .C(clk),
    .D(_000_[11]),
    .Q(data_out_sintetizado[11])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _642_ (
    .C(clk),
    .D(_000_[12]),
    .Q(data_out_sintetizado[12])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _643_ (
    .C(clk),
    .D(_000_[13]),
    .Q(data_out_sintetizado[13])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _644_ (
    .C(clk),
    .D(_000_[14]),
    .Q(data_out_sintetizado[14])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _645_ (
    .C(clk),
    .D(_000_[15]),
    .Q(data_out_sintetizado[15])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _646_ (
    .C(clk),
    .D(_000_[16]),
    .Q(data_out_sintetizado[16])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _647_ (
    .C(clk),
    .D(_000_[17]),
    .Q(data_out_sintetizado[17])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _648_ (
    .C(clk),
    .D(_000_[18]),
    .Q(data_out_sintetizado[18])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _649_ (
    .C(clk),
    .D(_000_[19]),
    .Q(data_out_sintetizado[19])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _650_ (
    .C(clk),
    .D(_000_[20]),
    .Q(data_out_sintetizado[20])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _651_ (
    .C(clk),
    .D(_000_[21]),
    .Q(data_out_sintetizado[21])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _652_ (
    .C(clk),
    .D(_000_[22]),
    .Q(data_out_sintetizado[22])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _653_ (
    .C(clk),
    .D(_000_[23]),
    .Q(data_out_sintetizado[23])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _654_ (
    .C(clk),
    .D(_000_[24]),
    .Q(data_out_sintetizado[24])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _655_ (
    .C(clk),
    .D(_000_[25]),
    .Q(data_out_sintetizado[25])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _656_ (
    .C(clk),
    .D(_000_[26]),
    .Q(data_out_sintetizado[26])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _657_ (
    .C(clk),
    .D(_000_[27]),
    .Q(data_out_sintetizado[27])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _658_ (
    .C(clk),
    .D(_000_[28]),
    .Q(data_out_sintetizado[28])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _659_ (
    .C(clk),
    .D(_000_[29]),
    .Q(data_out_sintetizado[29])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _660_ (
    .C(clk),
    .D(_000_[30]),
    .Q(data_out_sintetizado[30])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _661_ (
    .C(clk),
    .D(_000_[31]),
    .Q(data_out_sintetizado[31])
  );
  (* src = "byteUnstriping_sintetizado.v:9" *)
  DFF _662_ (
    .C(clk),
    .D(_001_),
    .Q(selector)
  );
endmodule
