/* Generated by Yosys 0.8 (git sha1 5706e90) */

(* top =  1  *)
(* src = "8bto32b.v:1" *)
module paso8bto32b_sintetizado(clk_f, clk_4f, data_in, valid_0, valid_out_sintetizado, data_out_sintetizado);
  (* src = "8bto32b.v:56" *)
  wire [31:0] _000_;
  (* src = "8bto32b.v:15" *)
  wire [1:0] _001_;
  (* src = "8bto32b.v:15" *)
  wire _002_;
  (* src = "8bto32b.v:15" *)
  wire [31:0] _003_;
  (* src = "8bto32b.v:15" *)
  wire [31:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  (* src = "8bto32b.v:2" *)
  input clk_4f;
  (* src = "8bto32b.v:2" *)
  input clk_f;
  (* src = "8bto32b.v:3" *)
  input [7:0] data_in;
  (* src = "8bto32b.v:6" *)
  output [31:0] data_out_sintetizado;
  (* init = 2'h0 *)
  (* src = "8bto32b.v:11" *)
  wire [1:0] indice;
  (* src = "8bto32b.v:10" *)
  wire validTemp;
  (* src = "8bto32b.v:4" *)
  input valid_0;
  (* src = "8bto32b.v:5" *)
  output valid_out_sintetizado;
  (* src = "8bto32b.v:8" *)
  wire [31:0] valorTrans;
  (* src = "8bto32b.v:9" *)
  wire [31:0] valorTrans2;
  NAND _213_ (
    .A(_023_),
    .B(_024_),
    .Y(_000_[7])
  );
  NAND _214_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[8]),
    .Y(_025_)
  );
  NAND _215_ (
    .A(_007_),
    .B(data_out_sintetizado[8]),
    .Y(_026_)
  );
  NAND _216_ (
    .A(_025_),
    .B(_026_),
    .Y(_000_[8])
  );
  NAND _217_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[9]),
    .Y(_027_)
  );
  NAND _218_ (
    .A(_007_),
    .B(data_out_sintetizado[9]),
    .Y(_028_)
  );
  NAND _219_ (
    .A(_027_),
    .B(_028_),
    .Y(_000_[9])
  );
  NAND _220_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[10]),
    .Y(_029_)
  );
  NAND _221_ (
    .A(_007_),
    .B(data_out_sintetizado[10]),
    .Y(_030_)
  );
  NAND _222_ (
    .A(_029_),
    .B(_030_),
    .Y(_000_[10])
  );
  NAND _223_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[11]),
    .Y(_031_)
  );
  NAND _224_ (
    .A(_007_),
    .B(data_out_sintetizado[11]),
    .Y(_032_)
  );
  NAND _225_ (
    .A(_031_),
    .B(_032_),
    .Y(_000_[11])
  );
  NAND _226_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[12]),
    .Y(_033_)
  );
  NAND _227_ (
    .A(_007_),
    .B(data_out_sintetizado[12]),
    .Y(_034_)
  );
  NAND _228_ (
    .A(_033_),
    .B(_034_),
    .Y(_000_[12])
  );
  NAND _229_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[13]),
    .Y(_035_)
  );
  NAND _230_ (
    .A(_007_),
    .B(data_out_sintetizado[13]),
    .Y(_036_)
  );
  NAND _231_ (
    .A(_035_),
    .B(_036_),
    .Y(_000_[13])
  );
  NAND _232_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[14]),
    .Y(_037_)
  );
  NAND _233_ (
    .A(_007_),
    .B(data_out_sintetizado[14]),
    .Y(_038_)
  );
  NAND _234_ (
    .A(_037_),
    .B(_038_),
    .Y(_000_[14])
  );
  NAND _235_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[15]),
    .Y(_039_)
  );
  NAND _236_ (
    .A(_007_),
    .B(data_out_sintetizado[15]),
    .Y(_040_)
  );
  NAND _237_ (
    .A(_039_),
    .B(_040_),
    .Y(_000_[15])
  );
  NAND _238_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[16]),
    .Y(_041_)
  );
  NAND _239_ (
    .A(_007_),
    .B(data_out_sintetizado[16]),
    .Y(_042_)
  );
  NAND _240_ (
    .A(_041_),
    .B(_042_),
    .Y(_000_[16])
  );
  NAND _241_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[17]),
    .Y(_043_)
  );
  NAND _242_ (
    .A(_007_),
    .B(data_out_sintetizado[17]),
    .Y(_044_)
  );
  NAND _243_ (
    .A(_043_),
    .B(_044_),
    .Y(_000_[17])
  );
  NAND _244_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[18]),
    .Y(_045_)
  );
  NAND _245_ (
    .A(_007_),
    .B(data_out_sintetizado[18]),
    .Y(_046_)
  );
  NAND _246_ (
    .A(_045_),
    .B(_046_),
    .Y(_000_[18])
  );
  NAND _247_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[19]),
    .Y(_047_)
  );
  NAND _248_ (
    .A(_007_),
    .B(data_out_sintetizado[19]),
    .Y(_048_)
  );
  NAND _249_ (
    .A(_047_),
    .B(_048_),
    .Y(_000_[19])
  );
  NAND _250_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[20]),
    .Y(_049_)
  );
  NAND _251_ (
    .A(_007_),
    .B(data_out_sintetizado[20]),
    .Y(_050_)
  );
  NAND _252_ (
    .A(_049_),
    .B(_050_),
    .Y(_000_[20])
  );
  NAND _253_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[21]),
    .Y(_051_)
  );
  NAND _254_ (
    .A(_007_),
    .B(data_out_sintetizado[21]),
    .Y(_052_)
  );
  NAND _255_ (
    .A(_051_),
    .B(_052_),
    .Y(_000_[21])
  );
  NAND _256_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[22]),
    .Y(_053_)
  );
  NAND _257_ (
    .A(_007_),
    .B(data_out_sintetizado[22]),
    .Y(_054_)
  );
  NAND _258_ (
    .A(_053_),
    .B(_054_),
    .Y(_000_[22])
  );
  NAND _259_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[23]),
    .Y(_055_)
  );
  NAND _260_ (
    .A(_007_),
    .B(data_out_sintetizado[23]),
    .Y(_056_)
  );
  NAND _261_ (
    .A(_055_),
    .B(_056_),
    .Y(_000_[23])
  );
  NAND _262_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[24]),
    .Y(_057_)
  );
  NAND _263_ (
    .A(_007_),
    .B(data_out_sintetizado[24]),
    .Y(_058_)
  );
  NAND _264_ (
    .A(_057_),
    .B(_058_),
    .Y(_000_[24])
  );
  NAND _265_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[25]),
    .Y(_059_)
  );
  NAND _266_ (
    .A(_007_),
    .B(data_out_sintetizado[25]),
    .Y(_060_)
  );
  NAND _267_ (
    .A(_059_),
    .B(_060_),
    .Y(_000_[25])
  );
  NAND _268_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[26]),
    .Y(_061_)
  );
  NAND _269_ (
    .A(_007_),
    .B(data_out_sintetizado[26]),
    .Y(_062_)
  );
  NAND _270_ (
    .A(_061_),
    .B(_062_),
    .Y(_000_[26])
  );
  NAND _271_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[27]),
    .Y(_063_)
  );
  NAND _272_ (
    .A(_007_),
    .B(data_out_sintetizado[27]),
    .Y(_064_)
  );
  NAND _273_ (
    .A(_063_),
    .B(_064_),
    .Y(_000_[27])
  );
  NAND _274_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[28]),
    .Y(_065_)
  );
  NAND _275_ (
    .A(_007_),
    .B(data_out_sintetizado[28]),
    .Y(_066_)
  );
  NAND _276_ (
    .A(_065_),
    .B(_066_),
    .Y(_000_[28])
  );
  NAND _277_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[29]),
    .Y(_067_)
  );
  NAND _278_ (
    .A(_007_),
    .B(data_out_sintetizado[29]),
    .Y(_068_)
  );
  NAND _279_ (
    .A(_067_),
    .B(_068_),
    .Y(_000_[29])
  );
  NAND _280_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[30]),
    .Y(_069_)
  );
  NAND _281_ (
    .A(_007_),
    .B(data_out_sintetizado[30]),
    .Y(_070_)
  );
  NAND _282_ (
    .A(_069_),
    .B(_070_),
    .Y(_000_[30])
  );
  NAND _283_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[31]),
    .Y(_071_)
  );
  NAND _284_ (
    .A(_007_),
    .B(data_out_sintetizado[31]),
    .Y(_072_)
  );
  NAND _285_ (
    .A(_071_),
    .B(_072_),
    .Y(_000_[31])
  );
  NOR _286_ (
    .A(_006_),
    .B(_008_),
    .Y(_073_)
  );
  NAND _287_ (
    .A(indice[1]),
    .B(valid_0),
    .Y(_074_)
  );
  NOR _288_ (
    .A(indice[0]),
    .B(_074_),
    .Y(_075_)
  );
  NAND _289_ (
    .A(_005_),
    .B(_073_),
    .Y(_076_)
  );
  NAND _290_ (
    .A(data_in[0]),
    .B(_075_),
    .Y(_077_)
  );
  NAND _291_ (
    .A(valorTrans[8]),
    .B(_076_),
    .Y(_078_)
  );
  NAND _292_ (
    .A(_077_),
    .B(_078_),
    .Y(_004_[8])
  );
  NAND _293_ (
    .A(data_in[1]),
    .B(_075_),
    .Y(_079_)
  );
  NAND _294_ (
    .A(valorTrans[9]),
    .B(_076_),
    .Y(_080_)
  );
  NAND _295_ (
    .A(_079_),
    .B(_080_),
    .Y(_004_[9])
  );
  NAND _296_ (
    .A(data_in[2]),
    .B(_075_),
    .Y(_081_)
  );
  NAND _297_ (
    .A(valorTrans[10]),
    .B(_076_),
    .Y(_082_)
  );
  NAND _298_ (
    .A(_081_),
    .B(_082_),
    .Y(_004_[10])
  );
  NAND _299_ (
    .A(data_in[3]),
    .B(_075_),
    .Y(_083_)
  );
  NAND _300_ (
    .A(valorTrans[11]),
    .B(_076_),
    .Y(_084_)
  );
  NAND _301_ (
    .A(_083_),
    .B(_084_),
    .Y(_004_[11])
  );
  NAND _302_ (
    .A(data_in[4]),
    .B(_075_),
    .Y(_085_)
  );
  NAND _303_ (
    .A(valorTrans[12]),
    .B(_076_),
    .Y(_086_)
  );
  NAND _304_ (
    .A(_085_),
    .B(_086_),
    .Y(_004_[12])
  );
  NAND _305_ (
    .A(data_in[5]),
    .B(_075_),
    .Y(_087_)
  );
  NAND _306_ (
    .A(valorTrans[13]),
    .B(_076_),
    .Y(_088_)
  );
  NAND _307_ (
    .A(_087_),
    .B(_088_),
    .Y(_004_[13])
  );
  NAND _308_ (
    .A(data_in[6]),
    .B(_075_),
    .Y(_089_)
  );
  NAND _309_ (
    .A(valorTrans[14]),
    .B(_076_),
    .Y(_090_)
  );
  NAND _310_ (
    .A(_089_),
    .B(_090_),
    .Y(_004_[14])
  );
  NAND _311_ (
    .A(data_in[7]),
    .B(_075_),
    .Y(_091_)
  );
  NAND _312_ (
    .A(valorTrans[15]),
    .B(_076_),
    .Y(_092_)
  );
  NAND _313_ (
    .A(_091_),
    .B(_092_),
    .Y(_004_[15])
  );
  NOR _314_ (
    .A(_005_),
    .B(_074_),
    .Y(_093_)
  );
  NAND _315_ (
    .A(indice[0]),
    .B(_073_),
    .Y(_094_)
  );
  NAND _316_ (
    .A(data_in[0]),
    .B(_093_),
    .Y(_095_)
  );
  NAND _317_ (
    .A(valorTrans[0]),
    .B(_094_),
    .Y(_096_)
  );
  NAND _318_ (
    .A(_095_),
    .B(_096_),
    .Y(_004_[0])
  );
  NAND _319_ (
    .A(data_in[1]),
    .B(_093_),
    .Y(_097_)
  );
  NAND _320_ (
    .A(valorTrans[1]),
    .B(_094_),
    .Y(_098_)
  );
  NAND _321_ (
    .A(_097_),
    .B(_098_),
    .Y(_004_[1])
  );
  NAND _322_ (
    .A(data_in[2]),
    .B(_093_),
    .Y(_099_)
  );
  NAND _323_ (
    .A(valorTrans[2]),
    .B(_094_),
    .Y(_100_)
  );
  NAND _324_ (
    .A(_099_),
    .B(_100_),
    .Y(_004_[2])
  );
  NAND _325_ (
    .A(data_in[3]),
    .B(_093_),
    .Y(_101_)
  );
  NAND _326_ (
    .A(valorTrans[3]),
    .B(_094_),
    .Y(_102_)
  );
  NAND _327_ (
    .A(_101_),
    .B(_102_),
    .Y(_004_[3])
  );
  NAND _328_ (
    .A(data_in[4]),
    .B(_093_),
    .Y(_103_)
  );
  NAND _329_ (
    .A(valorTrans[4]),
    .B(_094_),
    .Y(_104_)
  );
  NAND _330_ (
    .A(_103_),
    .B(_104_),
    .Y(_004_[4])
  );
  NAND _331_ (
    .A(data_in[5]),
    .B(_093_),
    .Y(_105_)
  );
  NAND _332_ (
    .A(valorTrans[5]),
    .B(_094_),
    .Y(_106_)
  );
  NAND _333_ (
    .A(_105_),
    .B(_106_),
    .Y(_004_[5])
  );
  NAND _334_ (
    .A(data_in[6]),
    .B(_093_),
    .Y(_107_)
  );
  NAND _335_ (
    .A(valorTrans[6]),
    .B(_094_),
    .Y(_108_)
  );
  NAND _336_ (
    .A(_107_),
    .B(_108_),
    .Y(_004_[6])
  );
  NAND _337_ (
    .A(data_in[7]),
    .B(_093_),
    .Y(_109_)
  );
  NAND _338_ (
    .A(valorTrans[7]),
    .B(_094_),
    .Y(_110_)
  );
  NAND _339_ (
    .A(_109_),
    .B(_110_),
    .Y(_004_[7])
  );
  NOR _340_ (
    .A(indice[1]),
    .B(_008_),
    .Y(_111_)
  );
  NAND _341_ (
    .A(_006_),
    .B(valid_0),
    .Y(_112_)
  );
  NOR _342_ (
    .A(_005_),
    .B(_112_),
    .Y(_113_)
  );
  NAND _343_ (
    .A(indice[0]),
    .B(_111_),
    .Y(_114_)
  );
  NAND _344_ (
    .A(data_in[0]),
    .B(_113_),
    .Y(_115_)
  );
  NAND _345_ (
    .A(valorTrans[16]),
    .B(_114_),
    .Y(_116_)
  );
  NAND _346_ (
    .A(_115_),
    .B(_116_),
    .Y(_004_[16])
  );
  NAND _347_ (
    .A(data_in[1]),
    .B(_113_),
    .Y(_117_)
  );
  NAND _348_ (
    .A(valorTrans[17]),
    .B(_114_),
    .Y(_118_)
  );
  NAND _349_ (
    .A(_117_),
    .B(_118_),
    .Y(_004_[17])
  );
  NAND _350_ (
    .A(data_in[2]),
    .B(_113_),
    .Y(_119_)
  );
  NAND _351_ (
    .A(valorTrans[18]),
    .B(_114_),
    .Y(_120_)
  );
  NAND _352_ (
    .A(_119_),
    .B(_120_),
    .Y(_004_[18])
  );
  NAND _353_ (
    .A(data_in[3]),
    .B(_113_),
    .Y(_121_)
  );
  NAND _354_ (
    .A(valorTrans[19]),
    .B(_114_),
    .Y(_122_)
  );
  NAND _355_ (
    .A(_121_),
    .B(_122_),
    .Y(_004_[19])
  );
  NAND _356_ (
    .A(data_in[4]),
    .B(_113_),
    .Y(_123_)
  );
  NAND _357_ (
    .A(valorTrans[20]),
    .B(_114_),
    .Y(_124_)
  );
  NAND _358_ (
    .A(_123_),
    .B(_124_),
    .Y(_004_[20])
  );
  NAND _359_ (
    .A(data_in[5]),
    .B(_113_),
    .Y(_125_)
  );
  NAND _360_ (
    .A(valorTrans[21]),
    .B(_114_),
    .Y(_126_)
  );
  NAND _361_ (
    .A(_125_),
    .B(_126_),
    .Y(_004_[21])
  );
  NAND _362_ (
    .A(data_in[6]),
    .B(_113_),
    .Y(_127_)
  );
  NAND _363_ (
    .A(valorTrans[22]),
    .B(_114_),
    .Y(_128_)
  );
  NAND _364_ (
    .A(_127_),
    .B(_128_),
    .Y(_004_[22])
  );
  NAND _365_ (
    .A(data_in[7]),
    .B(_113_),
    .Y(_129_)
  );
  NAND _366_ (
    .A(valorTrans[23]),
    .B(_114_),
    .Y(_130_)
  );
  NAND _367_ (
    .A(_129_),
    .B(_130_),
    .Y(_004_[23])
  );
  NOR _368_ (
    .A(indice[0]),
    .B(_112_),
    .Y(_131_)
  );
  NAND _369_ (
    .A(_005_),
    .B(_111_),
    .Y(_132_)
  );
  NAND _370_ (
    .A(data_in[0]),
    .B(_131_),
    .Y(_133_)
  );
  NAND _371_ (
    .A(valorTrans[24]),
    .B(_132_),
    .Y(_134_)
  );
  NAND _372_ (
    .A(_133_),
    .B(_134_),
    .Y(_004_[24])
  );
  NAND _373_ (
    .A(data_in[1]),
    .B(_131_),
    .Y(_135_)
  );
  NAND _374_ (
    .A(valorTrans[25]),
    .B(_132_),
    .Y(_136_)
  );
  NAND _375_ (
    .A(_135_),
    .B(_136_),
    .Y(_004_[25])
  );
  NAND _376_ (
    .A(data_in[2]),
    .B(_131_),
    .Y(_137_)
  );
  NAND _377_ (
    .A(valorTrans[26]),
    .B(_132_),
    .Y(_138_)
  );
  NAND _378_ (
    .A(_137_),
    .B(_138_),
    .Y(_004_[26])
  );
  NAND _379_ (
    .A(data_in[3]),
    .B(_131_),
    .Y(_139_)
  );
  NAND _380_ (
    .A(valorTrans[27]),
    .B(_132_),
    .Y(_140_)
  );
  NAND _381_ (
    .A(_139_),
    .B(_140_),
    .Y(_004_[27])
  );
  NAND _382_ (
    .A(data_in[4]),
    .B(_131_),
    .Y(_141_)
  );
  NAND _383_ (
    .A(valorTrans[28]),
    .B(_132_),
    .Y(_142_)
  );
  NAND _384_ (
    .A(_141_),
    .B(_142_),
    .Y(_004_[28])
  );
  NAND _385_ (
    .A(data_in[5]),
    .B(_131_),
    .Y(_143_)
  );
  NAND _386_ (
    .A(valorTrans[29]),
    .B(_132_),
    .Y(_144_)
  );
  NAND _387_ (
    .A(_143_),
    .B(_144_),
    .Y(_004_[29])
  );
  NAND _388_ (
    .A(data_in[6]),
    .B(_131_),
    .Y(_145_)
  );
  NAND _389_ (
    .A(valorTrans[30]),
    .B(_132_),
    .Y(_146_)
  );
  NAND _390_ (
    .A(_145_),
    .B(_146_),
    .Y(_004_[30])
  );
  NAND _391_ (
    .A(data_in[7]),
    .B(_131_),
    .Y(_147_)
  );
  NAND _392_ (
    .A(valorTrans[31]),
    .B(_132_),
    .Y(_148_)
  );
  NAND _393_ (
    .A(_147_),
    .B(_148_),
    .Y(_004_[31])
  );
  NAND _394_ (
    .A(valorTrans[0]),
    .B(_131_),
    .Y(_149_)
  );
  NAND _395_ (
    .A(valorTrans2[0]),
    .B(_132_),
    .Y(_150_)
  );
  NAND _396_ (
    .A(_149_),
    .B(_150_),
    .Y(_003_[0])
  );
  NAND _397_ (
    .A(valorTrans[1]),
    .B(_131_),
    .Y(_151_)
  );
  NAND _398_ (
    .A(valorTrans2[1]),
    .B(_132_),
    .Y(_152_)
  );
  NAND _399_ (
    .A(_151_),
    .B(_152_),
    .Y(_003_[1])
  );
  NAND _400_ (
    .A(valorTrans[2]),
    .B(_131_),
    .Y(_153_)
  );
  NAND _401_ (
    .A(valorTrans2[2]),
    .B(_132_),
    .Y(_154_)
  );
  NAND _402_ (
    .A(_153_),
    .B(_154_),
    .Y(_003_[2])
  );
  NAND _403_ (
    .A(valorTrans[3]),
    .B(_131_),
    .Y(_155_)
  );
  NAND _404_ (
    .A(valorTrans2[3]),
    .B(_132_),
    .Y(_156_)
  );
  NAND _405_ (
    .A(_155_),
    .B(_156_),
    .Y(_003_[3])
  );
  NAND _406_ (
    .A(valorTrans[4]),
    .B(_131_),
    .Y(_157_)
  );
  NAND _407_ (
    .A(valorTrans2[4]),
    .B(_132_),
    .Y(_158_)
  );
  NAND _408_ (
    .A(_157_),
    .B(_158_),
    .Y(_003_[4])
  );
  NAND _409_ (
    .A(valorTrans[5]),
    .B(_131_),
    .Y(_159_)
  );
  NAND _410_ (
    .A(valorTrans2[5]),
    .B(_132_),
    .Y(_160_)
  );
  NAND _411_ (
    .A(_159_),
    .B(_160_),
    .Y(_003_[5])
  );
  NAND _412_ (
    .A(valorTrans[6]),
    .B(_131_),
    .Y(_161_)
  );
  NAND _413_ (
    .A(valorTrans2[6]),
    .B(_132_),
    .Y(_162_)
  );
  NAND _414_ (
    .A(_161_),
    .B(_162_),
    .Y(_003_[6])
  );
  NAND _415_ (
    .A(valorTrans[7]),
    .B(_131_),
    .Y(_163_)
  );
  NAND _416_ (
    .A(valorTrans2[7]),
    .B(_132_),
    .Y(_164_)
  );
  NAND _417_ (
    .A(_163_),
    .B(_164_),
    .Y(_003_[7])
  );
  NAND _418_ (
    .A(valorTrans[8]),
    .B(_131_),
    .Y(_165_)
  );
  NAND _419_ (
    .A(valorTrans2[8]),
    .B(_132_),
    .Y(_166_)
  );
  NAND _420_ (
    .A(_165_),
    .B(_166_),
    .Y(_003_[8])
  );
  NAND _421_ (
    .A(valorTrans[9]),
    .B(_131_),
    .Y(_167_)
  );
  NAND _422_ (
    .A(valorTrans2[9]),
    .B(_132_),
    .Y(_168_)
  );
  NAND _423_ (
    .A(_167_),
    .B(_168_),
    .Y(_003_[9])
  );
  NAND _424_ (
    .A(valorTrans[10]),
    .B(_131_),
    .Y(_169_)
  );
  NAND _425_ (
    .A(valorTrans2[10]),
    .B(_132_),
    .Y(_170_)
  );
  NAND _426_ (
    .A(_169_),
    .B(_170_),
    .Y(_003_[10])
  );
  NAND _427_ (
    .A(valorTrans[11]),
    .B(_131_),
    .Y(_171_)
  );
  NAND _428_ (
    .A(valorTrans2[11]),
    .B(_132_),
    .Y(_172_)
  );
  NAND _429_ (
    .A(_171_),
    .B(_172_),
    .Y(_003_[11])
  );
  NAND _430_ (
    .A(valorTrans[12]),
    .B(_131_),
    .Y(_173_)
  );
  NAND _431_ (
    .A(valorTrans2[12]),
    .B(_132_),
    .Y(_174_)
  );
  NAND _432_ (
    .A(_173_),
    .B(_174_),
    .Y(_003_[12])
  );
  NAND _433_ (
    .A(valorTrans[13]),
    .B(_131_),
    .Y(_175_)
  );
  NAND _434_ (
    .A(valorTrans2[13]),
    .B(_132_),
    .Y(_176_)
  );
  NAND _435_ (
    .A(_175_),
    .B(_176_),
    .Y(_003_[13])
  );
  NAND _436_ (
    .A(valorTrans[14]),
    .B(_131_),
    .Y(_177_)
  );
  NAND _437_ (
    .A(valorTrans2[14]),
    .B(_132_),
    .Y(_178_)
  );
  NAND _438_ (
    .A(_177_),
    .B(_178_),
    .Y(_003_[14])
  );
  NAND _439_ (
    .A(valorTrans[15]),
    .B(_131_),
    .Y(_179_)
  );
  NAND _440_ (
    .A(valorTrans2[15]),
    .B(_132_),
    .Y(_180_)
  );
  NAND _441_ (
    .A(_179_),
    .B(_180_),
    .Y(_003_[15])
  );
  NAND _442_ (
    .A(valorTrans[16]),
    .B(_131_),
    .Y(_181_)
  );
  NAND _443_ (
    .A(valorTrans2[16]),
    .B(_132_),
    .Y(_182_)
  );
  NAND _444_ (
    .A(_181_),
    .B(_182_),
    .Y(_003_[16])
  );
  NAND _445_ (
    .A(valorTrans[17]),
    .B(_131_),
    .Y(_183_)
  );
  NAND _446_ (
    .A(valorTrans2[17]),
    .B(_132_),
    .Y(_184_)
  );
  NAND _447_ (
    .A(_183_),
    .B(_184_),
    .Y(_003_[17])
  );
  NAND _448_ (
    .A(valorTrans[18]),
    .B(_131_),
    .Y(_185_)
  );
  NAND _449_ (
    .A(valorTrans2[18]),
    .B(_132_),
    .Y(_186_)
  );
  NAND _450_ (
    .A(_185_),
    .B(_186_),
    .Y(_003_[18])
  );
  NAND _451_ (
    .A(valorTrans[19]),
    .B(_131_),
    .Y(_187_)
  );
  NAND _452_ (
    .A(valorTrans2[19]),
    .B(_132_),
    .Y(_188_)
  );
  NAND _453_ (
    .A(_187_),
    .B(_188_),
    .Y(_003_[19])
  );
  NAND _454_ (
    .A(valorTrans[20]),
    .B(_131_),
    .Y(_189_)
  );
  NAND _455_ (
    .A(valorTrans2[20]),
    .B(_132_),
    .Y(_190_)
  );
  NAND _456_ (
    .A(_189_),
    .B(_190_),
    .Y(_003_[20])
  );
  NAND _457_ (
    .A(valorTrans[21]),
    .B(_131_),
    .Y(_191_)
  );
  NAND _458_ (
    .A(valorTrans2[21]),
    .B(_132_),
    .Y(_192_)
  );
  NAND _459_ (
    .A(_191_),
    .B(_192_),
    .Y(_003_[21])
  );
  NAND _460_ (
    .A(valorTrans[22]),
    .B(_131_),
    .Y(_193_)
  );
  NAND _461_ (
    .A(valorTrans2[22]),
    .B(_132_),
    .Y(_194_)
  );
  NAND _462_ (
    .A(_193_),
    .B(_194_),
    .Y(_003_[22])
  );
  NAND _463_ (
    .A(valorTrans[23]),
    .B(_131_),
    .Y(_195_)
  );
  NAND _464_ (
    .A(valorTrans2[23]),
    .B(_132_),
    .Y(_196_)
  );
  NAND _465_ (
    .A(_195_),
    .B(_196_),
    .Y(_003_[23])
  );
  NAND _466_ (
    .A(valorTrans[24]),
    .B(_131_),
    .Y(_197_)
  );
  NAND _467_ (
    .A(valorTrans2[24]),
    .B(_132_),
    .Y(_198_)
  );
  NAND _468_ (
    .A(_197_),
    .B(_198_),
    .Y(_003_[24])
  );
  NAND _469_ (
    .A(valorTrans[25]),
    .B(_131_),
    .Y(_199_)
  );
  NAND _470_ (
    .A(valorTrans2[25]),
    .B(_132_),
    .Y(_200_)
  );
  NAND _471_ (
    .A(_199_),
    .B(_200_),
    .Y(_003_[25])
  );
  NAND _472_ (
    .A(valorTrans[26]),
    .B(_131_),
    .Y(_201_)
  );
  NAND _473_ (
    .A(valorTrans2[26]),
    .B(_132_),
    .Y(_202_)
  );
  NAND _474_ (
    .A(_201_),
    .B(_202_),
    .Y(_003_[26])
  );
  NAND _475_ (
    .A(valorTrans[27]),
    .B(_131_),
    .Y(_203_)
  );
  NAND _476_ (
    .A(valorTrans2[27]),
    .B(_132_),
    .Y(_204_)
  );
  NAND _477_ (
    .A(_203_),
    .B(_204_),
    .Y(_003_[27])
  );
  NAND _478_ (
    .A(valorTrans[28]),
    .B(_131_),
    .Y(_205_)
  );
  NAND _479_ (
    .A(valorTrans2[28]),
    .B(_132_),
    .Y(_206_)
  );
  NAND _480_ (
    .A(_205_),
    .B(_206_),
    .Y(_003_[28])
  );
  NAND _481_ (
    .A(valorTrans[29]),
    .B(_131_),
    .Y(_207_)
  );
  NAND _482_ (
    .A(valorTrans2[29]),
    .B(_132_),
    .Y(_208_)
  );
  NAND _483_ (
    .A(_207_),
    .B(_208_),
    .Y(_003_[29])
  );
  NAND _484_ (
    .A(valorTrans[30]),
    .B(_131_),
    .Y(_209_)
  );
  NAND _485_ (
    .A(valorTrans2[30]),
    .B(_132_),
    .Y(_210_)
  );
  NAND _486_ (
    .A(_209_),
    .B(_210_),
    .Y(_003_[30])
  );
  NAND _487_ (
    .A(valorTrans[31]),
    .B(_131_),
    .Y(_211_)
  );
  NAND _488_ (
    .A(valorTrans2[31]),
    .B(_132_),
    .Y(_212_)
  );
  NAND _489_ (
    .A(_211_),
    .B(_212_),
    .Y(_003_[31])
  );
  NOR _490_ (
    .A(indice[0]),
    .B(_008_),
    .Y(_001_[0])
  );
  NAND _491_ (
    .A(_076_),
    .B(_114_),
    .Y(_001_[1])
  );
  BUF _492_ (
    .A(valid_0),
    .Y(_002_)
  );
  NOT _493_ (
    .A(indice[0]),
    .Y(_005_)
  );
  NOT _494_ (
    .A(indice[1]),
    .Y(_006_)
  );
  NOT _495_ (
    .A(valid_out_sintetizado),
    .Y(_007_)
  );
  NOT _496_ (
    .A(valid_0),
    .Y(_008_)
  );
  NAND _497_ (
    .A(valorTrans2[0]),
    .B(valid_out_sintetizado),
    .Y(_009_)
  );
  NAND _498_ (
    .A(data_out_sintetizado[0]),
    .B(_007_),
    .Y(_010_)
  );
  NAND _499_ (
    .A(_009_),
    .B(_010_),
    .Y(_000_[0])
  );
  NAND _500_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[1]),
    .Y(_011_)
  );
  NAND _501_ (
    .A(_007_),
    .B(data_out_sintetizado[1]),
    .Y(_012_)
  );
  NAND _502_ (
    .A(_011_),
    .B(_012_),
    .Y(_000_[1])
  );
  NAND _503_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[2]),
    .Y(_013_)
  );
  NAND _504_ (
    .A(_007_),
    .B(data_out_sintetizado[2]),
    .Y(_014_)
  );
  NAND _505_ (
    .A(_013_),
    .B(_014_),
    .Y(_000_[2])
  );
  NAND _506_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[3]),
    .Y(_015_)
  );
  NAND _507_ (
    .A(_007_),
    .B(data_out_sintetizado[3]),
    .Y(_016_)
  );
  NAND _508_ (
    .A(_015_),
    .B(_016_),
    .Y(_000_[3])
  );
  NAND _509_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[4]),
    .Y(_017_)
  );
  NAND _510_ (
    .A(_007_),
    .B(data_out_sintetizado[4]),
    .Y(_018_)
  );
  NAND _511_ (
    .A(_017_),
    .B(_018_),
    .Y(_000_[4])
  );
  NAND _512_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[5]),
    .Y(_019_)
  );
  NAND _513_ (
    .A(_007_),
    .B(data_out_sintetizado[5]),
    .Y(_020_)
  );
  NAND _514_ (
    .A(_019_),
    .B(_020_),
    .Y(_000_[5])
  );
  NAND _515_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[6]),
    .Y(_021_)
  );
  NAND _516_ (
    .A(_007_),
    .B(data_out_sintetizado[6]),
    .Y(_022_)
  );
  NAND _517_ (
    .A(_021_),
    .B(_022_),
    .Y(_000_[6])
  );
  NAND _518_ (
    .A(valid_out_sintetizado),
    .B(valorTrans2[7]),
    .Y(_023_)
  );
  NAND _519_ (
    .A(_007_),
    .B(data_out_sintetizado[7]),
    .Y(_024_)
  );
  (* src = "8bto32b.v:56" *)
  DFF _520_ (
    .C(clk_f),
    .D(validTemp),
    .Q(valid_out_sintetizado)
  );
  (* src = "8bto32b.v:56" *)
  DFF _521_ (
    .C(clk_f),
    .D(_000_[0]),
    .Q(data_out_sintetizado[0])
  );
  (* src = "8bto32b.v:56" *)
  DFF _522_ (
    .C(clk_f),
    .D(_000_[1]),
    .Q(data_out_sintetizado[1])
  );
  (* src = "8bto32b.v:56" *)
  DFF _523_ (
    .C(clk_f),
    .D(_000_[2]),
    .Q(data_out_sintetizado[2])
  );
  (* src = "8bto32b.v:56" *)
  DFF _524_ (
    .C(clk_f),
    .D(_000_[3]),
    .Q(data_out_sintetizado[3])
  );
  (* src = "8bto32b.v:56" *)
  DFF _525_ (
    .C(clk_f),
    .D(_000_[4]),
    .Q(data_out_sintetizado[4])
  );
  (* src = "8bto32b.v:56" *)
  DFF _526_ (
    .C(clk_f),
    .D(_000_[5]),
    .Q(data_out_sintetizado[5])
  );
  (* src = "8bto32b.v:56" *)
  DFF _527_ (
    .C(clk_f),
    .D(_000_[6]),
    .Q(data_out_sintetizado[6])
  );
  (* src = "8bto32b.v:56" *)
  DFF _528_ (
    .C(clk_f),
    .D(_000_[7]),
    .Q(data_out_sintetizado[7])
  );
  (* src = "8bto32b.v:56" *)
  DFF _529_ (
    .C(clk_f),
    .D(_000_[8]),
    .Q(data_out_sintetizado[8])
  );
  (* src = "8bto32b.v:56" *)
  DFF _530_ (
    .C(clk_f),
    .D(_000_[9]),
    .Q(data_out_sintetizado[9])
  );
  (* src = "8bto32b.v:56" *)
  DFF _531_ (
    .C(clk_f),
    .D(_000_[10]),
    .Q(data_out_sintetizado[10])
  );
  (* src = "8bto32b.v:56" *)
  DFF _532_ (
    .C(clk_f),
    .D(_000_[11]),
    .Q(data_out_sintetizado[11])
  );
  (* src = "8bto32b.v:56" *)
  DFF _533_ (
    .C(clk_f),
    .D(_000_[12]),
    .Q(data_out_sintetizado[12])
  );
  (* src = "8bto32b.v:56" *)
  DFF _534_ (
    .C(clk_f),
    .D(_000_[13]),
    .Q(data_out_sintetizado[13])
  );
  (* src = "8bto32b.v:56" *)
  DFF _535_ (
    .C(clk_f),
    .D(_000_[14]),
    .Q(data_out_sintetizado[14])
  );
  (* src = "8bto32b.v:56" *)
  DFF _536_ (
    .C(clk_f),
    .D(_000_[15]),
    .Q(data_out_sintetizado[15])
  );
  (* src = "8bto32b.v:56" *)
  DFF _537_ (
    .C(clk_f),
    .D(_000_[16]),
    .Q(data_out_sintetizado[16])
  );
  (* src = "8bto32b.v:56" *)
  DFF _538_ (
    .C(clk_f),
    .D(_000_[17]),
    .Q(data_out_sintetizado[17])
  );
  (* src = "8bto32b.v:56" *)
  DFF _539_ (
    .C(clk_f),
    .D(_000_[18]),
    .Q(data_out_sintetizado[18])
  );
  (* src = "8bto32b.v:56" *)
  DFF _540_ (
    .C(clk_f),
    .D(_000_[19]),
    .Q(data_out_sintetizado[19])
  );
  (* src = "8bto32b.v:56" *)
  DFF _541_ (
    .C(clk_f),
    .D(_000_[20]),
    .Q(data_out_sintetizado[20])
  );
  (* src = "8bto32b.v:56" *)
  DFF _542_ (
    .C(clk_f),
    .D(_000_[21]),
    .Q(data_out_sintetizado[21])
  );
  (* src = "8bto32b.v:56" *)
  DFF _543_ (
    .C(clk_f),
    .D(_000_[22]),
    .Q(data_out_sintetizado[22])
  );
  (* src = "8bto32b.v:56" *)
  DFF _544_ (
    .C(clk_f),
    .D(_000_[23]),
    .Q(data_out_sintetizado[23])
  );
  (* src = "8bto32b.v:56" *)
  DFF _545_ (
    .C(clk_f),
    .D(_000_[24]),
    .Q(data_out_sintetizado[24])
  );
  (* src = "8bto32b.v:56" *)
  DFF _546_ (
    .C(clk_f),
    .D(_000_[25]),
    .Q(data_out_sintetizado[25])
  );
  (* src = "8bto32b.v:56" *)
  DFF _547_ (
    .C(clk_f),
    .D(_000_[26]),
    .Q(data_out_sintetizado[26])
  );
  (* src = "8bto32b.v:56" *)
  DFF _548_ (
    .C(clk_f),
    .D(_000_[27]),
    .Q(data_out_sintetizado[27])
  );
  (* src = "8bto32b.v:56" *)
  DFF _549_ (
    .C(clk_f),
    .D(_000_[28]),
    .Q(data_out_sintetizado[28])
  );
  (* src = "8bto32b.v:56" *)
  DFF _550_ (
    .C(clk_f),
    .D(_000_[29]),
    .Q(data_out_sintetizado[29])
  );
  (* src = "8bto32b.v:56" *)
  DFF _551_ (
    .C(clk_f),
    .D(_000_[30]),
    .Q(data_out_sintetizado[30])
  );
  (* src = "8bto32b.v:56" *)
  DFF _552_ (
    .C(clk_f),
    .D(_000_[31]),
    .Q(data_out_sintetizado[31])
  );
  (* src = "8bto32b.v:15" *)
  DFF _553_ (
    .C(clk_4f),
    .D(_004_[0]),
    .Q(valorTrans[0])
  );
  (* src = "8bto32b.v:15" *)
  DFF _554_ (
    .C(clk_4f),
    .D(_004_[1]),
    .Q(valorTrans[1])
  );
  (* src = "8bto32b.v:15" *)
  DFF _555_ (
    .C(clk_4f),
    .D(_004_[2]),
    .Q(valorTrans[2])
  );
  (* src = "8bto32b.v:15" *)
  DFF _556_ (
    .C(clk_4f),
    .D(_004_[3]),
    .Q(valorTrans[3])
  );
  (* src = "8bto32b.v:15" *)
  DFF _557_ (
    .C(clk_4f),
    .D(_004_[4]),
    .Q(valorTrans[4])
  );
  (* src = "8bto32b.v:15" *)
  DFF _558_ (
    .C(clk_4f),
    .D(_004_[5]),
    .Q(valorTrans[5])
  );
  (* src = "8bto32b.v:15" *)
  DFF _559_ (
    .C(clk_4f),
    .D(_004_[6]),
    .Q(valorTrans[6])
  );
  (* src = "8bto32b.v:15" *)
  DFF _560_ (
    .C(clk_4f),
    .D(_004_[7]),
    .Q(valorTrans[7])
  );
  (* src = "8bto32b.v:15" *)
  DFF _561_ (
    .C(clk_4f),
    .D(_004_[8]),
    .Q(valorTrans[8])
  );
  (* src = "8bto32b.v:15" *)
  DFF _562_ (
    .C(clk_4f),
    .D(_004_[9]),
    .Q(valorTrans[9])
  );
  (* src = "8bto32b.v:15" *)
  DFF _563_ (
    .C(clk_4f),
    .D(_004_[10]),
    .Q(valorTrans[10])
  );
  (* src = "8bto32b.v:15" *)
  DFF _564_ (
    .C(clk_4f),
    .D(_004_[11]),
    .Q(valorTrans[11])
  );
  (* src = "8bto32b.v:15" *)
  DFF _565_ (
    .C(clk_4f),
    .D(_004_[12]),
    .Q(valorTrans[12])
  );
  (* src = "8bto32b.v:15" *)
  DFF _566_ (
    .C(clk_4f),
    .D(_004_[13]),
    .Q(valorTrans[13])
  );
  (* src = "8bto32b.v:15" *)
  DFF _567_ (
    .C(clk_4f),
    .D(_004_[14]),
    .Q(valorTrans[14])
  );
  (* src = "8bto32b.v:15" *)
  DFF _568_ (
    .C(clk_4f),
    .D(_004_[15]),
    .Q(valorTrans[15])
  );
  (* src = "8bto32b.v:15" *)
  DFF _569_ (
    .C(clk_4f),
    .D(_004_[16]),
    .Q(valorTrans[16])
  );
  (* src = "8bto32b.v:15" *)
  DFF _570_ (
    .C(clk_4f),
    .D(_004_[17]),
    .Q(valorTrans[17])
  );
  (* src = "8bto32b.v:15" *)
  DFF _571_ (
    .C(clk_4f),
    .D(_004_[18]),
    .Q(valorTrans[18])
  );
  (* src = "8bto32b.v:15" *)
  DFF _572_ (
    .C(clk_4f),
    .D(_004_[19]),
    .Q(valorTrans[19])
  );
  (* src = "8bto32b.v:15" *)
  DFF _573_ (
    .C(clk_4f),
    .D(_004_[20]),
    .Q(valorTrans[20])
  );
  (* src = "8bto32b.v:15" *)
  DFF _574_ (
    .C(clk_4f),
    .D(_004_[21]),
    .Q(valorTrans[21])
  );
  (* src = "8bto32b.v:15" *)
  DFF _575_ (
    .C(clk_4f),
    .D(_004_[22]),
    .Q(valorTrans[22])
  );
  (* src = "8bto32b.v:15" *)
  DFF _576_ (
    .C(clk_4f),
    .D(_004_[23]),
    .Q(valorTrans[23])
  );
  (* src = "8bto32b.v:15" *)
  DFF _577_ (
    .C(clk_4f),
    .D(_004_[24]),
    .Q(valorTrans[24])
  );
  (* src = "8bto32b.v:15" *)
  DFF _578_ (
    .C(clk_4f),
    .D(_004_[25]),
    .Q(valorTrans[25])
  );
  (* src = "8bto32b.v:15" *)
  DFF _579_ (
    .C(clk_4f),
    .D(_004_[26]),
    .Q(valorTrans[26])
  );
  (* src = "8bto32b.v:15" *)
  DFF _580_ (
    .C(clk_4f),
    .D(_004_[27]),
    .Q(valorTrans[27])
  );
  (* src = "8bto32b.v:15" *)
  DFF _581_ (
    .C(clk_4f),
    .D(_004_[28]),
    .Q(valorTrans[28])
  );
  (* src = "8bto32b.v:15" *)
  DFF _582_ (
    .C(clk_4f),
    .D(_004_[29]),
    .Q(valorTrans[29])
  );
  (* src = "8bto32b.v:15" *)
  DFF _583_ (
    .C(clk_4f),
    .D(_004_[30]),
    .Q(valorTrans[30])
  );
  (* src = "8bto32b.v:15" *)
  DFF _584_ (
    .C(clk_4f),
    .D(_004_[31]),
    .Q(valorTrans[31])
  );
  (* src = "8bto32b.v:15" *)
  DFF _585_ (
    .C(clk_4f),
    .D(_003_[0]),
    .Q(valorTrans2[0])
  );
  (* src = "8bto32b.v:15" *)
  DFF _586_ (
    .C(clk_4f),
    .D(_003_[1]),
    .Q(valorTrans2[1])
  );
  (* src = "8bto32b.v:15" *)
  DFF _587_ (
    .C(clk_4f),
    .D(_003_[2]),
    .Q(valorTrans2[2])
  );
  (* src = "8bto32b.v:15" *)
  DFF _588_ (
    .C(clk_4f),
    .D(_003_[3]),
    .Q(valorTrans2[3])
  );
  (* src = "8bto32b.v:15" *)
  DFF _589_ (
    .C(clk_4f),
    .D(_003_[4]),
    .Q(valorTrans2[4])
  );
  (* src = "8bto32b.v:15" *)
  DFF _590_ (
    .C(clk_4f),
    .D(_003_[5]),
    .Q(valorTrans2[5])
  );
  (* src = "8bto32b.v:15" *)
  DFF _591_ (
    .C(clk_4f),
    .D(_003_[6]),
    .Q(valorTrans2[6])
  );
  (* src = "8bto32b.v:15" *)
  DFF _592_ (
    .C(clk_4f),
    .D(_003_[7]),
    .Q(valorTrans2[7])
  );
  (* src = "8bto32b.v:15" *)
  DFF _593_ (
    .C(clk_4f),
    .D(_003_[8]),
    .Q(valorTrans2[8])
  );
  (* src = "8bto32b.v:15" *)
  DFF _594_ (
    .C(clk_4f),
    .D(_003_[9]),
    .Q(valorTrans2[9])
  );
  (* src = "8bto32b.v:15" *)
  DFF _595_ (
    .C(clk_4f),
    .D(_003_[10]),
    .Q(valorTrans2[10])
  );
  (* src = "8bto32b.v:15" *)
  DFF _596_ (
    .C(clk_4f),
    .D(_003_[11]),
    .Q(valorTrans2[11])
  );
  (* src = "8bto32b.v:15" *)
  DFF _597_ (
    .C(clk_4f),
    .D(_003_[12]),
    .Q(valorTrans2[12])
  );
  (* src = "8bto32b.v:15" *)
  DFF _598_ (
    .C(clk_4f),
    .D(_003_[13]),
    .Q(valorTrans2[13])
  );
  (* src = "8bto32b.v:15" *)
  DFF _599_ (
    .C(clk_4f),
    .D(_003_[14]),
    .Q(valorTrans2[14])
  );
  (* src = "8bto32b.v:15" *)
  DFF _600_ (
    .C(clk_4f),
    .D(_003_[15]),
    .Q(valorTrans2[15])
  );
  (* src = "8bto32b.v:15" *)
  DFF _601_ (
    .C(clk_4f),
    .D(_003_[16]),
    .Q(valorTrans2[16])
  );
  (* src = "8bto32b.v:15" *)
  DFF _602_ (
    .C(clk_4f),
    .D(_003_[17]),
    .Q(valorTrans2[17])
  );
  (* src = "8bto32b.v:15" *)
  DFF _603_ (
    .C(clk_4f),
    .D(_003_[18]),
    .Q(valorTrans2[18])
  );
  (* src = "8bto32b.v:15" *)
  DFF _604_ (
    .C(clk_4f),
    .D(_003_[19]),
    .Q(valorTrans2[19])
  );
  (* src = "8bto32b.v:15" *)
  DFF _605_ (
    .C(clk_4f),
    .D(_003_[20]),
    .Q(valorTrans2[20])
  );
  (* src = "8bto32b.v:15" *)
  DFF _606_ (
    .C(clk_4f),
    .D(_003_[21]),
    .Q(valorTrans2[21])
  );
  (* src = "8bto32b.v:15" *)
  DFF _607_ (
    .C(clk_4f),
    .D(_003_[22]),
    .Q(valorTrans2[22])
  );
  (* src = "8bto32b.v:15" *)
  DFF _608_ (
    .C(clk_4f),
    .D(_003_[23]),
    .Q(valorTrans2[23])
  );
  (* src = "8bto32b.v:15" *)
  DFF _609_ (
    .C(clk_4f),
    .D(_003_[24]),
    .Q(valorTrans2[24])
  );
  (* src = "8bto32b.v:15" *)
  DFF _610_ (
    .C(clk_4f),
    .D(_003_[25]),
    .Q(valorTrans2[25])
  );
  (* src = "8bto32b.v:15" *)
  DFF _611_ (
    .C(clk_4f),
    .D(_003_[26]),
    .Q(valorTrans2[26])
  );
  (* src = "8bto32b.v:15" *)
  DFF _612_ (
    .C(clk_4f),
    .D(_003_[27]),
    .Q(valorTrans2[27])
  );
  (* src = "8bto32b.v:15" *)
  DFF _613_ (
    .C(clk_4f),
    .D(_003_[28]),
    .Q(valorTrans2[28])
  );
  (* src = "8bto32b.v:15" *)
  DFF _614_ (
    .C(clk_4f),
    .D(_003_[29]),
    .Q(valorTrans2[29])
  );
  (* src = "8bto32b.v:15" *)
  DFF _615_ (
    .C(clk_4f),
    .D(_003_[30]),
    .Q(valorTrans2[30])
  );
  (* src = "8bto32b.v:15" *)
  DFF _616_ (
    .C(clk_4f),
    .D(_003_[31]),
    .Q(valorTrans2[31])
  );
  (* src = "8bto32b.v:15" *)
  DFF _617_ (
    .C(clk_4f),
    .D(_002_),
    .Q(validTemp)
  );
  (* src = "8bto32b.v:15" *)
  DFF _618_ (
    .C(clk_4f),
    .D(_001_[0]),
    .Q(indice[0])
  );
  (* src = "8bto32b.v:15" *)
  DFF _619_ (
    .C(clk_4f),
    .D(_001_[1]),
    .Q(indice[1])
  );
endmodule
