/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "paso8bto32b_sintetizado.v:1" *)
module paso8bto32b_sintetizado(clk_f, clk_4f, data_in, valid_0, reset, valid_out_sintetizado, data_out_sintetizado);
  (* src = "paso8bto32b_sintetizado.v:16" *)
  wire [1:0] _000_;
  (* src = "paso8bto32b_sintetizado.v:16" *)
  wire [31:0] _001_;
  (* src = "paso8bto32b_sintetizado.v:16" *)
  wire [1:0] _002_;
  (* src = "paso8bto32b_sintetizado.v:16" *)
  wire _003_;
  (* src = "paso8bto32b_sintetizado.v:16" *)
  wire _004_;
  (* src = "paso8bto32b_sintetizado.v:16" *)
  wire _005_;
  (* src = "paso8bto32b_sintetizado.v:16" *)
  wire [31:0] _006_;
  (* src = "paso8bto32b_sintetizado.v:16" *)
  wire [31:0] _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  (* src = "paso8bto32b_sintetizado.v:2" *)
  input clk_4f;
  (* src = "paso8bto32b_sintetizado.v:2" *)
  input clk_f;
  (* src = "paso8bto32b_sintetizado.v:12" *)
  wire [1:0] contador_clk;
  (* src = "paso8bto32b_sintetizado.v:3" *)
  input [7:0] data_in;
  (* src = "paso8bto32b_sintetizado.v:7" *)
  output [31:0] data_out_sintetizado;
  (* src = "paso8bto32b_sintetizado.v:5" *)
  input reset;
  (* src = "paso8bto32b_sintetizado.v:11" *)
  wire [1:0] selector;
  (* src = "paso8bto32b_sintetizado.v:13" *)
  wire validTemp;
  (* src = "paso8bto32b_sintetizado.v:14" *)
  wire validTemp2;
  (* src = "paso8bto32b_sintetizado.v:4" *)
  input valid_0;
  (* src = "paso8bto32b_sintetizado.v:6" *)
  output valid_out_sintetizado;
  (* src = "paso8bto32b_sintetizado.v:9" *)
  wire [31:0] valorTrans;
  (* src = "paso8bto32b_sintetizado.v:10" *)
  wire [31:0] valorTrans2;
  NOT _325_ (
    .A(selector[0]),
    .Y(_008_)
  );
  NOT _326_ (
    .A(selector[1]),
    .Y(_009_)
  );
  NOT _327_ (
    .A(data_in[0]),
    .Y(_010_)
  );
  NOT _328_ (
    .A(valorTrans[8]),
    .Y(_011_)
  );
  NOT _329_ (
    .A(data_in[1]),
    .Y(_012_)
  );
  NOT _330_ (
    .A(valorTrans[9]),
    .Y(_013_)
  );
  NOT _331_ (
    .A(data_in[2]),
    .Y(_014_)
  );
  NOT _332_ (
    .A(valorTrans[10]),
    .Y(_015_)
  );
  NOT _333_ (
    .A(data_in[3]),
    .Y(_016_)
  );
  NOT _334_ (
    .A(valorTrans[11]),
    .Y(_017_)
  );
  NOT _335_ (
    .A(data_in[4]),
    .Y(_018_)
  );
  NOT _336_ (
    .A(valorTrans[12]),
    .Y(_019_)
  );
  NOT _337_ (
    .A(data_in[5]),
    .Y(_020_)
  );
  NOT _338_ (
    .A(valorTrans[13]),
    .Y(_021_)
  );
  NOT _339_ (
    .A(data_in[6]),
    .Y(_022_)
  );
  NOT _340_ (
    .A(valorTrans[14]),
    .Y(_023_)
  );
  NOT _341_ (
    .A(data_in[7]),
    .Y(_024_)
  );
  NOT _342_ (
    .A(valorTrans[15]),
    .Y(_025_)
  );
  NOT _343_ (
    .A(reset),
    .Y(_026_)
  );
  NOT _344_ (
    .A(valorTrans[0]),
    .Y(_027_)
  );
  NOT _345_ (
    .A(valorTrans[1]),
    .Y(_028_)
  );
  NOT _346_ (
    .A(valorTrans[2]),
    .Y(_029_)
  );
  NOT _347_ (
    .A(valorTrans[3]),
    .Y(_030_)
  );
  NOT _348_ (
    .A(valorTrans[4]),
    .Y(_031_)
  );
  NOT _349_ (
    .A(valorTrans[5]),
    .Y(_032_)
  );
  NOT _350_ (
    .A(valorTrans[6]),
    .Y(_033_)
  );
  NOT _351_ (
    .A(valorTrans[7]),
    .Y(_034_)
  );
  NOT _352_ (
    .A(valorTrans[16]),
    .Y(_035_)
  );
  NOT _353_ (
    .A(valorTrans[17]),
    .Y(_036_)
  );
  NOT _354_ (
    .A(valorTrans[18]),
    .Y(_037_)
  );
  NOT _355_ (
    .A(valorTrans[19]),
    .Y(_038_)
  );
  NOT _356_ (
    .A(valorTrans[20]),
    .Y(_039_)
  );
  NOT _357_ (
    .A(valorTrans[21]),
    .Y(_040_)
  );
  NOT _358_ (
    .A(valorTrans[22]),
    .Y(_041_)
  );
  NOT _359_ (
    .A(valorTrans[23]),
    .Y(_042_)
  );
  NOT _360_ (
    .A(valorTrans[24]),
    .Y(_043_)
  );
  NOT _361_ (
    .A(valorTrans[25]),
    .Y(_044_)
  );
  NOT _362_ (
    .A(valorTrans[26]),
    .Y(_045_)
  );
  NOT _363_ (
    .A(valorTrans[27]),
    .Y(_046_)
  );
  NOT _364_ (
    .A(valorTrans[28]),
    .Y(_047_)
  );
  NOT _365_ (
    .A(valorTrans[29]),
    .Y(_048_)
  );
  NOT _366_ (
    .A(valorTrans[30]),
    .Y(_049_)
  );
  NOT _367_ (
    .A(valorTrans[31]),
    .Y(_050_)
  );
  NAND _368_ (
    .A(_008_),
    .B(valid_0),
    .Y(_051_)
  );
  NOR _369_ (
    .A(_009_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _370_ (
    .A(valorTrans[8]),
    .B(_052_),
    .Y(_053_)
  );
  NAND _371_ (
    .A(_010_),
    .B(_052_),
    .Y(_054_)
  );
  NAND _372_ (
    .A(_026_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _373_ (
    .A(_053_),
    .B(_055_),
    .Y(_007_[8])
  );
  NOR _374_ (
    .A(valorTrans[9]),
    .B(_052_),
    .Y(_056_)
  );
  NAND _375_ (
    .A(_012_),
    .B(_052_),
    .Y(_057_)
  );
  NAND _376_ (
    .A(_026_),
    .B(_057_),
    .Y(_058_)
  );
  NOR _377_ (
    .A(_056_),
    .B(_058_),
    .Y(_007_[9])
  );
  NOR _378_ (
    .A(valorTrans[10]),
    .B(_052_),
    .Y(_059_)
  );
  NAND _379_ (
    .A(_014_),
    .B(_052_),
    .Y(_060_)
  );
  NAND _380_ (
    .A(_026_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _381_ (
    .A(_059_),
    .B(_061_),
    .Y(_007_[10])
  );
  NOR _382_ (
    .A(valorTrans[11]),
    .B(_052_),
    .Y(_062_)
  );
  NAND _383_ (
    .A(_016_),
    .B(_052_),
    .Y(_063_)
  );
  NAND _384_ (
    .A(_026_),
    .B(_063_),
    .Y(_064_)
  );
  NOR _385_ (
    .A(_062_),
    .B(_064_),
    .Y(_007_[11])
  );
  NOR _386_ (
    .A(valorTrans[12]),
    .B(_052_),
    .Y(_065_)
  );
  NAND _387_ (
    .A(_018_),
    .B(_052_),
    .Y(_066_)
  );
  NAND _388_ (
    .A(_026_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _389_ (
    .A(_065_),
    .B(_067_),
    .Y(_007_[12])
  );
  NOR _390_ (
    .A(valorTrans[13]),
    .B(_052_),
    .Y(_068_)
  );
  NAND _391_ (
    .A(_020_),
    .B(_052_),
    .Y(_069_)
  );
  NAND _392_ (
    .A(_026_),
    .B(_069_),
    .Y(_070_)
  );
  NOR _393_ (
    .A(_068_),
    .B(_070_),
    .Y(_007_[13])
  );
  NOR _394_ (
    .A(valorTrans[14]),
    .B(_052_),
    .Y(_071_)
  );
  NAND _395_ (
    .A(_022_),
    .B(_052_),
    .Y(_072_)
  );
  NAND _396_ (
    .A(_026_),
    .B(_072_),
    .Y(_073_)
  );
  NOR _397_ (
    .A(_071_),
    .B(_073_),
    .Y(_007_[14])
  );
  NOR _398_ (
    .A(valorTrans[15]),
    .B(_052_),
    .Y(_074_)
  );
  NAND _399_ (
    .A(_024_),
    .B(_052_),
    .Y(_075_)
  );
  NAND _400_ (
    .A(_026_),
    .B(_075_),
    .Y(_076_)
  );
  NOR _401_ (
    .A(_074_),
    .B(_076_),
    .Y(_007_[15])
  );
  NAND _402_ (
    .A(selector[0]),
    .B(valid_0),
    .Y(_077_)
  );
  NOT _403_ (
    .A(_077_),
    .Y(_078_)
  );
  NOR _404_ (
    .A(_009_),
    .B(_077_),
    .Y(_079_)
  );
  NAND _405_ (
    .A(selector[1]),
    .B(_078_),
    .Y(_080_)
  );
  NOR _406_ (
    .A(reset),
    .B(_079_),
    .Y(_081_)
  );
  NOT _407_ (
    .A(_081_),
    .Y(_082_)
  );
  NAND _408_ (
    .A(valorTrans[0]),
    .B(_081_),
    .Y(_083_)
  );
  NOR _409_ (
    .A(reset),
    .B(_080_),
    .Y(_004_)
  );
  NAND _410_ (
    .A(data_in[0]),
    .B(_004_),
    .Y(_084_)
  );
  NAND _411_ (
    .A(_083_),
    .B(_084_),
    .Y(_007_[0])
  );
  NAND _412_ (
    .A(valorTrans[1]),
    .B(_081_),
    .Y(_085_)
  );
  NAND _413_ (
    .A(data_in[1]),
    .B(_004_),
    .Y(_086_)
  );
  NAND _414_ (
    .A(_085_),
    .B(_086_),
    .Y(_007_[1])
  );
  NAND _415_ (
    .A(valorTrans[2]),
    .B(_081_),
    .Y(_087_)
  );
  NAND _416_ (
    .A(data_in[2]),
    .B(_004_),
    .Y(_088_)
  );
  NAND _417_ (
    .A(_087_),
    .B(_088_),
    .Y(_007_[2])
  );
  NAND _418_ (
    .A(valorTrans[3]),
    .B(_081_),
    .Y(_089_)
  );
  NAND _419_ (
    .A(data_in[3]),
    .B(_004_),
    .Y(_090_)
  );
  NAND _420_ (
    .A(_089_),
    .B(_090_),
    .Y(_007_[3])
  );
  NAND _421_ (
    .A(valorTrans[4]),
    .B(_081_),
    .Y(_091_)
  );
  NAND _422_ (
    .A(data_in[4]),
    .B(_004_),
    .Y(_092_)
  );
  NAND _423_ (
    .A(_091_),
    .B(_092_),
    .Y(_007_[4])
  );
  NAND _424_ (
    .A(valorTrans[5]),
    .B(_081_),
    .Y(_093_)
  );
  NAND _425_ (
    .A(data_in[5]),
    .B(_004_),
    .Y(_094_)
  );
  NAND _426_ (
    .A(_093_),
    .B(_094_),
    .Y(_007_[5])
  );
  NAND _427_ (
    .A(valorTrans[6]),
    .B(_081_),
    .Y(_095_)
  );
  NAND _428_ (
    .A(data_in[6]),
    .B(_004_),
    .Y(_096_)
  );
  NAND _429_ (
    .A(_095_),
    .B(_096_),
    .Y(_007_[6])
  );
  NAND _430_ (
    .A(valorTrans[7]),
    .B(_081_),
    .Y(_097_)
  );
  NAND _431_ (
    .A(data_in[7]),
    .B(_004_),
    .Y(_098_)
  );
  NAND _432_ (
    .A(_097_),
    .B(_098_),
    .Y(_007_[7])
  );
  NOR _433_ (
    .A(selector[1]),
    .B(_077_),
    .Y(_099_)
  );
  NOR _434_ (
    .A(valorTrans[16]),
    .B(_099_),
    .Y(_100_)
  );
  NAND _435_ (
    .A(_010_),
    .B(_099_),
    .Y(_101_)
  );
  NAND _436_ (
    .A(_026_),
    .B(_101_),
    .Y(_102_)
  );
  NOR _437_ (
    .A(_100_),
    .B(_102_),
    .Y(_007_[16])
  );
  NOR _438_ (
    .A(valorTrans[17]),
    .B(_099_),
    .Y(_103_)
  );
  NAND _439_ (
    .A(_012_),
    .B(_099_),
    .Y(_104_)
  );
  NAND _440_ (
    .A(_026_),
    .B(_104_),
    .Y(_105_)
  );
  NOR _441_ (
    .A(_103_),
    .B(_105_),
    .Y(_007_[17])
  );
  NOR _442_ (
    .A(valorTrans[18]),
    .B(_099_),
    .Y(_106_)
  );
  NAND _443_ (
    .A(_014_),
    .B(_099_),
    .Y(_107_)
  );
  NAND _444_ (
    .A(_026_),
    .B(_107_),
    .Y(_108_)
  );
  NOR _445_ (
    .A(_106_),
    .B(_108_),
    .Y(_007_[18])
  );
  NOR _446_ (
    .A(valorTrans[19]),
    .B(_099_),
    .Y(_109_)
  );
  NAND _447_ (
    .A(_016_),
    .B(_099_),
    .Y(_110_)
  );
  NAND _448_ (
    .A(_026_),
    .B(_110_),
    .Y(_111_)
  );
  NOR _449_ (
    .A(_109_),
    .B(_111_),
    .Y(_007_[19])
  );
  NOR _450_ (
    .A(valorTrans[20]),
    .B(_099_),
    .Y(_112_)
  );
  NAND _451_ (
    .A(_018_),
    .B(_099_),
    .Y(_113_)
  );
  NAND _452_ (
    .A(_026_),
    .B(_113_),
    .Y(_114_)
  );
  NOR _453_ (
    .A(_112_),
    .B(_114_),
    .Y(_007_[20])
  );
  NOR _454_ (
    .A(valorTrans[21]),
    .B(_099_),
    .Y(_115_)
  );
  NAND _455_ (
    .A(_020_),
    .B(_099_),
    .Y(_116_)
  );
  NAND _456_ (
    .A(_026_),
    .B(_116_),
    .Y(_117_)
  );
  NOR _457_ (
    .A(_115_),
    .B(_117_),
    .Y(_007_[21])
  );
  NOR _458_ (
    .A(valorTrans[22]),
    .B(_099_),
    .Y(_118_)
  );
  NAND _459_ (
    .A(_022_),
    .B(_099_),
    .Y(_119_)
  );
  NAND _460_ (
    .A(_026_),
    .B(_119_),
    .Y(_120_)
  );
  NOR _461_ (
    .A(_118_),
    .B(_120_),
    .Y(_007_[22])
  );
  NOR _462_ (
    .A(valorTrans[23]),
    .B(_099_),
    .Y(_121_)
  );
  NAND _463_ (
    .A(_024_),
    .B(_099_),
    .Y(_122_)
  );
  NAND _464_ (
    .A(_026_),
    .B(_122_),
    .Y(_123_)
  );
  NOR _465_ (
    .A(_121_),
    .B(_123_),
    .Y(_007_[23])
  );
  NOR _466_ (
    .A(selector[1]),
    .B(_051_),
    .Y(_124_)
  );
  NOR _467_ (
    .A(valorTrans[24]),
    .B(_124_),
    .Y(_125_)
  );
  NAND _468_ (
    .A(_010_),
    .B(_124_),
    .Y(_126_)
  );
  NAND _469_ (
    .A(_026_),
    .B(_126_),
    .Y(_127_)
  );
  NOR _470_ (
    .A(_125_),
    .B(_127_),
    .Y(_007_[24])
  );
  NOR _471_ (
    .A(valorTrans[25]),
    .B(_124_),
    .Y(_128_)
  );
  NAND _472_ (
    .A(_012_),
    .B(_124_),
    .Y(_129_)
  );
  NAND _473_ (
    .A(_026_),
    .B(_129_),
    .Y(_130_)
  );
  NOR _474_ (
    .A(_128_),
    .B(_130_),
    .Y(_007_[25])
  );
  NOR _475_ (
    .A(valorTrans[26]),
    .B(_124_),
    .Y(_131_)
  );
  NAND _476_ (
    .A(_014_),
    .B(_124_),
    .Y(_132_)
  );
  NAND _477_ (
    .A(_026_),
    .B(_132_),
    .Y(_133_)
  );
  NOR _478_ (
    .A(_131_),
    .B(_133_),
    .Y(_007_[26])
  );
  NOR _479_ (
    .A(valorTrans[27]),
    .B(_124_),
    .Y(_134_)
  );
  NAND _480_ (
    .A(_016_),
    .B(_124_),
    .Y(_135_)
  );
  NAND _481_ (
    .A(_026_),
    .B(_135_),
    .Y(_136_)
  );
  NOR _482_ (
    .A(_134_),
    .B(_136_),
    .Y(_007_[27])
  );
  NOR _483_ (
    .A(valorTrans[28]),
    .B(_124_),
    .Y(_137_)
  );
  NAND _484_ (
    .A(_018_),
    .B(_124_),
    .Y(_138_)
  );
  NAND _485_ (
    .A(_026_),
    .B(_138_),
    .Y(_139_)
  );
  NOR _486_ (
    .A(_137_),
    .B(_139_),
    .Y(_007_[28])
  );
  NOR _487_ (
    .A(valorTrans[29]),
    .B(_124_),
    .Y(_140_)
  );
  NAND _488_ (
    .A(_020_),
    .B(_124_),
    .Y(_141_)
  );
  NAND _489_ (
    .A(_026_),
    .B(_141_),
    .Y(_142_)
  );
  NOR _490_ (
    .A(_140_),
    .B(_142_),
    .Y(_007_[29])
  );
  NOR _491_ (
    .A(valorTrans[30]),
    .B(_124_),
    .Y(_143_)
  );
  NAND _492_ (
    .A(_022_),
    .B(_124_),
    .Y(_144_)
  );
  NAND _493_ (
    .A(_026_),
    .B(_144_),
    .Y(_145_)
  );
  NOR _494_ (
    .A(_143_),
    .B(_145_),
    .Y(_007_[30])
  );
  NOR _495_ (
    .A(valorTrans[31]),
    .B(_124_),
    .Y(_146_)
  );
  NAND _496_ (
    .A(_024_),
    .B(_124_),
    .Y(_147_)
  );
  NAND _497_ (
    .A(_026_),
    .B(_147_),
    .Y(_148_)
  );
  NOR _498_ (
    .A(_146_),
    .B(_148_),
    .Y(_007_[31])
  );
  NOR _499_ (
    .A(reset),
    .B(contador_clk[0]),
    .Y(_000_[0])
  );
  NAND _500_ (
    .A(contador_clk[1]),
    .B(contador_clk[0]),
    .Y(_149_)
  );
  NOT _501_ (
    .A(_149_),
    .Y(_150_)
  );
  NOR _502_ (
    .A(contador_clk[1]),
    .B(contador_clk[0]),
    .Y(_151_)
  );
  NOR _503_ (
    .A(reset),
    .B(_151_),
    .Y(_152_)
  );
  NAND _504_ (
    .A(_149_),
    .B(_152_),
    .Y(_153_)
  );
  NOT _505_ (
    .A(_153_),
    .Y(_000_[1])
  );
  NOR _506_ (
    .A(selector[0]),
    .B(valid_0),
    .Y(_154_)
  );
  NAND _507_ (
    .A(_026_),
    .B(_077_),
    .Y(_155_)
  );
  NOR _508_ (
    .A(_154_),
    .B(_155_),
    .Y(_002_[0])
  );
  NOR _509_ (
    .A(selector[1]),
    .B(_078_),
    .Y(_156_)
  );
  NOR _510_ (
    .A(_082_),
    .B(_156_),
    .Y(_002_[1])
  );
  NOR _511_ (
    .A(reset),
    .B(_149_),
    .Y(_157_)
  );
  NOT _512_ (
    .A(_157_),
    .Y(_158_)
  );
  NAND _513_ (
    .A(valid_out_sintetizado),
    .B(_158_),
    .Y(_159_)
  );
  NAND _514_ (
    .A(validTemp2),
    .B(_150_),
    .Y(_160_)
  );
  NOR _515_ (
    .A(reset),
    .B(_160_),
    .Y(_161_)
  );
  NAND _516_ (
    .A(validTemp2),
    .B(_157_),
    .Y(_162_)
  );
  NAND _517_ (
    .A(_159_),
    .B(_162_),
    .Y(_005_)
  );
  NOR _518_ (
    .A(valorTrans2[0]),
    .B(validTemp),
    .Y(_163_)
  );
  NAND _519_ (
    .A(_027_),
    .B(validTemp),
    .Y(_164_)
  );
  NAND _520_ (
    .A(_026_),
    .B(_164_),
    .Y(_165_)
  );
  NOR _521_ (
    .A(_163_),
    .B(_165_),
    .Y(_006_[0])
  );
  NOR _522_ (
    .A(validTemp),
    .B(valorTrans2[1]),
    .Y(_166_)
  );
  NAND _523_ (
    .A(_028_),
    .B(validTemp),
    .Y(_167_)
  );
  NAND _524_ (
    .A(_026_),
    .B(_167_),
    .Y(_168_)
  );
  NOR _525_ (
    .A(_166_),
    .B(_168_),
    .Y(_006_[1])
  );
  NOR _526_ (
    .A(validTemp),
    .B(valorTrans2[2]),
    .Y(_169_)
  );
  NAND _527_ (
    .A(_029_),
    .B(validTemp),
    .Y(_170_)
  );
  NAND _528_ (
    .A(_026_),
    .B(_170_),
    .Y(_171_)
  );
  NOR _529_ (
    .A(_169_),
    .B(_171_),
    .Y(_006_[2])
  );
  NOR _530_ (
    .A(validTemp),
    .B(valorTrans2[3]),
    .Y(_172_)
  );
  NAND _531_ (
    .A(_030_),
    .B(validTemp),
    .Y(_173_)
  );
  NAND _532_ (
    .A(_026_),
    .B(_173_),
    .Y(_174_)
  );
  NOR _533_ (
    .A(_172_),
    .B(_174_),
    .Y(_006_[3])
  );
  NOR _534_ (
    .A(validTemp),
    .B(valorTrans2[4]),
    .Y(_175_)
  );
  NAND _535_ (
    .A(_031_),
    .B(validTemp),
    .Y(_176_)
  );
  NAND _536_ (
    .A(_026_),
    .B(_176_),
    .Y(_177_)
  );
  NOR _537_ (
    .A(_175_),
    .B(_177_),
    .Y(_006_[4])
  );
  NOR _538_ (
    .A(validTemp),
    .B(valorTrans2[5]),
    .Y(_178_)
  );
  NAND _539_ (
    .A(_032_),
    .B(validTemp),
    .Y(_179_)
  );
  NAND _540_ (
    .A(_026_),
    .B(_179_),
    .Y(_180_)
  );
  NOR _541_ (
    .A(_178_),
    .B(_180_),
    .Y(_006_[5])
  );
  NOR _542_ (
    .A(validTemp),
    .B(valorTrans2[6]),
    .Y(_181_)
  );
  NAND _543_ (
    .A(_033_),
    .B(validTemp),
    .Y(_182_)
  );
  NAND _544_ (
    .A(_026_),
    .B(_182_),
    .Y(_183_)
  );
  NOR _545_ (
    .A(_181_),
    .B(_183_),
    .Y(_006_[6])
  );
  NOR _546_ (
    .A(validTemp),
    .B(valorTrans2[7]),
    .Y(_184_)
  );
  NAND _547_ (
    .A(_034_),
    .B(validTemp),
    .Y(_185_)
  );
  NAND _548_ (
    .A(_026_),
    .B(_185_),
    .Y(_186_)
  );
  NOR _549_ (
    .A(_184_),
    .B(_186_),
    .Y(_006_[7])
  );
  NOR _550_ (
    .A(validTemp),
    .B(valorTrans2[8]),
    .Y(_187_)
  );
  NAND _551_ (
    .A(_011_),
    .B(validTemp),
    .Y(_188_)
  );
  NAND _552_ (
    .A(_026_),
    .B(_188_),
    .Y(_189_)
  );
  NOR _553_ (
    .A(_187_),
    .B(_189_),
    .Y(_006_[8])
  );
  NOR _554_ (
    .A(validTemp),
    .B(valorTrans2[9]),
    .Y(_190_)
  );
  NAND _555_ (
    .A(_013_),
    .B(validTemp),
    .Y(_191_)
  );
  NAND _556_ (
    .A(_026_),
    .B(_191_),
    .Y(_192_)
  );
  NOR _557_ (
    .A(_190_),
    .B(_192_),
    .Y(_006_[9])
  );
  NOR _558_ (
    .A(validTemp),
    .B(valorTrans2[10]),
    .Y(_193_)
  );
  NAND _559_ (
    .A(_015_),
    .B(validTemp),
    .Y(_194_)
  );
  NAND _560_ (
    .A(_026_),
    .B(_194_),
    .Y(_195_)
  );
  NOR _561_ (
    .A(_193_),
    .B(_195_),
    .Y(_006_[10])
  );
  NOR _562_ (
    .A(validTemp),
    .B(valorTrans2[11]),
    .Y(_196_)
  );
  NAND _563_ (
    .A(_017_),
    .B(validTemp),
    .Y(_197_)
  );
  NAND _564_ (
    .A(_026_),
    .B(_197_),
    .Y(_198_)
  );
  NOR _565_ (
    .A(_196_),
    .B(_198_),
    .Y(_006_[11])
  );
  NOR _566_ (
    .A(validTemp),
    .B(valorTrans2[12]),
    .Y(_199_)
  );
  NAND _567_ (
    .A(_019_),
    .B(validTemp),
    .Y(_200_)
  );
  NAND _568_ (
    .A(_026_),
    .B(_200_),
    .Y(_201_)
  );
  NOR _569_ (
    .A(_199_),
    .B(_201_),
    .Y(_006_[12])
  );
  NOR _570_ (
    .A(validTemp),
    .B(valorTrans2[13]),
    .Y(_202_)
  );
  NAND _571_ (
    .A(_021_),
    .B(validTemp),
    .Y(_203_)
  );
  NAND _572_ (
    .A(_026_),
    .B(_203_),
    .Y(_204_)
  );
  NOR _573_ (
    .A(_202_),
    .B(_204_),
    .Y(_006_[13])
  );
  NOR _574_ (
    .A(validTemp),
    .B(valorTrans2[14]),
    .Y(_205_)
  );
  NAND _575_ (
    .A(_023_),
    .B(validTemp),
    .Y(_206_)
  );
  NAND _576_ (
    .A(_026_),
    .B(_206_),
    .Y(_207_)
  );
  NOR _577_ (
    .A(_205_),
    .B(_207_),
    .Y(_006_[14])
  );
  NOR _578_ (
    .A(validTemp),
    .B(valorTrans2[15]),
    .Y(_208_)
  );
  NAND _579_ (
    .A(_025_),
    .B(validTemp),
    .Y(_209_)
  );
  NAND _580_ (
    .A(_026_),
    .B(_209_),
    .Y(_210_)
  );
  NOR _581_ (
    .A(_208_),
    .B(_210_),
    .Y(_006_[15])
  );
  NOR _582_ (
    .A(validTemp),
    .B(valorTrans2[16]),
    .Y(_211_)
  );
  NAND _583_ (
    .A(_035_),
    .B(validTemp),
    .Y(_212_)
  );
  NAND _584_ (
    .A(_026_),
    .B(_212_),
    .Y(_213_)
  );
  NOR _585_ (
    .A(_211_),
    .B(_213_),
    .Y(_006_[16])
  );
  NOR _586_ (
    .A(validTemp),
    .B(valorTrans2[17]),
    .Y(_214_)
  );
  NAND _587_ (
    .A(_036_),
    .B(validTemp),
    .Y(_215_)
  );
  NAND _588_ (
    .A(_026_),
    .B(_215_),
    .Y(_216_)
  );
  NOR _589_ (
    .A(_214_),
    .B(_216_),
    .Y(_006_[17])
  );
  NOR _590_ (
    .A(validTemp),
    .B(valorTrans2[18]),
    .Y(_217_)
  );
  NAND _591_ (
    .A(_037_),
    .B(validTemp),
    .Y(_218_)
  );
  NAND _592_ (
    .A(_026_),
    .B(_218_),
    .Y(_219_)
  );
  NOR _593_ (
    .A(_217_),
    .B(_219_),
    .Y(_006_[18])
  );
  NOR _594_ (
    .A(validTemp),
    .B(valorTrans2[19]),
    .Y(_220_)
  );
  NAND _595_ (
    .A(_038_),
    .B(validTemp),
    .Y(_221_)
  );
  NAND _596_ (
    .A(_026_),
    .B(_221_),
    .Y(_222_)
  );
  NOR _597_ (
    .A(_220_),
    .B(_222_),
    .Y(_006_[19])
  );
  NOR _598_ (
    .A(validTemp),
    .B(valorTrans2[20]),
    .Y(_223_)
  );
  NAND _599_ (
    .A(_039_),
    .B(validTemp),
    .Y(_224_)
  );
  NAND _600_ (
    .A(_026_),
    .B(_224_),
    .Y(_225_)
  );
  NOR _601_ (
    .A(_223_),
    .B(_225_),
    .Y(_006_[20])
  );
  NOR _602_ (
    .A(validTemp),
    .B(valorTrans2[21]),
    .Y(_226_)
  );
  NAND _603_ (
    .A(_040_),
    .B(validTemp),
    .Y(_227_)
  );
  NAND _604_ (
    .A(_026_),
    .B(_227_),
    .Y(_228_)
  );
  NOR _605_ (
    .A(_226_),
    .B(_228_),
    .Y(_006_[21])
  );
  NOR _606_ (
    .A(validTemp),
    .B(valorTrans2[22]),
    .Y(_229_)
  );
  NAND _607_ (
    .A(_041_),
    .B(validTemp),
    .Y(_230_)
  );
  NAND _608_ (
    .A(_026_),
    .B(_230_),
    .Y(_231_)
  );
  NOR _609_ (
    .A(_229_),
    .B(_231_),
    .Y(_006_[22])
  );
  NOR _610_ (
    .A(validTemp),
    .B(valorTrans2[23]),
    .Y(_232_)
  );
  NAND _611_ (
    .A(_042_),
    .B(validTemp),
    .Y(_233_)
  );
  NAND _612_ (
    .A(_026_),
    .B(_233_),
    .Y(_234_)
  );
  NOR _613_ (
    .A(_232_),
    .B(_234_),
    .Y(_006_[23])
  );
  NOR _614_ (
    .A(validTemp),
    .B(valorTrans2[24]),
    .Y(_235_)
  );
  NAND _615_ (
    .A(_043_),
    .B(validTemp),
    .Y(_236_)
  );
  NAND _616_ (
    .A(_026_),
    .B(_236_),
    .Y(_237_)
  );
  NOR _617_ (
    .A(_235_),
    .B(_237_),
    .Y(_006_[24])
  );
  NOR _618_ (
    .A(validTemp),
    .B(valorTrans2[25]),
    .Y(_238_)
  );
  NAND _619_ (
    .A(_044_),
    .B(validTemp),
    .Y(_239_)
  );
  NAND _620_ (
    .A(_026_),
    .B(_239_),
    .Y(_240_)
  );
  NOR _621_ (
    .A(_238_),
    .B(_240_),
    .Y(_006_[25])
  );
  NOR _622_ (
    .A(validTemp),
    .B(valorTrans2[26]),
    .Y(_241_)
  );
  NAND _623_ (
    .A(_045_),
    .B(validTemp),
    .Y(_242_)
  );
  NAND _624_ (
    .A(_026_),
    .B(_242_),
    .Y(_243_)
  );
  NOR _625_ (
    .A(_241_),
    .B(_243_),
    .Y(_006_[26])
  );
  NOR _626_ (
    .A(validTemp),
    .B(valorTrans2[27]),
    .Y(_244_)
  );
  NAND _627_ (
    .A(_046_),
    .B(validTemp),
    .Y(_245_)
  );
  NAND _628_ (
    .A(_026_),
    .B(_245_),
    .Y(_246_)
  );
  NOR _629_ (
    .A(_244_),
    .B(_246_),
    .Y(_006_[27])
  );
  NOR _630_ (
    .A(validTemp),
    .B(valorTrans2[28]),
    .Y(_247_)
  );
  NAND _631_ (
    .A(_047_),
    .B(validTemp),
    .Y(_248_)
  );
  NAND _632_ (
    .A(_026_),
    .B(_248_),
    .Y(_249_)
  );
  NOR _633_ (
    .A(_247_),
    .B(_249_),
    .Y(_006_[28])
  );
  NOR _634_ (
    .A(validTemp),
    .B(valorTrans2[29]),
    .Y(_250_)
  );
  NAND _635_ (
    .A(_048_),
    .B(validTemp),
    .Y(_251_)
  );
  NAND _636_ (
    .A(_026_),
    .B(_251_),
    .Y(_252_)
  );
  NOR _637_ (
    .A(_250_),
    .B(_252_),
    .Y(_006_[29])
  );
  NOR _638_ (
    .A(validTemp),
    .B(valorTrans2[30]),
    .Y(_253_)
  );
  NAND _639_ (
    .A(_049_),
    .B(validTemp),
    .Y(_254_)
  );
  NAND _640_ (
    .A(_026_),
    .B(_254_),
    .Y(_255_)
  );
  NOR _641_ (
    .A(_253_),
    .B(_255_),
    .Y(_006_[30])
  );
  NOR _642_ (
    .A(validTemp),
    .B(valorTrans2[31]),
    .Y(_256_)
  );
  NAND _643_ (
    .A(_050_),
    .B(validTemp),
    .Y(_257_)
  );
  NAND _644_ (
    .A(_026_),
    .B(_257_),
    .Y(_258_)
  );
  NOR _645_ (
    .A(_256_),
    .B(_258_),
    .Y(_006_[31])
  );
  NOR _646_ (
    .A(validTemp),
    .B(validTemp2),
    .Y(_259_)
  );
  NAND _647_ (
    .A(_026_),
    .B(_160_),
    .Y(_260_)
  );
  NOR _648_ (
    .A(_259_),
    .B(_260_),
    .Y(_003_)
  );
  NAND _649_ (
    .A(valorTrans2[0]),
    .B(_161_),
    .Y(_261_)
  );
  NAND _650_ (
    .A(data_out_sintetizado[0]),
    .B(_162_),
    .Y(_262_)
  );
  NAND _651_ (
    .A(_261_),
    .B(_262_),
    .Y(_001_[0])
  );
  NAND _652_ (
    .A(valorTrans2[1]),
    .B(_161_),
    .Y(_263_)
  );
  NAND _653_ (
    .A(data_out_sintetizado[1]),
    .B(_162_),
    .Y(_264_)
  );
  NAND _654_ (
    .A(_263_),
    .B(_264_),
    .Y(_001_[1])
  );
  NAND _655_ (
    .A(valorTrans2[2]),
    .B(_161_),
    .Y(_265_)
  );
  NAND _656_ (
    .A(data_out_sintetizado[2]),
    .B(_162_),
    .Y(_266_)
  );
  NAND _657_ (
    .A(_265_),
    .B(_266_),
    .Y(_001_[2])
  );
  NAND _658_ (
    .A(valorTrans2[3]),
    .B(_161_),
    .Y(_267_)
  );
  NAND _659_ (
    .A(data_out_sintetizado[3]),
    .B(_162_),
    .Y(_268_)
  );
  NAND _660_ (
    .A(_267_),
    .B(_268_),
    .Y(_001_[3])
  );
  NAND _661_ (
    .A(valorTrans2[4]),
    .B(_161_),
    .Y(_269_)
  );
  NAND _662_ (
    .A(data_out_sintetizado[4]),
    .B(_162_),
    .Y(_270_)
  );
  NAND _663_ (
    .A(_269_),
    .B(_270_),
    .Y(_001_[4])
  );
  NAND _664_ (
    .A(valorTrans2[5]),
    .B(_161_),
    .Y(_271_)
  );
  NAND _665_ (
    .A(data_out_sintetizado[5]),
    .B(_162_),
    .Y(_272_)
  );
  NAND _666_ (
    .A(_271_),
    .B(_272_),
    .Y(_001_[5])
  );
  NAND _667_ (
    .A(valorTrans2[6]),
    .B(_161_),
    .Y(_273_)
  );
  NAND _668_ (
    .A(data_out_sintetizado[6]),
    .B(_162_),
    .Y(_274_)
  );
  NAND _669_ (
    .A(_273_),
    .B(_274_),
    .Y(_001_[6])
  );
  NAND _670_ (
    .A(valorTrans2[7]),
    .B(_161_),
    .Y(_275_)
  );
  NAND _671_ (
    .A(data_out_sintetizado[7]),
    .B(_162_),
    .Y(_276_)
  );
  NAND _672_ (
    .A(_275_),
    .B(_276_),
    .Y(_001_[7])
  );
  NAND _673_ (
    .A(valorTrans2[8]),
    .B(_161_),
    .Y(_277_)
  );
  NAND _674_ (
    .A(data_out_sintetizado[8]),
    .B(_162_),
    .Y(_278_)
  );
  NAND _675_ (
    .A(_277_),
    .B(_278_),
    .Y(_001_[8])
  );
  NAND _676_ (
    .A(valorTrans2[9]),
    .B(_161_),
    .Y(_279_)
  );
  NAND _677_ (
    .A(data_out_sintetizado[9]),
    .B(_162_),
    .Y(_280_)
  );
  NAND _678_ (
    .A(_279_),
    .B(_280_),
    .Y(_001_[9])
  );
  NAND _679_ (
    .A(valorTrans2[10]),
    .B(_161_),
    .Y(_281_)
  );
  NAND _680_ (
    .A(data_out_sintetizado[10]),
    .B(_162_),
    .Y(_282_)
  );
  NAND _681_ (
    .A(_281_),
    .B(_282_),
    .Y(_001_[10])
  );
  NAND _682_ (
    .A(valorTrans2[11]),
    .B(_161_),
    .Y(_283_)
  );
  NAND _683_ (
    .A(data_out_sintetizado[11]),
    .B(_162_),
    .Y(_284_)
  );
  NAND _684_ (
    .A(_283_),
    .B(_284_),
    .Y(_001_[11])
  );
  NAND _685_ (
    .A(valorTrans2[12]),
    .B(_161_),
    .Y(_285_)
  );
  NAND _686_ (
    .A(data_out_sintetizado[12]),
    .B(_162_),
    .Y(_286_)
  );
  NAND _687_ (
    .A(_285_),
    .B(_286_),
    .Y(_001_[12])
  );
  NAND _688_ (
    .A(valorTrans2[13]),
    .B(_161_),
    .Y(_287_)
  );
  NAND _689_ (
    .A(data_out_sintetizado[13]),
    .B(_162_),
    .Y(_288_)
  );
  NAND _690_ (
    .A(_287_),
    .B(_288_),
    .Y(_001_[13])
  );
  NAND _691_ (
    .A(valorTrans2[14]),
    .B(_161_),
    .Y(_289_)
  );
  NAND _692_ (
    .A(data_out_sintetizado[14]),
    .B(_162_),
    .Y(_290_)
  );
  NAND _693_ (
    .A(_289_),
    .B(_290_),
    .Y(_001_[14])
  );
  NAND _694_ (
    .A(valorTrans2[15]),
    .B(_161_),
    .Y(_291_)
  );
  NAND _695_ (
    .A(data_out_sintetizado[15]),
    .B(_162_),
    .Y(_292_)
  );
  NAND _696_ (
    .A(_291_),
    .B(_292_),
    .Y(_001_[15])
  );
  NAND _697_ (
    .A(valorTrans2[16]),
    .B(_161_),
    .Y(_293_)
  );
  NAND _698_ (
    .A(data_out_sintetizado[16]),
    .B(_162_),
    .Y(_294_)
  );
  NAND _699_ (
    .A(_293_),
    .B(_294_),
    .Y(_001_[16])
  );
  NAND _700_ (
    .A(valorTrans2[17]),
    .B(_161_),
    .Y(_295_)
  );
  NAND _701_ (
    .A(data_out_sintetizado[17]),
    .B(_162_),
    .Y(_296_)
  );
  NAND _702_ (
    .A(_295_),
    .B(_296_),
    .Y(_001_[17])
  );
  NAND _703_ (
    .A(valorTrans2[18]),
    .B(_161_),
    .Y(_297_)
  );
  NAND _704_ (
    .A(data_out_sintetizado[18]),
    .B(_162_),
    .Y(_298_)
  );
  NAND _705_ (
    .A(_297_),
    .B(_298_),
    .Y(_001_[18])
  );
  NAND _706_ (
    .A(valorTrans2[19]),
    .B(_161_),
    .Y(_299_)
  );
  NAND _707_ (
    .A(data_out_sintetizado[19]),
    .B(_162_),
    .Y(_300_)
  );
  NAND _708_ (
    .A(_299_),
    .B(_300_),
    .Y(_001_[19])
  );
  NAND _709_ (
    .A(valorTrans2[20]),
    .B(_161_),
    .Y(_301_)
  );
  NAND _710_ (
    .A(data_out_sintetizado[20]),
    .B(_162_),
    .Y(_302_)
  );
  NAND _711_ (
    .A(_301_),
    .B(_302_),
    .Y(_001_[20])
  );
  NAND _712_ (
    .A(valorTrans2[21]),
    .B(_161_),
    .Y(_303_)
  );
  NAND _713_ (
    .A(data_out_sintetizado[21]),
    .B(_162_),
    .Y(_304_)
  );
  NAND _714_ (
    .A(_303_),
    .B(_304_),
    .Y(_001_[21])
  );
  NAND _715_ (
    .A(valorTrans2[22]),
    .B(_161_),
    .Y(_305_)
  );
  NAND _716_ (
    .A(data_out_sintetizado[22]),
    .B(_162_),
    .Y(_306_)
  );
  NAND _717_ (
    .A(_305_),
    .B(_306_),
    .Y(_001_[22])
  );
  NAND _718_ (
    .A(valorTrans2[23]),
    .B(_161_),
    .Y(_307_)
  );
  NAND _719_ (
    .A(data_out_sintetizado[23]),
    .B(_162_),
    .Y(_308_)
  );
  NAND _720_ (
    .A(_307_),
    .B(_308_),
    .Y(_001_[23])
  );
  NAND _721_ (
    .A(valorTrans2[24]),
    .B(_161_),
    .Y(_309_)
  );
  NAND _722_ (
    .A(data_out_sintetizado[24]),
    .B(_162_),
    .Y(_310_)
  );
  NAND _723_ (
    .A(_309_),
    .B(_310_),
    .Y(_001_[24])
  );
  NAND _724_ (
    .A(valorTrans2[25]),
    .B(_161_),
    .Y(_311_)
  );
  NAND _725_ (
    .A(data_out_sintetizado[25]),
    .B(_162_),
    .Y(_312_)
  );
  NAND _726_ (
    .A(_311_),
    .B(_312_),
    .Y(_001_[25])
  );
  NAND _727_ (
    .A(valorTrans2[26]),
    .B(_161_),
    .Y(_313_)
  );
  NAND _728_ (
    .A(data_out_sintetizado[26]),
    .B(_162_),
    .Y(_314_)
  );
  NAND _729_ (
    .A(_313_),
    .B(_314_),
    .Y(_001_[26])
  );
  NAND _730_ (
    .A(valorTrans2[27]),
    .B(_161_),
    .Y(_315_)
  );
  NAND _731_ (
    .A(data_out_sintetizado[27]),
    .B(_162_),
    .Y(_316_)
  );
  NAND _732_ (
    .A(_315_),
    .B(_316_),
    .Y(_001_[27])
  );
  NAND _733_ (
    .A(valorTrans2[28]),
    .B(_161_),
    .Y(_317_)
  );
  NAND _734_ (
    .A(data_out_sintetizado[28]),
    .B(_162_),
    .Y(_318_)
  );
  NAND _735_ (
    .A(_317_),
    .B(_318_),
    .Y(_001_[28])
  );
  NAND _736_ (
    .A(valorTrans2[29]),
    .B(_161_),
    .Y(_319_)
  );
  NAND _737_ (
    .A(data_out_sintetizado[29]),
    .B(_162_),
    .Y(_320_)
  );
  NAND _738_ (
    .A(_319_),
    .B(_320_),
    .Y(_001_[29])
  );
  NAND _739_ (
    .A(valorTrans2[30]),
    .B(_161_),
    .Y(_321_)
  );
  NAND _740_ (
    .A(data_out_sintetizado[30]),
    .B(_162_),
    .Y(_322_)
  );
  NAND _741_ (
    .A(_321_),
    .B(_322_),
    .Y(_001_[30])
  );
  NAND _742_ (
    .A(valorTrans2[31]),
    .B(_161_),
    .Y(_323_)
  );
  NAND _743_ (
    .A(data_out_sintetizado[31]),
    .B(_162_),
    .Y(_324_)
  );
  NAND _744_ (
    .A(_323_),
    .B(_324_),
    .Y(_001_[31])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _745_ (
    .C(clk_4f),
    .D(_001_[0]),
    .Q(data_out_sintetizado[0])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _746_ (
    .C(clk_4f),
    .D(_001_[1]),
    .Q(data_out_sintetizado[1])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _747_ (
    .C(clk_4f),
    .D(_001_[2]),
    .Q(data_out_sintetizado[2])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _748_ (
    .C(clk_4f),
    .D(_001_[3]),
    .Q(data_out_sintetizado[3])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _749_ (
    .C(clk_4f),
    .D(_001_[4]),
    .Q(data_out_sintetizado[4])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _750_ (
    .C(clk_4f),
    .D(_001_[5]),
    .Q(data_out_sintetizado[5])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _751_ (
    .C(clk_4f),
    .D(_001_[6]),
    .Q(data_out_sintetizado[6])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _752_ (
    .C(clk_4f),
    .D(_001_[7]),
    .Q(data_out_sintetizado[7])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _753_ (
    .C(clk_4f),
    .D(_001_[8]),
    .Q(data_out_sintetizado[8])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _754_ (
    .C(clk_4f),
    .D(_001_[9]),
    .Q(data_out_sintetizado[9])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _755_ (
    .C(clk_4f),
    .D(_001_[10]),
    .Q(data_out_sintetizado[10])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _756_ (
    .C(clk_4f),
    .D(_001_[11]),
    .Q(data_out_sintetizado[11])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _757_ (
    .C(clk_4f),
    .D(_001_[12]),
    .Q(data_out_sintetizado[12])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _758_ (
    .C(clk_4f),
    .D(_001_[13]),
    .Q(data_out_sintetizado[13])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _759_ (
    .C(clk_4f),
    .D(_001_[14]),
    .Q(data_out_sintetizado[14])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _760_ (
    .C(clk_4f),
    .D(_001_[15]),
    .Q(data_out_sintetizado[15])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _761_ (
    .C(clk_4f),
    .D(_001_[16]),
    .Q(data_out_sintetizado[16])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _762_ (
    .C(clk_4f),
    .D(_001_[17]),
    .Q(data_out_sintetizado[17])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _763_ (
    .C(clk_4f),
    .D(_001_[18]),
    .Q(data_out_sintetizado[18])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _764_ (
    .C(clk_4f),
    .D(_001_[19]),
    .Q(data_out_sintetizado[19])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _765_ (
    .C(clk_4f),
    .D(_001_[20]),
    .Q(data_out_sintetizado[20])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _766_ (
    .C(clk_4f),
    .D(_001_[21]),
    .Q(data_out_sintetizado[21])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _767_ (
    .C(clk_4f),
    .D(_001_[22]),
    .Q(data_out_sintetizado[22])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _768_ (
    .C(clk_4f),
    .D(_001_[23]),
    .Q(data_out_sintetizado[23])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _769_ (
    .C(clk_4f),
    .D(_001_[24]),
    .Q(data_out_sintetizado[24])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _770_ (
    .C(clk_4f),
    .D(_001_[25]),
    .Q(data_out_sintetizado[25])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _771_ (
    .C(clk_4f),
    .D(_001_[26]),
    .Q(data_out_sintetizado[26])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _772_ (
    .C(clk_4f),
    .D(_001_[27]),
    .Q(data_out_sintetizado[27])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _773_ (
    .C(clk_4f),
    .D(_001_[28]),
    .Q(data_out_sintetizado[28])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _774_ (
    .C(clk_4f),
    .D(_001_[29]),
    .Q(data_out_sintetizado[29])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _775_ (
    .C(clk_4f),
    .D(_001_[30]),
    .Q(data_out_sintetizado[30])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _776_ (
    .C(clk_4f),
    .D(_001_[31]),
    .Q(data_out_sintetizado[31])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _777_ (
    .C(clk_4f),
    .D(_007_[0]),
    .Q(valorTrans[0])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _778_ (
    .C(clk_4f),
    .D(_007_[1]),
    .Q(valorTrans[1])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _779_ (
    .C(clk_4f),
    .D(_007_[2]),
    .Q(valorTrans[2])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _780_ (
    .C(clk_4f),
    .D(_007_[3]),
    .Q(valorTrans[3])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _781_ (
    .C(clk_4f),
    .D(_007_[4]),
    .Q(valorTrans[4])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _782_ (
    .C(clk_4f),
    .D(_007_[5]),
    .Q(valorTrans[5])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _783_ (
    .C(clk_4f),
    .D(_007_[6]),
    .Q(valorTrans[6])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _784_ (
    .C(clk_4f),
    .D(_007_[7]),
    .Q(valorTrans[7])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _785_ (
    .C(clk_4f),
    .D(_007_[8]),
    .Q(valorTrans[8])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _786_ (
    .C(clk_4f),
    .D(_007_[9]),
    .Q(valorTrans[9])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _787_ (
    .C(clk_4f),
    .D(_007_[10]),
    .Q(valorTrans[10])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _788_ (
    .C(clk_4f),
    .D(_007_[11]),
    .Q(valorTrans[11])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _789_ (
    .C(clk_4f),
    .D(_007_[12]),
    .Q(valorTrans[12])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _790_ (
    .C(clk_4f),
    .D(_007_[13]),
    .Q(valorTrans[13])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _791_ (
    .C(clk_4f),
    .D(_007_[14]),
    .Q(valorTrans[14])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _792_ (
    .C(clk_4f),
    .D(_007_[15]),
    .Q(valorTrans[15])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _793_ (
    .C(clk_4f),
    .D(_007_[16]),
    .Q(valorTrans[16])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _794_ (
    .C(clk_4f),
    .D(_007_[17]),
    .Q(valorTrans[17])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _795_ (
    .C(clk_4f),
    .D(_007_[18]),
    .Q(valorTrans[18])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _796_ (
    .C(clk_4f),
    .D(_007_[19]),
    .Q(valorTrans[19])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _797_ (
    .C(clk_4f),
    .D(_007_[20]),
    .Q(valorTrans[20])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _798_ (
    .C(clk_4f),
    .D(_007_[21]),
    .Q(valorTrans[21])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _799_ (
    .C(clk_4f),
    .D(_007_[22]),
    .Q(valorTrans[22])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _800_ (
    .C(clk_4f),
    .D(_007_[23]),
    .Q(valorTrans[23])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _801_ (
    .C(clk_4f),
    .D(_007_[24]),
    .Q(valorTrans[24])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _802_ (
    .C(clk_4f),
    .D(_007_[25]),
    .Q(valorTrans[25])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _803_ (
    .C(clk_4f),
    .D(_007_[26]),
    .Q(valorTrans[26])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _804_ (
    .C(clk_4f),
    .D(_007_[27]),
    .Q(valorTrans[27])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _805_ (
    .C(clk_4f),
    .D(_007_[28]),
    .Q(valorTrans[28])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _806_ (
    .C(clk_4f),
    .D(_007_[29]),
    .Q(valorTrans[29])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _807_ (
    .C(clk_4f),
    .D(_007_[30]),
    .Q(valorTrans[30])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _808_ (
    .C(clk_4f),
    .D(_007_[31]),
    .Q(valorTrans[31])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _809_ (
    .C(clk_4f),
    .D(_006_[0]),
    .Q(valorTrans2[0])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _810_ (
    .C(clk_4f),
    .D(_006_[1]),
    .Q(valorTrans2[1])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _811_ (
    .C(clk_4f),
    .D(_006_[2]),
    .Q(valorTrans2[2])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _812_ (
    .C(clk_4f),
    .D(_006_[3]),
    .Q(valorTrans2[3])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _813_ (
    .C(clk_4f),
    .D(_006_[4]),
    .Q(valorTrans2[4])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _814_ (
    .C(clk_4f),
    .D(_006_[5]),
    .Q(valorTrans2[5])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _815_ (
    .C(clk_4f),
    .D(_006_[6]),
    .Q(valorTrans2[6])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _816_ (
    .C(clk_4f),
    .D(_006_[7]),
    .Q(valorTrans2[7])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _817_ (
    .C(clk_4f),
    .D(_006_[8]),
    .Q(valorTrans2[8])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _818_ (
    .C(clk_4f),
    .D(_006_[9]),
    .Q(valorTrans2[9])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _819_ (
    .C(clk_4f),
    .D(_006_[10]),
    .Q(valorTrans2[10])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _820_ (
    .C(clk_4f),
    .D(_006_[11]),
    .Q(valorTrans2[11])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _821_ (
    .C(clk_4f),
    .D(_006_[12]),
    .Q(valorTrans2[12])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _822_ (
    .C(clk_4f),
    .D(_006_[13]),
    .Q(valorTrans2[13])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _823_ (
    .C(clk_4f),
    .D(_006_[14]),
    .Q(valorTrans2[14])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _824_ (
    .C(clk_4f),
    .D(_006_[15]),
    .Q(valorTrans2[15])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _825_ (
    .C(clk_4f),
    .D(_006_[16]),
    .Q(valorTrans2[16])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _826_ (
    .C(clk_4f),
    .D(_006_[17]),
    .Q(valorTrans2[17])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _827_ (
    .C(clk_4f),
    .D(_006_[18]),
    .Q(valorTrans2[18])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _828_ (
    .C(clk_4f),
    .D(_006_[19]),
    .Q(valorTrans2[19])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _829_ (
    .C(clk_4f),
    .D(_006_[20]),
    .Q(valorTrans2[20])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _830_ (
    .C(clk_4f),
    .D(_006_[21]),
    .Q(valorTrans2[21])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _831_ (
    .C(clk_4f),
    .D(_006_[22]),
    .Q(valorTrans2[22])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _832_ (
    .C(clk_4f),
    .D(_006_[23]),
    .Q(valorTrans2[23])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _833_ (
    .C(clk_4f),
    .D(_006_[24]),
    .Q(valorTrans2[24])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _834_ (
    .C(clk_4f),
    .D(_006_[25]),
    .Q(valorTrans2[25])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _835_ (
    .C(clk_4f),
    .D(_006_[26]),
    .Q(valorTrans2[26])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _836_ (
    .C(clk_4f),
    .D(_006_[27]),
    .Q(valorTrans2[27])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _837_ (
    .C(clk_4f),
    .D(_006_[28]),
    .Q(valorTrans2[28])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _838_ (
    .C(clk_4f),
    .D(_006_[29]),
    .Q(valorTrans2[29])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _839_ (
    .C(clk_4f),
    .D(_006_[30]),
    .Q(valorTrans2[30])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _840_ (
    .C(clk_4f),
    .D(_006_[31]),
    .Q(valorTrans2[31])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _841_ (
    .C(clk_4f),
    .D(_005_),
    .Q(valid_out_sintetizado)
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _842_ (
    .C(clk_4f),
    .D(_002_[0]),
    .Q(selector[0])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _843_ (
    .C(clk_4f),
    .D(_002_[1]),
    .Q(selector[1])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _844_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(contador_clk[0])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _845_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(contador_clk[1])
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _846_ (
    .C(clk_4f),
    .D(_004_),
    .Q(validTemp)
  );
  (* src = "paso8bto32b_sintetizado.v:16" *)
  DFF _847_ (
    .C(clk_4f),
    .D(_003_),
    .Q(validTemp2)
  );
endmodule
