/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "serialParalelo_sintetizado.v:2" *)
module serialParalelo_sintetizado(clk_32f, clk_4f, data_in, reset, data_out_sintetizado, valid_out_sintetizado);
  (* src = "serialParalelo_sintetizado.v:24" *)
  wire [2:0] _000_;
  (* src = "serialParalelo_sintetizado.v:24" *)
  wire _001_;
  (* src = "serialParalelo_sintetizado.v:24" *)
  wire [7:0] _002_;
  (* src = "serialParalelo_sintetizado.v:24" *)
  wire [7:0] _003_;
  (* src = "serialParalelo_sintetizado.v:24" *)
  wire [7:0] _004_;
  (* src = "serialParalelo_sintetizado.v:24" *)
  wire _005_;
  (* src = "serialParalelo_sintetizado.v:24" *)
  wire _006_;
  (* src = "serialParalelo_sintetizado.v:24" *)
  wire _007_;
  (* src = "serialParalelo_sintetizado.v:24" *)
  wire _008_;
  (* src = "serialParalelo_sintetizado.v:24" *)
  wire _009_;
  (* src = "serialParalelo_sintetizado.v:24" *)
  wire _010_;
  (* src = "serialParalelo_sintetizado.v:24" *)
  wire _011_;
  (* src = "serialParalelo_sintetizado.v:24" *)
  wire _012_;
  (* src = "serialParalelo_sintetizado.v:24" *)
  wire _013_;
  (* src = "serialParalelo_sintetizado.v:24" *)
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  (* src = "serialParalelo_sintetizado.v:19" *)
  wire [2:0] BC_counter;
  (* src = "serialParalelo_sintetizado.v:9" *)
  wire active;
  (* src = "serialParalelo_sintetizado.v:3" *)
  input clk_32f;
  (* src = "serialParalelo_sintetizado.v:3" *)
  input clk_4f;
  (* src = "serialParalelo_sintetizado.v:22" *)
  wire [7:0] contador_CLK;
  (* src = "serialParalelo_sintetizado.v:20" *)
  wire [7:0] data2Send;
  (* src = "serialParalelo_sintetizado.v:4" *)
  input data_in;
  (* src = "serialParalelo_sintetizado.v:6" *)
  output [7:0] data_out_sintetizado;
  (* src = "serialParalelo_sintetizado.v:5" *)
  input reset;
  (* onehot = 32'd1 *)
  wire [7:0] selector;
  (* src = "serialParalelo_sintetizado.v:10" *)
  wire temp;
  (* src = "serialParalelo_sintetizado.v:11" *)
  wire temp1;
  (* src = "serialParalelo_sintetizado.v:12" *)
  wire temp2;
  (* src = "serialParalelo_sintetizado.v:13" *)
  wire temp3;
  (* src = "serialParalelo_sintetizado.v:14" *)
  wire temp4;
  (* src = "serialParalelo_sintetizado.v:15" *)
  wire temp5;
  (* src = "serialParalelo_sintetizado.v:16" *)
  wire temp6;
  (* src = "serialParalelo_sintetizado.v:17" *)
  wire temp7;
  (* src = "serialParalelo_sintetizado.v:21" *)
  wire valid_dts;
  (* src = "serialParalelo_sintetizado.v:7" *)
  output valid_out_sintetizado;
  NOT _167_ (
    .A(BC_counter[2]),
    .Y(_162_)
  );
  NOT _168_ (
    .A(contador_CLK[3]),
    .Y(_163_)
  );
  NOT _169_ (
    .A(contador_CLK[4]),
    .Y(_164_)
  );
  NOT _170_ (
    .A(contador_CLK[5]),
    .Y(_165_)
  );
  NOT _171_ (
    .A(contador_CLK[7]),
    .Y(_166_)
  );
  NOT _172_ (
    .A(data2Send[6]),
    .Y(_023_)
  );
  NOT _173_ (
    .A(reset),
    .Y(_024_)
  );
  NOT _174_ (
    .A(selector[0]),
    .Y(_025_)
  );
  NOT _175_ (
    .A(valid_dts),
    .Y(_026_)
  );
  NOT _176_ (
    .A(BC_counter[0]),
    .Y(_027_)
  );
  NOT _177_ (
    .A(BC_counter[1]),
    .Y(_028_)
  );
  NOT _178_ (
    .A(data_in),
    .Y(_029_)
  );
  NOT _179_ (
    .A(selector[7]),
    .Y(_030_)
  );
  NOT _180_ (
    .A(selector[3]),
    .Y(_031_)
  );
  NOT _181_ (
    .A(selector[5]),
    .Y(_032_)
  );
  NOT _182_ (
    .A(selector[1]),
    .Y(_033_)
  );
  NOT _183_ (
    .A(selector[6]),
    .Y(_034_)
  );
  NOT _184_ (
    .A(selector[2]),
    .Y(_035_)
  );
  NOT _185_ (
    .A(contador_CLK[1]),
    .Y(_036_)
  );
  NOT _186_ (
    .A(contador_CLK[0]),
    .Y(_037_)
  );
  NOT _187_ (
    .A(contador_CLK[2]),
    .Y(_038_)
  );
  NOR _188_ (
    .A(selector[4]),
    .B(reset),
    .Y(_039_)
  );
  NOT _189_ (
    .A(_039_),
    .Y(_022_)
  );
  NOR _190_ (
    .A(reset),
    .B(contador_CLK[0]),
    .Y(_002_[0])
  );
  NOR _191_ (
    .A(_036_),
    .B(_037_),
    .Y(_040_)
  );
  NAND _192_ (
    .A(contador_CLK[1]),
    .B(contador_CLK[0]),
    .Y(_041_)
  );
  NOR _193_ (
    .A(contador_CLK[1]),
    .B(contador_CLK[0]),
    .Y(_042_)
  );
  NOR _194_ (
    .A(reset),
    .B(_042_),
    .Y(_043_)
  );
  NAND _195_ (
    .A(_041_),
    .B(_043_),
    .Y(_044_)
  );
  NOT _196_ (
    .A(_044_),
    .Y(_002_[1])
  );
  NOR _197_ (
    .A(_038_),
    .B(_041_),
    .Y(_045_)
  );
  NAND _198_ (
    .A(contador_CLK[2]),
    .B(_040_),
    .Y(_046_)
  );
  NOR _199_ (
    .A(contador_CLK[2]),
    .B(_040_),
    .Y(_047_)
  );
  NOR _200_ (
    .A(reset),
    .B(_047_),
    .Y(_048_)
  );
  NAND _201_ (
    .A(_046_),
    .B(_048_),
    .Y(_049_)
  );
  NOT _202_ (
    .A(_049_),
    .Y(_002_[2])
  );
  NAND _203_ (
    .A(_163_),
    .B(_045_),
    .Y(_050_)
  );
  NOR _204_ (
    .A(contador_CLK[4]),
    .B(contador_CLK[5]),
    .Y(_051_)
  );
  NOR _205_ (
    .A(contador_CLK[6]),
    .B(contador_CLK[7]),
    .Y(_052_)
  );
  NAND _206_ (
    .A(_051_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _207_ (
    .A(_050_),
    .B(_053_),
    .Y(_054_)
  );
  NOT _208_ (
    .A(_054_),
    .Y(_055_)
  );
  NAND _209_ (
    .A(contador_CLK[3]),
    .B(_046_),
    .Y(_056_)
  );
  NAND _210_ (
    .A(_050_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _211_ (
    .A(_024_),
    .B(_057_),
    .Y(_058_)
  );
  NOR _212_ (
    .A(_054_),
    .B(_058_),
    .Y(_002_[3])
  );
  NAND _213_ (
    .A(contador_CLK[3]),
    .B(_045_),
    .Y(_059_)
  );
  NOR _214_ (
    .A(_164_),
    .B(_059_),
    .Y(_060_)
  );
  NOT _215_ (
    .A(_060_),
    .Y(_061_)
  );
  NAND _216_ (
    .A(_164_),
    .B(_059_),
    .Y(_062_)
  );
  NAND _217_ (
    .A(_024_),
    .B(_062_),
    .Y(_063_)
  );
  NOR _218_ (
    .A(_060_),
    .B(_063_),
    .Y(_002_[4])
  );
  NOR _219_ (
    .A(_165_),
    .B(_061_),
    .Y(_064_)
  );
  NOR _220_ (
    .A(contador_CLK[5]),
    .B(_060_),
    .Y(_065_)
  );
  NOR _221_ (
    .A(reset),
    .B(_065_),
    .Y(_066_)
  );
  NOT _222_ (
    .A(_066_),
    .Y(_067_)
  );
  NOR _223_ (
    .A(_064_),
    .B(_067_),
    .Y(_002_[5])
  );
  NAND _224_ (
    .A(contador_CLK[6]),
    .B(_064_),
    .Y(_068_)
  );
  NOR _225_ (
    .A(contador_CLK[6]),
    .B(_064_),
    .Y(_069_)
  );
  NOR _226_ (
    .A(reset),
    .B(_069_),
    .Y(_070_)
  );
  NAND _227_ (
    .A(_068_),
    .B(_070_),
    .Y(_071_)
  );
  NOT _228_ (
    .A(_071_),
    .Y(_002_[6])
  );
  NOR _229_ (
    .A(_166_),
    .B(_068_),
    .Y(_072_)
  );
  NAND _230_ (
    .A(_166_),
    .B(_068_),
    .Y(_073_)
  );
  NAND _231_ (
    .A(_024_),
    .B(_073_),
    .Y(_074_)
  );
  NOR _232_ (
    .A(_072_),
    .B(_074_),
    .Y(_002_[7])
  );
  NOR _233_ (
    .A(reset),
    .B(_025_),
    .Y(_013_)
  );
  NOR _234_ (
    .A(reset),
    .B(_026_),
    .Y(_075_)
  );
  NAND _235_ (
    .A(_024_),
    .B(valid_dts),
    .Y(_076_)
  );
  NAND _236_ (
    .A(temp),
    .B(_075_),
    .Y(_077_)
  );
  NAND _237_ (
    .A(data2Send[0]),
    .B(_076_),
    .Y(_078_)
  );
  NAND _238_ (
    .A(_077_),
    .B(_078_),
    .Y(_003_[0])
  );
  NAND _239_ (
    .A(temp1),
    .B(_075_),
    .Y(_079_)
  );
  NAND _240_ (
    .A(data2Send[1]),
    .B(_076_),
    .Y(_080_)
  );
  NAND _241_ (
    .A(_079_),
    .B(_080_),
    .Y(_003_[1])
  );
  NAND _242_ (
    .A(temp2),
    .B(_075_),
    .Y(_081_)
  );
  NAND _243_ (
    .A(data2Send[2]),
    .B(_076_),
    .Y(_082_)
  );
  NAND _244_ (
    .A(_081_),
    .B(_082_),
    .Y(_003_[2])
  );
  NAND _245_ (
    .A(temp3),
    .B(_075_),
    .Y(_083_)
  );
  NAND _246_ (
    .A(data2Send[3]),
    .B(_076_),
    .Y(_084_)
  );
  NAND _247_ (
    .A(_083_),
    .B(_084_),
    .Y(_003_[3])
  );
  NAND _248_ (
    .A(temp4),
    .B(_075_),
    .Y(_085_)
  );
  NAND _249_ (
    .A(data2Send[4]),
    .B(_076_),
    .Y(_086_)
  );
  NAND _250_ (
    .A(_085_),
    .B(_086_),
    .Y(_003_[4])
  );
  NAND _251_ (
    .A(temp5),
    .B(_075_),
    .Y(_087_)
  );
  NAND _252_ (
    .A(data2Send[5]),
    .B(_076_),
    .Y(_088_)
  );
  NAND _253_ (
    .A(_087_),
    .B(_088_),
    .Y(_003_[5])
  );
  NAND _254_ (
    .A(temp6),
    .B(_075_),
    .Y(_089_)
  );
  NAND _255_ (
    .A(data2Send[6]),
    .B(_076_),
    .Y(_090_)
  );
  NAND _256_ (
    .A(_089_),
    .B(_090_),
    .Y(_003_[6])
  );
  NAND _257_ (
    .A(temp7),
    .B(_075_),
    .Y(_091_)
  );
  NAND _258_ (
    .A(data2Send[7]),
    .B(_076_),
    .Y(_092_)
  );
  NAND _259_ (
    .A(_091_),
    .B(_092_),
    .Y(_003_[7])
  );
  NAND _260_ (
    .A(data2Send[3]),
    .B(data2Send[4]),
    .Y(_093_)
  );
  NAND _261_ (
    .A(data2Send[5]),
    .B(data2Send[7]),
    .Y(_094_)
  );
  NOR _262_ (
    .A(_093_),
    .B(_094_),
    .Y(_095_)
  );
  NOR _263_ (
    .A(data2Send[0]),
    .B(data2Send[1]),
    .Y(_096_)
  );
  NOT _264_ (
    .A(_096_),
    .Y(_097_)
  );
  NAND _265_ (
    .A(_023_),
    .B(data2Send[2]),
    .Y(_098_)
  );
  NOR _266_ (
    .A(_097_),
    .B(_098_),
    .Y(_099_)
  );
  NAND _267_ (
    .A(_095_),
    .B(_099_),
    .Y(_100_)
  );
  NOR _268_ (
    .A(active),
    .B(_100_),
    .Y(_101_)
  );
  NAND _269_ (
    .A(_054_),
    .B(_101_),
    .Y(_102_)
  );
  NAND _270_ (
    .A(_027_),
    .B(_102_),
    .Y(_103_)
  );
  NAND _271_ (
    .A(_024_),
    .B(_103_),
    .Y(_104_)
  );
  NOR _272_ (
    .A(_027_),
    .B(_102_),
    .Y(_105_)
  );
  NOR _273_ (
    .A(_104_),
    .B(_105_),
    .Y(_000_[0])
  );
  NOR _274_ (
    .A(BC_counter[1]),
    .B(_105_),
    .Y(_106_)
  );
  NOR _275_ (
    .A(reset),
    .B(_106_),
    .Y(_107_)
  );
  NAND _276_ (
    .A(BC_counter[1]),
    .B(_105_),
    .Y(_108_)
  );
  NAND _277_ (
    .A(_107_),
    .B(_108_),
    .Y(_109_)
  );
  NOT _278_ (
    .A(_109_),
    .Y(_000_[1])
  );
  NOR _279_ (
    .A(_162_),
    .B(_108_),
    .Y(_110_)
  );
  NAND _280_ (
    .A(_162_),
    .B(_108_),
    .Y(_111_)
  );
  NAND _281_ (
    .A(_024_),
    .B(_111_),
    .Y(_112_)
  );
  NOR _282_ (
    .A(_110_),
    .B(_112_),
    .Y(_000_[2])
  );
  NAND _283_ (
    .A(_029_),
    .B(selector[7]),
    .Y(_113_)
  );
  NAND _284_ (
    .A(_024_),
    .B(_113_),
    .Y(_114_)
  );
  NOR _285_ (
    .A(temp7),
    .B(selector[7]),
    .Y(_115_)
  );
  NOR _286_ (
    .A(_114_),
    .B(_115_),
    .Y(_011_)
  );
  NAND _287_ (
    .A(_029_),
    .B(selector[3]),
    .Y(_116_)
  );
  NAND _288_ (
    .A(_024_),
    .B(_116_),
    .Y(_117_)
  );
  NOR _289_ (
    .A(temp6),
    .B(selector[3]),
    .Y(_118_)
  );
  NOR _290_ (
    .A(_117_),
    .B(_118_),
    .Y(_010_)
  );
  NAND _291_ (
    .A(_029_),
    .B(selector[5]),
    .Y(_119_)
  );
  NAND _292_ (
    .A(_024_),
    .B(_119_),
    .Y(_120_)
  );
  NOR _293_ (
    .A(temp5),
    .B(selector[5]),
    .Y(_121_)
  );
  NOR _294_ (
    .A(_120_),
    .B(_121_),
    .Y(_009_)
  );
  NAND _295_ (
    .A(_029_),
    .B(selector[1]),
    .Y(_122_)
  );
  NAND _296_ (
    .A(_024_),
    .B(_122_),
    .Y(_123_)
  );
  NOR _297_ (
    .A(temp4),
    .B(selector[1]),
    .Y(_124_)
  );
  NOR _298_ (
    .A(_123_),
    .B(_124_),
    .Y(_008_)
  );
  NAND _299_ (
    .A(_029_),
    .B(selector[6]),
    .Y(_125_)
  );
  NAND _300_ (
    .A(_024_),
    .B(_125_),
    .Y(_126_)
  );
  NOR _301_ (
    .A(temp3),
    .B(selector[6]),
    .Y(_127_)
  );
  NOR _302_ (
    .A(_126_),
    .B(_127_),
    .Y(_007_)
  );
  NAND _303_ (
    .A(_029_),
    .B(selector[2]),
    .Y(_128_)
  );
  NAND _304_ (
    .A(_024_),
    .B(_128_),
    .Y(_129_)
  );
  NOR _305_ (
    .A(temp2),
    .B(selector[2]),
    .Y(_130_)
  );
  NOR _306_ (
    .A(_129_),
    .B(_130_),
    .Y(_006_)
  );
  NOR _307_ (
    .A(reset),
    .B(_055_),
    .Y(_131_)
  );
  NAND _308_ (
    .A(_024_),
    .B(_054_),
    .Y(_132_)
  );
  NAND _309_ (
    .A(active),
    .B(_100_),
    .Y(_133_)
  );
  NOT _310_ (
    .A(_133_),
    .Y(_134_)
  );
  NOR _311_ (
    .A(_132_),
    .B(_134_),
    .Y(_135_)
  );
  NOR _312_ (
    .A(valid_out_sintetizado),
    .B(_131_),
    .Y(_136_)
  );
  NOR _313_ (
    .A(_135_),
    .B(_136_),
    .Y(_014_)
  );
  NAND _314_ (
    .A(data2Send[0]),
    .B(_131_),
    .Y(_137_)
  );
  NAND _315_ (
    .A(data_out_sintetizado[0]),
    .B(_132_),
    .Y(_138_)
  );
  NAND _316_ (
    .A(_137_),
    .B(_138_),
    .Y(_004_[0])
  );
  NAND _317_ (
    .A(data2Send[1]),
    .B(_131_),
    .Y(_139_)
  );
  NAND _318_ (
    .A(data_out_sintetizado[1]),
    .B(_132_),
    .Y(_140_)
  );
  NAND _319_ (
    .A(_139_),
    .B(_140_),
    .Y(_004_[1])
  );
  NAND _320_ (
    .A(data2Send[2]),
    .B(_131_),
    .Y(_141_)
  );
  NAND _321_ (
    .A(data_out_sintetizado[2]),
    .B(_132_),
    .Y(_142_)
  );
  NAND _322_ (
    .A(_141_),
    .B(_142_),
    .Y(_004_[2])
  );
  NAND _323_ (
    .A(data2Send[3]),
    .B(_131_),
    .Y(_143_)
  );
  NAND _324_ (
    .A(data_out_sintetizado[3]),
    .B(_132_),
    .Y(_144_)
  );
  NAND _325_ (
    .A(_143_),
    .B(_144_),
    .Y(_004_[3])
  );
  NAND _326_ (
    .A(data2Send[4]),
    .B(_131_),
    .Y(_145_)
  );
  NAND _327_ (
    .A(data_out_sintetizado[4]),
    .B(_132_),
    .Y(_146_)
  );
  NAND _328_ (
    .A(_145_),
    .B(_146_),
    .Y(_004_[4])
  );
  NAND _329_ (
    .A(data2Send[5]),
    .B(_131_),
    .Y(_147_)
  );
  NAND _330_ (
    .A(data_out_sintetizado[5]),
    .B(_132_),
    .Y(_148_)
  );
  NAND _331_ (
    .A(_147_),
    .B(_148_),
    .Y(_004_[5])
  );
  NAND _332_ (
    .A(data2Send[6]),
    .B(_131_),
    .Y(_149_)
  );
  NAND _333_ (
    .A(data_out_sintetizado[6]),
    .B(_132_),
    .Y(_150_)
  );
  NAND _334_ (
    .A(_149_),
    .B(_150_),
    .Y(_004_[6])
  );
  NAND _335_ (
    .A(data2Send[7]),
    .B(_131_),
    .Y(_151_)
  );
  NAND _336_ (
    .A(data_out_sintetizado[7]),
    .B(_132_),
    .Y(_152_)
  );
  NAND _337_ (
    .A(_151_),
    .B(_152_),
    .Y(_004_[7])
  );
  NOR _338_ (
    .A(selector[4]),
    .B(temp1),
    .Y(_153_)
  );
  NAND _339_ (
    .A(selector[4]),
    .B(_029_),
    .Y(_154_)
  );
  NAND _340_ (
    .A(_024_),
    .B(_154_),
    .Y(_155_)
  );
  NOR _341_ (
    .A(_153_),
    .B(_155_),
    .Y(_005_)
  );
  NAND _342_ (
    .A(selector[0]),
    .B(_029_),
    .Y(_156_)
  );
  NAND _343_ (
    .A(_024_),
    .B(_156_),
    .Y(_157_)
  );
  NOR _344_ (
    .A(selector[0]),
    .B(temp),
    .Y(_158_)
  );
  NOR _345_ (
    .A(_157_),
    .B(_158_),
    .Y(_012_)
  );
  NAND _346_ (
    .A(_162_),
    .B(BC_counter[0]),
    .Y(_159_)
  );
  NOR _347_ (
    .A(_028_),
    .B(_159_),
    .Y(_160_)
  );
  NOR _348_ (
    .A(active),
    .B(_160_),
    .Y(_161_)
  );
  NOR _349_ (
    .A(reset),
    .B(_161_),
    .Y(_001_)
  );
  NOR _350_ (
    .A(reset),
    .B(_035_),
    .Y(_018_)
  );
  NOR _351_ (
    .A(reset),
    .B(_033_),
    .Y(_020_)
  );
  NOR _352_ (
    .A(reset),
    .B(_030_),
    .Y(_017_)
  );
  NOR _353_ (
    .A(reset),
    .B(_031_),
    .Y(_019_)
  );
  NOR _354_ (
    .A(reset),
    .B(_032_),
    .Y(_015_)
  );
  NOR _355_ (
    .A(reset),
    .B(_034_),
    .Y(_016_)
  );
  NOR _356_ (
    .A(reset),
    .B(_025_),
    .Y(_021_)
  );
  DFF _357_ (
    .C(clk_32f),
    .D(_022_),
    .Q(selector[0])
  );
  DFF _358_ (
    .C(clk_32f),
    .D(_015_),
    .Q(selector[1])
  );
  DFF _359_ (
    .C(clk_32f),
    .D(_016_),
    .Q(selector[2])
  );
  DFF _360_ (
    .C(clk_32f),
    .D(_017_),
    .Q(selector[3])
  );
  DFF _361_ (
    .C(clk_32f),
    .D(_018_),
    .Q(selector[4])
  );
  DFF _362_ (
    .C(clk_32f),
    .D(_019_),
    .Q(selector[5])
  );
  DFF _363_ (
    .C(clk_32f),
    .D(_020_),
    .Q(selector[6])
  );
  DFF _364_ (
    .C(clk_32f),
    .D(_021_),
    .Q(selector[7])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _365_ (
    .C(clk_32f),
    .D(_001_),
    .Q(active)
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _366_ (
    .C(clk_32f),
    .D(_012_),
    .Q(temp)
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _367_ (
    .C(clk_32f),
    .D(_005_),
    .Q(temp1)
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _368_ (
    .C(clk_32f),
    .D(_004_[0]),
    .Q(data_out_sintetizado[0])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _369_ (
    .C(clk_32f),
    .D(_004_[1]),
    .Q(data_out_sintetizado[1])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _370_ (
    .C(clk_32f),
    .D(_004_[2]),
    .Q(data_out_sintetizado[2])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _371_ (
    .C(clk_32f),
    .D(_004_[3]),
    .Q(data_out_sintetizado[3])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _372_ (
    .C(clk_32f),
    .D(_004_[4]),
    .Q(data_out_sintetizado[4])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _373_ (
    .C(clk_32f),
    .D(_004_[5]),
    .Q(data_out_sintetizado[5])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _374_ (
    .C(clk_32f),
    .D(_004_[6]),
    .Q(data_out_sintetizado[6])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _375_ (
    .C(clk_32f),
    .D(_004_[7]),
    .Q(data_out_sintetizado[7])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _376_ (
    .C(clk_32f),
    .D(_014_),
    .Q(valid_out_sintetizado)
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _377_ (
    .C(clk_32f),
    .D(_006_),
    .Q(temp2)
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _378_ (
    .C(clk_32f),
    .D(_007_),
    .Q(temp3)
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _379_ (
    .C(clk_32f),
    .D(_008_),
    .Q(temp4)
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _380_ (
    .C(clk_32f),
    .D(_009_),
    .Q(temp5)
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _381_ (
    .C(clk_32f),
    .D(_010_),
    .Q(temp6)
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _382_ (
    .C(clk_32f),
    .D(_011_),
    .Q(temp7)
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _383_ (
    .C(clk_32f),
    .D(_000_[0]),
    .Q(BC_counter[0])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _384_ (
    .C(clk_32f),
    .D(_000_[1]),
    .Q(BC_counter[1])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _385_ (
    .C(clk_32f),
    .D(_000_[2]),
    .Q(BC_counter[2])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _386_ (
    .C(clk_32f),
    .D(_003_[0]),
    .Q(data2Send[0])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _387_ (
    .C(clk_32f),
    .D(_003_[1]),
    .Q(data2Send[1])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _388_ (
    .C(clk_32f),
    .D(_003_[2]),
    .Q(data2Send[2])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _389_ (
    .C(clk_32f),
    .D(_003_[3]),
    .Q(data2Send[3])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _390_ (
    .C(clk_32f),
    .D(_003_[4]),
    .Q(data2Send[4])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _391_ (
    .C(clk_32f),
    .D(_003_[5]),
    .Q(data2Send[5])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _392_ (
    .C(clk_32f),
    .D(_003_[6]),
    .Q(data2Send[6])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _393_ (
    .C(clk_32f),
    .D(_003_[7]),
    .Q(data2Send[7])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _394_ (
    .C(clk_32f),
    .D(_013_),
    .Q(valid_dts)
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _395_ (
    .C(clk_32f),
    .D(_002_[0]),
    .Q(contador_CLK[0])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _396_ (
    .C(clk_32f),
    .D(_002_[1]),
    .Q(contador_CLK[1])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _397_ (
    .C(clk_32f),
    .D(_002_[2]),
    .Q(contador_CLK[2])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _398_ (
    .C(clk_32f),
    .D(_002_[3]),
    .Q(contador_CLK[3])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _399_ (
    .C(clk_32f),
    .D(_002_[4]),
    .Q(contador_CLK[4])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _400_ (
    .C(clk_32f),
    .D(_002_[5]),
    .Q(contador_CLK[5])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _401_ (
    .C(clk_32f),
    .D(_002_[6]),
    .Q(contador_CLK[6])
  );
  (* src = "serialParalelo_sintetizado.v:24" *)
  DFF _402_ (
    .C(clk_32f),
    .D(_002_[7]),
    .Q(contador_CLK[7])
  );
endmodule
