/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "paraleloSerial_sintetizado.v:1" *)
module paraleloSerial_sintetizado(data_in, clk_4f, clk_32f, valid_in, reset, data_out_sintetizado);
  (* src = "paraleloSerial_sintetizado.v:10" *)
  wire [7:0] _000_;
  (* src = "paraleloSerial_sintetizado.v:10" *)
  wire _001_;
  (* src = "paraleloSerial_sintetizado.v:10" *)
  wire [3:0] _002_;
  (* src = "paraleloSerial_sintetizado.v:10" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  (* src = "paraleloSerial_sintetizado.v:3" *)
  input clk_32f;
  (* src = "paraleloSerial_sintetizado.v:3" *)
  input clk_4f;
  (* src = "paraleloSerial_sintetizado.v:6" *)
  wire [7:0] data2send;
  (* src = "paraleloSerial_sintetizado.v:2" *)
  input [7:0] data_in;
  (* src = "paraleloSerial_sintetizado.v:4" *)
  output data_out_sintetizado;
  (* src = "paraleloSerial_sintetizado.v:3" *)
  input reset;
  (* src = "paraleloSerial_sintetizado.v:7" *)
  wire [3:0] selector;
  (* src = "paraleloSerial_sintetizado.v:8" *)
  wire validTemp;
  (* src = "paraleloSerial_sintetizado.v:3" *)
  input valid_in;
  NOT _086_ (
    .A(selector[2]),
    .Y(_031_)
  );
  NOT _087_ (
    .A(validTemp),
    .Y(_032_)
  );
  NOT _088_ (
    .A(reset),
    .Y(_033_)
  );
  NOT _089_ (
    .A(selector[0]),
    .Y(_034_)
  );
  NOT _090_ (
    .A(selector[1]),
    .Y(_035_)
  );
  NOT _091_ (
    .A(data_in[0]),
    .Y(_036_)
  );
  NOT _092_ (
    .A(data_in[1]),
    .Y(_037_)
  );
  NOT _093_ (
    .A(data_in[6]),
    .Y(_038_)
  );
  NOT _094_ (
    .A(data2send[0]),
    .Y(_039_)
  );
  NOT _095_ (
    .A(data2send[1]),
    .Y(_040_)
  );
  NOT _096_ (
    .A(data2send[2]),
    .Y(_041_)
  );
  NOT _097_ (
    .A(data2send[3]),
    .Y(_042_)
  );
  NOT _098_ (
    .A(data2send[6]),
    .Y(_043_)
  );
  NAND _099_ (
    .A(data_out_sintetizado),
    .B(validTemp),
    .Y(_044_)
  );
  NOT _100_ (
    .A(_044_),
    .Y(_045_)
  );
  NOR _101_ (
    .A(selector[3]),
    .B(validTemp),
    .Y(_046_)
  );
  NOR _102_ (
    .A(_031_),
    .B(data2send[7]),
    .Y(_047_)
  );
  NAND _103_ (
    .A(_031_),
    .B(_042_),
    .Y(_048_)
  );
  NAND _104_ (
    .A(selector[0]),
    .B(_048_),
    .Y(_049_)
  );
  NOR _105_ (
    .A(_047_),
    .B(_049_),
    .Y(_050_)
  );
  NAND _106_ (
    .A(_031_),
    .B(_041_),
    .Y(_051_)
  );
  NAND _107_ (
    .A(selector[2]),
    .B(_043_),
    .Y(_052_)
  );
  NAND _108_ (
    .A(_051_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _109_ (
    .A(selector[0]),
    .B(_053_),
    .Y(_054_)
  );
  NOR _110_ (
    .A(_050_),
    .B(_054_),
    .Y(_055_)
  );
  NAND _111_ (
    .A(selector[1]),
    .B(_055_),
    .Y(_056_)
  );
  NOR _112_ (
    .A(selector[2]),
    .B(data2send[0]),
    .Y(_057_)
  );
  NOR _113_ (
    .A(_031_),
    .B(data2send[4]),
    .Y(_058_)
  );
  NOR _114_ (
    .A(_057_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _115_ (
    .A(_034_),
    .B(_059_),
    .Y(_060_)
  );
  NOR _116_ (
    .A(_031_),
    .B(data2send[5]),
    .Y(_061_)
  );
  NAND _117_ (
    .A(_031_),
    .B(_040_),
    .Y(_062_)
  );
  NOR _118_ (
    .A(_034_),
    .B(_061_),
    .Y(_063_)
  );
  NAND _119_ (
    .A(_062_),
    .B(_063_),
    .Y(_064_)
  );
  NAND _120_ (
    .A(_060_),
    .B(_064_),
    .Y(_065_)
  );
  NOR _121_ (
    .A(selector[1]),
    .B(_065_),
    .Y(_066_)
  );
  NAND _122_ (
    .A(_046_),
    .B(_056_),
    .Y(_067_)
  );
  NOR _123_ (
    .A(_066_),
    .B(_067_),
    .Y(_068_)
  );
  NOR _124_ (
    .A(_045_),
    .B(_068_),
    .Y(_069_)
  );
  NOR _125_ (
    .A(reset),
    .B(_069_),
    .Y(_001_)
  );
  NOR _126_ (
    .A(selector[2]),
    .B(selector[1]),
    .Y(_070_)
  );
  NAND _127_ (
    .A(_034_),
    .B(_070_),
    .Y(_071_)
  );
  NAND _128_ (
    .A(_033_),
    .B(_046_),
    .Y(_072_)
  );
  NOR _129_ (
    .A(_071_),
    .B(_072_),
    .Y(_003_)
  );
  NOR _130_ (
    .A(validTemp),
    .B(selector[0]),
    .Y(_073_)
  );
  NOT _131_ (
    .A(_073_),
    .Y(_074_)
  );
  NAND _132_ (
    .A(validTemp),
    .B(selector[0]),
    .Y(_075_)
  );
  NOT _133_ (
    .A(_075_),
    .Y(_076_)
  );
  NOR _134_ (
    .A(reset),
    .B(_076_),
    .Y(_077_)
  );
  NAND _135_ (
    .A(_074_),
    .B(_077_),
    .Y(_002_[0])
  );
  NAND _136_ (
    .A(_035_),
    .B(_073_),
    .Y(_078_)
  );
  NOR _137_ (
    .A(_035_),
    .B(_073_),
    .Y(_079_)
  );
  NOR _138_ (
    .A(reset),
    .B(_079_),
    .Y(_080_)
  );
  NAND _139_ (
    .A(_078_),
    .B(_080_),
    .Y(_002_[1])
  );
  NAND _140_ (
    .A(selector[2]),
    .B(_078_),
    .Y(_081_)
  );
  NOR _141_ (
    .A(selector[2]),
    .B(_078_),
    .Y(_082_)
  );
  NOR _142_ (
    .A(reset),
    .B(_082_),
    .Y(_083_)
  );
  NAND _143_ (
    .A(_081_),
    .B(_083_),
    .Y(_002_[2])
  );
  NAND _144_ (
    .A(selector[3]),
    .B(_083_),
    .Y(_084_)
  );
  NOT _145_ (
    .A(_084_),
    .Y(_002_[3])
  );
  NOR _146_ (
    .A(validTemp),
    .B(_039_),
    .Y(_085_)
  );
  NAND _147_ (
    .A(validTemp),
    .B(valid_in),
    .Y(_004_)
  );
  NOR _148_ (
    .A(_036_),
    .B(_004_),
    .Y(_005_)
  );
  NOR _149_ (
    .A(_085_),
    .B(_005_),
    .Y(_006_)
  );
  NOR _150_ (
    .A(reset),
    .B(_006_),
    .Y(_000_[0])
  );
  NOR _151_ (
    .A(validTemp),
    .B(_040_),
    .Y(_007_)
  );
  NOR _152_ (
    .A(_037_),
    .B(_004_),
    .Y(_008_)
  );
  NOR _153_ (
    .A(_007_),
    .B(_008_),
    .Y(_009_)
  );
  NOR _154_ (
    .A(reset),
    .B(_009_),
    .Y(_000_[1])
  );
  NOR _155_ (
    .A(data_in[2]),
    .B(_004_),
    .Y(_010_)
  );
  NAND _156_ (
    .A(_032_),
    .B(_041_),
    .Y(_011_)
  );
  NAND _157_ (
    .A(_033_),
    .B(_011_),
    .Y(_012_)
  );
  NOR _158_ (
    .A(_010_),
    .B(_012_),
    .Y(_000_[2])
  );
  NOR _159_ (
    .A(data_in[3]),
    .B(_004_),
    .Y(_013_)
  );
  NAND _160_ (
    .A(_032_),
    .B(_042_),
    .Y(_014_)
  );
  NAND _161_ (
    .A(_033_),
    .B(_014_),
    .Y(_015_)
  );
  NOR _162_ (
    .A(_013_),
    .B(_015_),
    .Y(_000_[3])
  );
  NOR _163_ (
    .A(data_in[4]),
    .B(_004_),
    .Y(_016_)
  );
  NOR _164_ (
    .A(validTemp),
    .B(data2send[4]),
    .Y(_017_)
  );
  NOR _165_ (
    .A(reset),
    .B(_016_),
    .Y(_018_)
  );
  NOT _166_ (
    .A(_018_),
    .Y(_019_)
  );
  NOR _167_ (
    .A(_017_),
    .B(_019_),
    .Y(_000_[4])
  );
  NOR _168_ (
    .A(data_in[5]),
    .B(_004_),
    .Y(_020_)
  );
  NOR _169_ (
    .A(validTemp),
    .B(data2send[5]),
    .Y(_021_)
  );
  NOR _170_ (
    .A(reset),
    .B(_020_),
    .Y(_022_)
  );
  NOT _171_ (
    .A(_022_),
    .Y(_023_)
  );
  NOR _172_ (
    .A(_021_),
    .B(_023_),
    .Y(_000_[5])
  );
  NOR _173_ (
    .A(validTemp),
    .B(_043_),
    .Y(_024_)
  );
  NOR _174_ (
    .A(_038_),
    .B(_004_),
    .Y(_025_)
  );
  NOR _175_ (
    .A(_024_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _176_ (
    .A(reset),
    .B(_026_),
    .Y(_000_[6])
  );
  NOR _177_ (
    .A(data_in[7]),
    .B(_004_),
    .Y(_027_)
  );
  NOR _178_ (
    .A(validTemp),
    .B(data2send[7]),
    .Y(_028_)
  );
  NOR _179_ (
    .A(reset),
    .B(_027_),
    .Y(_029_)
  );
  NOT _180_ (
    .A(_029_),
    .Y(_030_)
  );
  NOR _181_ (
    .A(_028_),
    .B(_030_),
    .Y(_000_[7])
  );
  (* src = "paraleloSerial_sintetizado.v:10" *)
  DFF _182_ (
    .C(clk_32f),
    .D(_000_[0]),
    .Q(data2send[0])
  );
  (* src = "paraleloSerial_sintetizado.v:10" *)
  DFF _183_ (
    .C(clk_32f),
    .D(_000_[1]),
    .Q(data2send[1])
  );
  (* src = "paraleloSerial_sintetizado.v:10" *)
  DFF _184_ (
    .C(clk_32f),
    .D(_000_[2]),
    .Q(data2send[2])
  );
  (* src = "paraleloSerial_sintetizado.v:10" *)
  DFF _185_ (
    .C(clk_32f),
    .D(_000_[3]),
    .Q(data2send[3])
  );
  (* src = "paraleloSerial_sintetizado.v:10" *)
  DFF _186_ (
    .C(clk_32f),
    .D(_000_[4]),
    .Q(data2send[4])
  );
  (* src = "paraleloSerial_sintetizado.v:10" *)
  DFF _187_ (
    .C(clk_32f),
    .D(_000_[5]),
    .Q(data2send[5])
  );
  (* src = "paraleloSerial_sintetizado.v:10" *)
  DFF _188_ (
    .C(clk_32f),
    .D(_000_[6]),
    .Q(data2send[6])
  );
  (* src = "paraleloSerial_sintetizado.v:10" *)
  DFF _189_ (
    .C(clk_32f),
    .D(_000_[7]),
    .Q(data2send[7])
  );
  (* src = "paraleloSerial_sintetizado.v:10" *)
  DFF _190_ (
    .C(clk_32f),
    .D(_002_[0]),
    .Q(selector[0])
  );
  (* src = "paraleloSerial_sintetizado.v:10" *)
  DFF _191_ (
    .C(clk_32f),
    .D(_002_[1]),
    .Q(selector[1])
  );
  (* src = "paraleloSerial_sintetizado.v:10" *)
  DFF _192_ (
    .C(clk_32f),
    .D(_002_[2]),
    .Q(selector[2])
  );
  (* src = "paraleloSerial_sintetizado.v:10" *)
  DFF _193_ (
    .C(clk_32f),
    .D(_002_[3]),
    .Q(selector[3])
  );
  (* src = "paraleloSerial_sintetizado.v:10" *)
  DFF _194_ (
    .C(clk_32f),
    .D(_003_),
    .Q(validTemp)
  );
  (* src = "paraleloSerial_sintetizado.v:10" *)
  DFF _195_ (
    .C(clk_32f),
    .D(_001_),
    .Q(data_out_sintetizado)
  );
endmodule
