/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "paso32bto8b_sintetizado.v:1" *)
module paso32bto8b_sintetizado(clk_f, clk_4f, reset, data_in, valid_0, valid_out_sintetizado, data_out_sintetizado);
  (* src = "paso32bto8b_sintetizado.v:14" *)
  wire [7:0] _000_;
  (* src = "paso32bto8b_sintetizado.v:14" *)
  wire [1:0] _001_;
  (* src = "paso32bto8b_sintetizado.v:14" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  (* src = "paso32bto8b_sintetizado.v:2" *)
  input clk_4f;
  (* src = "paso32bto8b_sintetizado.v:2" *)
  input clk_f;
  (* src = "paso32bto8b_sintetizado.v:4" *)
  input [31:0] data_in;
  (* src = "paso32bto8b_sintetizado.v:7" *)
  output [7:0] data_out_sintetizado;
  (* src = "paso32bto8b_sintetizado.v:11" *)
  wire [1:0] indice;
  (* src = "paso32bto8b_sintetizado.v:2" *)
  input reset;
  (* src = "paso32bto8b_sintetizado.v:10" *)
  wire validTemp;
  (* src = "paso32bto8b_sintetizado.v:5" *)
  input valid_0;
  (* src = "paso32bto8b_sintetizado.v:6" *)
  output valid_out_sintetizado;
  NOT _121_ (
    .A(indice[0]),
    .Y(_080_)
  );
  NOT _122_ (
    .A(indice[1]),
    .Y(_081_)
  );
  NOT _123_ (
    .A(reset),
    .Y(_082_)
  );
  NOT _124_ (
    .A(data_in[8]),
    .Y(_083_)
  );
  NOT _125_ (
    .A(data_in[9]),
    .Y(_084_)
  );
  NOT _126_ (
    .A(data_in[10]),
    .Y(_085_)
  );
  NOT _127_ (
    .A(data_in[11]),
    .Y(_086_)
  );
  NOT _128_ (
    .A(data_in[12]),
    .Y(_087_)
  );
  NOT _129_ (
    .A(data_in[13]),
    .Y(_088_)
  );
  NOT _130_ (
    .A(data_in[14]),
    .Y(_089_)
  );
  NOT _131_ (
    .A(data_in[15]),
    .Y(_090_)
  );
  NOT _132_ (
    .A(data_in[0]),
    .Y(_091_)
  );
  NOT _133_ (
    .A(data_in[1]),
    .Y(_092_)
  );
  NOT _134_ (
    .A(data_in[2]),
    .Y(_093_)
  );
  NOT _135_ (
    .A(data_in[3]),
    .Y(_094_)
  );
  NOT _136_ (
    .A(data_in[4]),
    .Y(_095_)
  );
  NOT _137_ (
    .A(data_in[5]),
    .Y(_096_)
  );
  NOT _138_ (
    .A(data_in[6]),
    .Y(_097_)
  );
  NOT _139_ (
    .A(data_in[7]),
    .Y(_098_)
  );
  NOT _140_ (
    .A(data_in[16]),
    .Y(_099_)
  );
  NOT _141_ (
    .A(data_in[17]),
    .Y(_100_)
  );
  NOT _142_ (
    .A(data_in[18]),
    .Y(_101_)
  );
  NOT _143_ (
    .A(data_in[19]),
    .Y(_102_)
  );
  NOT _144_ (
    .A(data_in[20]),
    .Y(_103_)
  );
  NOT _145_ (
    .A(data_in[21]),
    .Y(_104_)
  );
  NOT _146_ (
    .A(data_in[22]),
    .Y(_105_)
  );
  NOT _147_ (
    .A(data_in[23]),
    .Y(_106_)
  );
  NOT _148_ (
    .A(data_in[24]),
    .Y(_107_)
  );
  NOT _149_ (
    .A(data_in[25]),
    .Y(_108_)
  );
  NOT _150_ (
    .A(data_in[26]),
    .Y(_109_)
  );
  NOT _151_ (
    .A(data_in[27]),
    .Y(_110_)
  );
  NOT _152_ (
    .A(data_in[28]),
    .Y(_111_)
  );
  NOT _153_ (
    .A(data_in[29]),
    .Y(_112_)
  );
  NOT _154_ (
    .A(data_in[30]),
    .Y(_113_)
  );
  NOT _155_ (
    .A(data_in[31]),
    .Y(_114_)
  );
  NAND _156_ (
    .A(indice[0]),
    .B(valid_0),
    .Y(_115_)
  );
  NOR _157_ (
    .A(indice[0]),
    .B(valid_0),
    .Y(_116_)
  );
  NAND _158_ (
    .A(valid_0),
    .B(_082_),
    .Y(_117_)
  );
  NOT _159_ (
    .A(_117_),
    .Y(_002_)
  );
  NAND _160_ (
    .A(_082_),
    .B(_115_),
    .Y(_118_)
  );
  NOR _161_ (
    .A(_116_),
    .B(_118_),
    .Y(_001_[0])
  );
  NOR _162_ (
    .A(_081_),
    .B(_115_),
    .Y(_119_)
  );
  NAND _163_ (
    .A(_081_),
    .B(_115_),
    .Y(_120_)
  );
  NAND _164_ (
    .A(_082_),
    .B(_120_),
    .Y(_003_)
  );
  NOR _165_ (
    .A(_119_),
    .B(_003_),
    .Y(_001_[1])
  );
  NAND _166_ (
    .A(indice[0]),
    .B(indice[1]),
    .Y(_004_)
  );
  NOR _167_ (
    .A(_091_),
    .B(_004_),
    .Y(_005_)
  );
  NAND _168_ (
    .A(indice[0]),
    .B(_081_),
    .Y(_006_)
  );
  NOR _169_ (
    .A(_099_),
    .B(_006_),
    .Y(_007_)
  );
  NOR _170_ (
    .A(_005_),
    .B(_007_),
    .Y(_008_)
  );
  NAND _171_ (
    .A(_080_),
    .B(_081_),
    .Y(_009_)
  );
  NOR _172_ (
    .A(_107_),
    .B(_009_),
    .Y(_010_)
  );
  NAND _173_ (
    .A(_080_),
    .B(indice[1]),
    .Y(_011_)
  );
  NOR _174_ (
    .A(_083_),
    .B(_011_),
    .Y(_012_)
  );
  NOR _175_ (
    .A(_010_),
    .B(_012_),
    .Y(_013_)
  );
  NAND _176_ (
    .A(_008_),
    .B(_013_),
    .Y(_014_)
  );
  NAND _177_ (
    .A(_002_),
    .B(_014_),
    .Y(_015_)
  );
  NAND _178_ (
    .A(data_out_sintetizado[0]),
    .B(_117_),
    .Y(_016_)
  );
  NAND _179_ (
    .A(_015_),
    .B(_016_),
    .Y(_000_[0])
  );
  NOR _180_ (
    .A(_084_),
    .B(_011_),
    .Y(_017_)
  );
  NOR _181_ (
    .A(_100_),
    .B(_006_),
    .Y(_018_)
  );
  NOR _182_ (
    .A(_017_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _183_ (
    .A(_108_),
    .B(_009_),
    .Y(_020_)
  );
  NOR _184_ (
    .A(_092_),
    .B(_004_),
    .Y(_021_)
  );
  NOR _185_ (
    .A(_020_),
    .B(_021_),
    .Y(_022_)
  );
  NAND _186_ (
    .A(_019_),
    .B(_022_),
    .Y(_023_)
  );
  NAND _187_ (
    .A(_002_),
    .B(_023_),
    .Y(_024_)
  );
  NAND _188_ (
    .A(data_out_sintetizado[1]),
    .B(_117_),
    .Y(_025_)
  );
  NAND _189_ (
    .A(_024_),
    .B(_025_),
    .Y(_000_[1])
  );
  NOR _190_ (
    .A(_093_),
    .B(_004_),
    .Y(_026_)
  );
  NOR _191_ (
    .A(_101_),
    .B(_006_),
    .Y(_027_)
  );
  NOR _192_ (
    .A(_026_),
    .B(_027_),
    .Y(_028_)
  );
  NOR _193_ (
    .A(_109_),
    .B(_009_),
    .Y(_029_)
  );
  NOR _194_ (
    .A(_085_),
    .B(_011_),
    .Y(_030_)
  );
  NOR _195_ (
    .A(_029_),
    .B(_030_),
    .Y(_031_)
  );
  NAND _196_ (
    .A(_028_),
    .B(_031_),
    .Y(_032_)
  );
  NAND _197_ (
    .A(_002_),
    .B(_032_),
    .Y(_033_)
  );
  NAND _198_ (
    .A(data_out_sintetizado[2]),
    .B(_117_),
    .Y(_034_)
  );
  NAND _199_ (
    .A(_033_),
    .B(_034_),
    .Y(_000_[2])
  );
  NOR _200_ (
    .A(_094_),
    .B(_004_),
    .Y(_035_)
  );
  NOR _201_ (
    .A(_102_),
    .B(_006_),
    .Y(_036_)
  );
  NOR _202_ (
    .A(_035_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _203_ (
    .A(_110_),
    .B(_009_),
    .Y(_038_)
  );
  NOR _204_ (
    .A(_086_),
    .B(_011_),
    .Y(_039_)
  );
  NOR _205_ (
    .A(_038_),
    .B(_039_),
    .Y(_040_)
  );
  NAND _206_ (
    .A(_037_),
    .B(_040_),
    .Y(_041_)
  );
  NAND _207_ (
    .A(_002_),
    .B(_041_),
    .Y(_042_)
  );
  NAND _208_ (
    .A(data_out_sintetizado[3]),
    .B(_117_),
    .Y(_043_)
  );
  NAND _209_ (
    .A(_042_),
    .B(_043_),
    .Y(_000_[3])
  );
  NOR _210_ (
    .A(_095_),
    .B(_004_),
    .Y(_044_)
  );
  NOR _211_ (
    .A(_103_),
    .B(_006_),
    .Y(_045_)
  );
  NOR _212_ (
    .A(_044_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _213_ (
    .A(_111_),
    .B(_009_),
    .Y(_047_)
  );
  NOR _214_ (
    .A(_087_),
    .B(_011_),
    .Y(_048_)
  );
  NOR _215_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  NAND _216_ (
    .A(_046_),
    .B(_049_),
    .Y(_050_)
  );
  NAND _217_ (
    .A(_002_),
    .B(_050_),
    .Y(_051_)
  );
  NAND _218_ (
    .A(data_out_sintetizado[4]),
    .B(_117_),
    .Y(_052_)
  );
  NAND _219_ (
    .A(_051_),
    .B(_052_),
    .Y(_000_[4])
  );
  NOR _220_ (
    .A(_096_),
    .B(_004_),
    .Y(_053_)
  );
  NOR _221_ (
    .A(_104_),
    .B(_006_),
    .Y(_054_)
  );
  NOR _222_ (
    .A(_053_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _223_ (
    .A(_112_),
    .B(_009_),
    .Y(_056_)
  );
  NOR _224_ (
    .A(_088_),
    .B(_011_),
    .Y(_057_)
  );
  NOR _225_ (
    .A(_056_),
    .B(_057_),
    .Y(_058_)
  );
  NAND _226_ (
    .A(_055_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _227_ (
    .A(_002_),
    .B(_059_),
    .Y(_060_)
  );
  NAND _228_ (
    .A(data_out_sintetizado[5]),
    .B(_117_),
    .Y(_061_)
  );
  NAND _229_ (
    .A(_060_),
    .B(_061_),
    .Y(_000_[5])
  );
  NOR _230_ (
    .A(_089_),
    .B(_011_),
    .Y(_062_)
  );
  NOR _231_ (
    .A(_105_),
    .B(_006_),
    .Y(_063_)
  );
  NOR _232_ (
    .A(_062_),
    .B(_063_),
    .Y(_064_)
  );
  NOR _233_ (
    .A(_113_),
    .B(_009_),
    .Y(_065_)
  );
  NOR _234_ (
    .A(_097_),
    .B(_004_),
    .Y(_066_)
  );
  NOR _235_ (
    .A(_065_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _236_ (
    .A(_064_),
    .B(_067_),
    .Y(_068_)
  );
  NAND _237_ (
    .A(_002_),
    .B(_068_),
    .Y(_069_)
  );
  NAND _238_ (
    .A(data_out_sintetizado[6]),
    .B(_117_),
    .Y(_070_)
  );
  NAND _239_ (
    .A(_069_),
    .B(_070_),
    .Y(_000_[6])
  );
  NOR _240_ (
    .A(_090_),
    .B(_011_),
    .Y(_071_)
  );
  NOR _241_ (
    .A(_106_),
    .B(_006_),
    .Y(_072_)
  );
  NOR _242_ (
    .A(_071_),
    .B(_072_),
    .Y(_073_)
  );
  NOR _243_ (
    .A(_114_),
    .B(_009_),
    .Y(_074_)
  );
  NOR _244_ (
    .A(_098_),
    .B(_004_),
    .Y(_075_)
  );
  NOR _245_ (
    .A(_074_),
    .B(_075_),
    .Y(_076_)
  );
  NAND _246_ (
    .A(_073_),
    .B(_076_),
    .Y(_077_)
  );
  NAND _247_ (
    .A(_002_),
    .B(_077_),
    .Y(_078_)
  );
  NAND _248_ (
    .A(data_out_sintetizado[7]),
    .B(_117_),
    .Y(_079_)
  );
  NAND _249_ (
    .A(_078_),
    .B(_079_),
    .Y(_000_[7])
  );
  (* src = "paso32bto8b_sintetizado.v:14" *)
  DFF _250_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(data_out_sintetizado[0])
  );
  (* src = "paso32bto8b_sintetizado.v:14" *)
  DFF _251_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(data_out_sintetizado[1])
  );
  (* src = "paso32bto8b_sintetizado.v:14" *)
  DFF _252_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(data_out_sintetizado[2])
  );
  (* src = "paso32bto8b_sintetizado.v:14" *)
  DFF _253_ (
    .C(clk_4f),
    .D(_000_[3]),
    .Q(data_out_sintetizado[3])
  );
  (* src = "paso32bto8b_sintetizado.v:14" *)
  DFF _254_ (
    .C(clk_4f),
    .D(_000_[4]),
    .Q(data_out_sintetizado[4])
  );
  (* src = "paso32bto8b_sintetizado.v:14" *)
  DFF _255_ (
    .C(clk_4f),
    .D(_000_[5]),
    .Q(data_out_sintetizado[5])
  );
  (* src = "paso32bto8b_sintetizado.v:14" *)
  DFF _256_ (
    .C(clk_4f),
    .D(_000_[6]),
    .Q(data_out_sintetizado[6])
  );
  (* src = "paso32bto8b_sintetizado.v:14" *)
  DFF _257_ (
    .C(clk_4f),
    .D(_000_[7]),
    .Q(data_out_sintetizado[7])
  );
  (* src = "paso32bto8b_sintetizado.v:14" *)
  DFF _258_ (
    .C(clk_4f),
    .D(_002_),
    .Q(valid_out_sintetizado)
  );
  (* src = "paso32bto8b_sintetizado.v:14" *)
  DFF _259_ (
    .C(clk_4f),
    .D(_001_[0]),
    .Q(indice[0])
  );
  (* src = "paso32bto8b_sintetizado.v:14" *)
  DFF _260_ (
    .C(clk_4f),
    .D(_001_[1]),
    .Q(indice[1])
  );
  assign validTemp = 1'h0;
endmodule
