/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "byteStriping_sintetizado.v:1" *)
module byteStriping_sintetizado(valid_in, clk, reset, data_in, valid_0_sintetizado, valid_1_sintetizado, lane_0_sintetizado, lane_1_sintetizado);
  (* src = "byteStriping_sintetizado.v:9" *)
  wire [31:0] _000_;
  (* src = "byteStriping_sintetizado.v:9" *)
  wire [31:0] _001_;
  (* src = "byteStriping_sintetizado.v:9" *)
  wire _002_;
  (* src = "byteStriping_sintetizado.v:9" *)
  wire _003_;
  (* src = "byteStriping_sintetizado.v:9" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  (* src = "byteStriping_sintetizado.v:2" *)
  input clk;
  (* src = "byteStriping_sintetizado.v:3" *)
  input [31:0] data_in;
  (* src = "byteStriping_sintetizado.v:5" *)
  output [31:0] lane_0_sintetizado;
  (* src = "byteStriping_sintetizado.v:6" *)
  output [31:0] lane_1_sintetizado;
  (* src = "byteStriping_sintetizado.v:2" *)
  input reset;
  (* src = "byteStriping_sintetizado.v:8" *)
  wire selector;
  (* src = "byteStriping_sintetizado.v:4" *)
  output valid_0_sintetizado;
  (* src = "byteStriping_sintetizado.v:4" *)
  output valid_1_sintetizado;
  (* src = "byteStriping_sintetizado.v:2" *)
  input valid_in;
  NOT _239_ (
    .A(valid_in),
    .Y(_005_)
  );
  NOT _240_ (
    .A(reset),
    .Y(_006_)
  );
  NOT _241_ (
    .A(selector),
    .Y(_007_)
  );
  NOT _242_ (
    .A(data_in[0]),
    .Y(_008_)
  );
  NOT _243_ (
    .A(data_in[1]),
    .Y(_009_)
  );
  NOT _244_ (
    .A(data_in[2]),
    .Y(_010_)
  );
  NOT _245_ (
    .A(data_in[3]),
    .Y(_011_)
  );
  NOT _246_ (
    .A(data_in[4]),
    .Y(_012_)
  );
  NOT _247_ (
    .A(data_in[5]),
    .Y(_013_)
  );
  NOT _248_ (
    .A(data_in[6]),
    .Y(_014_)
  );
  NOT _249_ (
    .A(data_in[7]),
    .Y(_015_)
  );
  NOT _250_ (
    .A(data_in[8]),
    .Y(_016_)
  );
  NOT _251_ (
    .A(data_in[9]),
    .Y(_017_)
  );
  NOT _252_ (
    .A(data_in[10]),
    .Y(_018_)
  );
  NOT _253_ (
    .A(data_in[11]),
    .Y(_019_)
  );
  NOT _254_ (
    .A(data_in[12]),
    .Y(_020_)
  );
  NOT _255_ (
    .A(data_in[13]),
    .Y(_021_)
  );
  NOT _256_ (
    .A(data_in[14]),
    .Y(_022_)
  );
  NOT _257_ (
    .A(data_in[15]),
    .Y(_023_)
  );
  NOT _258_ (
    .A(data_in[16]),
    .Y(_024_)
  );
  NOT _259_ (
    .A(data_in[17]),
    .Y(_025_)
  );
  NOT _260_ (
    .A(data_in[18]),
    .Y(_026_)
  );
  NOT _261_ (
    .A(data_in[19]),
    .Y(_027_)
  );
  NOT _262_ (
    .A(data_in[20]),
    .Y(_028_)
  );
  NOT _263_ (
    .A(data_in[21]),
    .Y(_029_)
  );
  NOT _264_ (
    .A(data_in[22]),
    .Y(_030_)
  );
  NOT _265_ (
    .A(data_in[23]),
    .Y(_031_)
  );
  NOT _266_ (
    .A(data_in[24]),
    .Y(_032_)
  );
  NOT _267_ (
    .A(data_in[25]),
    .Y(_033_)
  );
  NOT _268_ (
    .A(data_in[26]),
    .Y(_034_)
  );
  NOT _269_ (
    .A(data_in[27]),
    .Y(_035_)
  );
  NOT _270_ (
    .A(data_in[28]),
    .Y(_036_)
  );
  NOT _271_ (
    .A(data_in[29]),
    .Y(_037_)
  );
  NOT _272_ (
    .A(data_in[30]),
    .Y(_038_)
  );
  NOT _273_ (
    .A(data_in[31]),
    .Y(_039_)
  );
  NAND _274_ (
    .A(selector),
    .B(valid_1_sintetizado),
    .Y(_040_)
  );
  NOT _275_ (
    .A(_040_),
    .Y(_041_)
  );
  NOR _276_ (
    .A(_005_),
    .B(selector),
    .Y(_042_)
  );
  NOR _277_ (
    .A(_041_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _278_ (
    .A(reset),
    .B(_043_),
    .Y(_004_)
  );
  NOR _279_ (
    .A(_005_),
    .B(_007_),
    .Y(_044_)
  );
  NAND _280_ (
    .A(_006_),
    .B(_044_),
    .Y(_045_)
  );
  NOR _281_ (
    .A(reset),
    .B(selector),
    .Y(_002_)
  );
  NAND _282_ (
    .A(valid_0_sintetizado),
    .B(_002_),
    .Y(_046_)
  );
  NAND _283_ (
    .A(_045_),
    .B(_046_),
    .Y(_003_)
  );
  NOR _284_ (
    .A(lane_1_sintetizado[0]),
    .B(_042_),
    .Y(_047_)
  );
  NAND _285_ (
    .A(_008_),
    .B(_042_),
    .Y(_048_)
  );
  NAND _286_ (
    .A(_006_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _287_ (
    .A(_047_),
    .B(_049_),
    .Y(_001_[0])
  );
  NOR _288_ (
    .A(lane_1_sintetizado[1]),
    .B(_042_),
    .Y(_050_)
  );
  NAND _289_ (
    .A(_009_),
    .B(_042_),
    .Y(_051_)
  );
  NAND _290_ (
    .A(_006_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _291_ (
    .A(_050_),
    .B(_052_),
    .Y(_001_[1])
  );
  NOR _292_ (
    .A(lane_1_sintetizado[2]),
    .B(_042_),
    .Y(_053_)
  );
  NAND _293_ (
    .A(_010_),
    .B(_042_),
    .Y(_054_)
  );
  NAND _294_ (
    .A(_006_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _295_ (
    .A(_053_),
    .B(_055_),
    .Y(_001_[2])
  );
  NOR _296_ (
    .A(lane_1_sintetizado[3]),
    .B(_042_),
    .Y(_056_)
  );
  NAND _297_ (
    .A(_011_),
    .B(_042_),
    .Y(_057_)
  );
  NAND _298_ (
    .A(_006_),
    .B(_057_),
    .Y(_058_)
  );
  NOR _299_ (
    .A(_056_),
    .B(_058_),
    .Y(_001_[3])
  );
  NOR _300_ (
    .A(lane_1_sintetizado[4]),
    .B(_042_),
    .Y(_059_)
  );
  NAND _301_ (
    .A(_012_),
    .B(_042_),
    .Y(_060_)
  );
  NAND _302_ (
    .A(_006_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _303_ (
    .A(_059_),
    .B(_061_),
    .Y(_001_[4])
  );
  NOR _304_ (
    .A(lane_1_sintetizado[5]),
    .B(_042_),
    .Y(_062_)
  );
  NAND _305_ (
    .A(_013_),
    .B(_042_),
    .Y(_063_)
  );
  NAND _306_ (
    .A(_006_),
    .B(_063_),
    .Y(_064_)
  );
  NOR _307_ (
    .A(_062_),
    .B(_064_),
    .Y(_001_[5])
  );
  NOR _308_ (
    .A(lane_1_sintetizado[6]),
    .B(_042_),
    .Y(_065_)
  );
  NAND _309_ (
    .A(_014_),
    .B(_042_),
    .Y(_066_)
  );
  NAND _310_ (
    .A(_006_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _311_ (
    .A(_065_),
    .B(_067_),
    .Y(_001_[6])
  );
  NOR _312_ (
    .A(lane_1_sintetizado[7]),
    .B(_042_),
    .Y(_068_)
  );
  NAND _313_ (
    .A(_015_),
    .B(_042_),
    .Y(_069_)
  );
  NAND _314_ (
    .A(_006_),
    .B(_069_),
    .Y(_070_)
  );
  NOR _315_ (
    .A(_068_),
    .B(_070_),
    .Y(_001_[7])
  );
  NOR _316_ (
    .A(lane_1_sintetizado[8]),
    .B(_042_),
    .Y(_071_)
  );
  NAND _317_ (
    .A(_016_),
    .B(_042_),
    .Y(_072_)
  );
  NAND _318_ (
    .A(_006_),
    .B(_072_),
    .Y(_073_)
  );
  NOR _319_ (
    .A(_071_),
    .B(_073_),
    .Y(_001_[8])
  );
  NOR _320_ (
    .A(lane_1_sintetizado[9]),
    .B(_042_),
    .Y(_074_)
  );
  NAND _321_ (
    .A(_017_),
    .B(_042_),
    .Y(_075_)
  );
  NAND _322_ (
    .A(_006_),
    .B(_075_),
    .Y(_076_)
  );
  NOR _323_ (
    .A(_074_),
    .B(_076_),
    .Y(_001_[9])
  );
  NOR _324_ (
    .A(lane_1_sintetizado[10]),
    .B(_042_),
    .Y(_077_)
  );
  NAND _325_ (
    .A(_018_),
    .B(_042_),
    .Y(_078_)
  );
  NAND _326_ (
    .A(_006_),
    .B(_078_),
    .Y(_079_)
  );
  NOR _327_ (
    .A(_077_),
    .B(_079_),
    .Y(_001_[10])
  );
  NOR _328_ (
    .A(lane_1_sintetizado[11]),
    .B(_042_),
    .Y(_080_)
  );
  NAND _329_ (
    .A(_019_),
    .B(_042_),
    .Y(_081_)
  );
  NAND _330_ (
    .A(_006_),
    .B(_081_),
    .Y(_082_)
  );
  NOR _331_ (
    .A(_080_),
    .B(_082_),
    .Y(_001_[11])
  );
  NOR _332_ (
    .A(lane_1_sintetizado[12]),
    .B(_042_),
    .Y(_083_)
  );
  NAND _333_ (
    .A(_020_),
    .B(_042_),
    .Y(_084_)
  );
  NAND _334_ (
    .A(_006_),
    .B(_084_),
    .Y(_085_)
  );
  NOR _335_ (
    .A(_083_),
    .B(_085_),
    .Y(_001_[12])
  );
  NOR _336_ (
    .A(lane_1_sintetizado[13]),
    .B(_042_),
    .Y(_086_)
  );
  NAND _337_ (
    .A(_021_),
    .B(_042_),
    .Y(_087_)
  );
  NAND _338_ (
    .A(_006_),
    .B(_087_),
    .Y(_088_)
  );
  NOR _339_ (
    .A(_086_),
    .B(_088_),
    .Y(_001_[13])
  );
  NOR _340_ (
    .A(lane_1_sintetizado[14]),
    .B(_042_),
    .Y(_089_)
  );
  NAND _341_ (
    .A(_022_),
    .B(_042_),
    .Y(_090_)
  );
  NAND _342_ (
    .A(_006_),
    .B(_090_),
    .Y(_091_)
  );
  NOR _343_ (
    .A(_089_),
    .B(_091_),
    .Y(_001_[14])
  );
  NOR _344_ (
    .A(lane_1_sintetizado[15]),
    .B(_042_),
    .Y(_092_)
  );
  NAND _345_ (
    .A(_023_),
    .B(_042_),
    .Y(_093_)
  );
  NAND _346_ (
    .A(_006_),
    .B(_093_),
    .Y(_094_)
  );
  NOR _347_ (
    .A(_092_),
    .B(_094_),
    .Y(_001_[15])
  );
  NOR _348_ (
    .A(lane_1_sintetizado[16]),
    .B(_042_),
    .Y(_095_)
  );
  NAND _349_ (
    .A(_024_),
    .B(_042_),
    .Y(_096_)
  );
  NAND _350_ (
    .A(_006_),
    .B(_096_),
    .Y(_097_)
  );
  NOR _351_ (
    .A(_095_),
    .B(_097_),
    .Y(_001_[16])
  );
  NOR _352_ (
    .A(lane_1_sintetizado[17]),
    .B(_042_),
    .Y(_098_)
  );
  NAND _353_ (
    .A(_025_),
    .B(_042_),
    .Y(_099_)
  );
  NAND _354_ (
    .A(_006_),
    .B(_099_),
    .Y(_100_)
  );
  NOR _355_ (
    .A(_098_),
    .B(_100_),
    .Y(_001_[17])
  );
  NOR _356_ (
    .A(lane_1_sintetizado[18]),
    .B(_042_),
    .Y(_101_)
  );
  NAND _357_ (
    .A(_026_),
    .B(_042_),
    .Y(_102_)
  );
  NAND _358_ (
    .A(_006_),
    .B(_102_),
    .Y(_103_)
  );
  NOR _359_ (
    .A(_101_),
    .B(_103_),
    .Y(_001_[18])
  );
  NOR _360_ (
    .A(lane_1_sintetizado[19]),
    .B(_042_),
    .Y(_104_)
  );
  NAND _361_ (
    .A(_027_),
    .B(_042_),
    .Y(_105_)
  );
  NAND _362_ (
    .A(_006_),
    .B(_105_),
    .Y(_106_)
  );
  NOR _363_ (
    .A(_104_),
    .B(_106_),
    .Y(_001_[19])
  );
  NOR _364_ (
    .A(lane_1_sintetizado[20]),
    .B(_042_),
    .Y(_107_)
  );
  NAND _365_ (
    .A(_028_),
    .B(_042_),
    .Y(_108_)
  );
  NAND _366_ (
    .A(_006_),
    .B(_108_),
    .Y(_109_)
  );
  NOR _367_ (
    .A(_107_),
    .B(_109_),
    .Y(_001_[20])
  );
  NOR _368_ (
    .A(lane_1_sintetizado[21]),
    .B(_042_),
    .Y(_110_)
  );
  NAND _369_ (
    .A(_029_),
    .B(_042_),
    .Y(_111_)
  );
  NAND _370_ (
    .A(_006_),
    .B(_111_),
    .Y(_112_)
  );
  NOR _371_ (
    .A(_110_),
    .B(_112_),
    .Y(_001_[21])
  );
  NOR _372_ (
    .A(lane_1_sintetizado[22]),
    .B(_042_),
    .Y(_113_)
  );
  NAND _373_ (
    .A(_030_),
    .B(_042_),
    .Y(_114_)
  );
  NAND _374_ (
    .A(_006_),
    .B(_114_),
    .Y(_115_)
  );
  NOR _375_ (
    .A(_113_),
    .B(_115_),
    .Y(_001_[22])
  );
  NOR _376_ (
    .A(lane_1_sintetizado[23]),
    .B(_042_),
    .Y(_116_)
  );
  NAND _377_ (
    .A(_031_),
    .B(_042_),
    .Y(_117_)
  );
  NAND _378_ (
    .A(_006_),
    .B(_117_),
    .Y(_118_)
  );
  NOR _379_ (
    .A(_116_),
    .B(_118_),
    .Y(_001_[23])
  );
  NOR _380_ (
    .A(lane_1_sintetizado[24]),
    .B(_042_),
    .Y(_119_)
  );
  NAND _381_ (
    .A(_032_),
    .B(_042_),
    .Y(_120_)
  );
  NAND _382_ (
    .A(_006_),
    .B(_120_),
    .Y(_121_)
  );
  NOR _383_ (
    .A(_119_),
    .B(_121_),
    .Y(_001_[24])
  );
  NOR _384_ (
    .A(lane_1_sintetizado[25]),
    .B(_042_),
    .Y(_122_)
  );
  NAND _385_ (
    .A(_033_),
    .B(_042_),
    .Y(_123_)
  );
  NAND _386_ (
    .A(_006_),
    .B(_123_),
    .Y(_124_)
  );
  NOR _387_ (
    .A(_122_),
    .B(_124_),
    .Y(_001_[25])
  );
  NOR _388_ (
    .A(lane_1_sintetizado[26]),
    .B(_042_),
    .Y(_125_)
  );
  NAND _389_ (
    .A(_034_),
    .B(_042_),
    .Y(_126_)
  );
  NAND _390_ (
    .A(_006_),
    .B(_126_),
    .Y(_127_)
  );
  NOR _391_ (
    .A(_125_),
    .B(_127_),
    .Y(_001_[26])
  );
  NOR _392_ (
    .A(lane_1_sintetizado[27]),
    .B(_042_),
    .Y(_128_)
  );
  NAND _393_ (
    .A(_035_),
    .B(_042_),
    .Y(_129_)
  );
  NAND _394_ (
    .A(_006_),
    .B(_129_),
    .Y(_130_)
  );
  NOR _395_ (
    .A(_128_),
    .B(_130_),
    .Y(_001_[27])
  );
  NOR _396_ (
    .A(lane_1_sintetizado[28]),
    .B(_042_),
    .Y(_131_)
  );
  NAND _397_ (
    .A(_036_),
    .B(_042_),
    .Y(_132_)
  );
  NAND _398_ (
    .A(_006_),
    .B(_132_),
    .Y(_133_)
  );
  NOR _399_ (
    .A(_131_),
    .B(_133_),
    .Y(_001_[28])
  );
  NOR _400_ (
    .A(lane_1_sintetizado[29]),
    .B(_042_),
    .Y(_134_)
  );
  NAND _401_ (
    .A(_037_),
    .B(_042_),
    .Y(_135_)
  );
  NAND _402_ (
    .A(_006_),
    .B(_135_),
    .Y(_136_)
  );
  NOR _403_ (
    .A(_134_),
    .B(_136_),
    .Y(_001_[29])
  );
  NOR _404_ (
    .A(lane_1_sintetizado[30]),
    .B(_042_),
    .Y(_137_)
  );
  NAND _405_ (
    .A(_038_),
    .B(_042_),
    .Y(_138_)
  );
  NAND _406_ (
    .A(_006_),
    .B(_138_),
    .Y(_139_)
  );
  NOR _407_ (
    .A(_137_),
    .B(_139_),
    .Y(_001_[30])
  );
  NOR _408_ (
    .A(lane_1_sintetizado[31]),
    .B(_042_),
    .Y(_140_)
  );
  NAND _409_ (
    .A(_039_),
    .B(_042_),
    .Y(_141_)
  );
  NAND _410_ (
    .A(_006_),
    .B(_141_),
    .Y(_142_)
  );
  NOR _411_ (
    .A(_140_),
    .B(_142_),
    .Y(_001_[31])
  );
  NAND _412_ (
    .A(_008_),
    .B(_044_),
    .Y(_143_)
  );
  NAND _413_ (
    .A(_006_),
    .B(_143_),
    .Y(_144_)
  );
  NOR _414_ (
    .A(lane_0_sintetizado[0]),
    .B(_044_),
    .Y(_145_)
  );
  NOR _415_ (
    .A(_144_),
    .B(_145_),
    .Y(_000_[0])
  );
  NAND _416_ (
    .A(_009_),
    .B(_044_),
    .Y(_146_)
  );
  NAND _417_ (
    .A(_006_),
    .B(_146_),
    .Y(_147_)
  );
  NOR _418_ (
    .A(lane_0_sintetizado[1]),
    .B(_044_),
    .Y(_148_)
  );
  NOR _419_ (
    .A(_147_),
    .B(_148_),
    .Y(_000_[1])
  );
  NAND _420_ (
    .A(_010_),
    .B(_044_),
    .Y(_149_)
  );
  NAND _421_ (
    .A(_006_),
    .B(_149_),
    .Y(_150_)
  );
  NOR _422_ (
    .A(lane_0_sintetizado[2]),
    .B(_044_),
    .Y(_151_)
  );
  NOR _423_ (
    .A(_150_),
    .B(_151_),
    .Y(_000_[2])
  );
  NAND _424_ (
    .A(_011_),
    .B(_044_),
    .Y(_152_)
  );
  NAND _425_ (
    .A(_006_),
    .B(_152_),
    .Y(_153_)
  );
  NOR _426_ (
    .A(lane_0_sintetizado[3]),
    .B(_044_),
    .Y(_154_)
  );
  NOR _427_ (
    .A(_153_),
    .B(_154_),
    .Y(_000_[3])
  );
  NAND _428_ (
    .A(_012_),
    .B(_044_),
    .Y(_155_)
  );
  NAND _429_ (
    .A(_006_),
    .B(_155_),
    .Y(_156_)
  );
  NOR _430_ (
    .A(lane_0_sintetizado[4]),
    .B(_044_),
    .Y(_157_)
  );
  NOR _431_ (
    .A(_156_),
    .B(_157_),
    .Y(_000_[4])
  );
  NAND _432_ (
    .A(_013_),
    .B(_044_),
    .Y(_158_)
  );
  NAND _433_ (
    .A(_006_),
    .B(_158_),
    .Y(_159_)
  );
  NOR _434_ (
    .A(lane_0_sintetizado[5]),
    .B(_044_),
    .Y(_160_)
  );
  NOR _435_ (
    .A(_159_),
    .B(_160_),
    .Y(_000_[5])
  );
  NAND _436_ (
    .A(_014_),
    .B(_044_),
    .Y(_161_)
  );
  NAND _437_ (
    .A(_006_),
    .B(_161_),
    .Y(_162_)
  );
  NOR _438_ (
    .A(lane_0_sintetizado[6]),
    .B(_044_),
    .Y(_163_)
  );
  NOR _439_ (
    .A(_162_),
    .B(_163_),
    .Y(_000_[6])
  );
  NAND _440_ (
    .A(_015_),
    .B(_044_),
    .Y(_164_)
  );
  NAND _441_ (
    .A(_006_),
    .B(_164_),
    .Y(_165_)
  );
  NOR _442_ (
    .A(lane_0_sintetizado[7]),
    .B(_044_),
    .Y(_166_)
  );
  NOR _443_ (
    .A(_165_),
    .B(_166_),
    .Y(_000_[7])
  );
  NAND _444_ (
    .A(_016_),
    .B(_044_),
    .Y(_167_)
  );
  NAND _445_ (
    .A(_006_),
    .B(_167_),
    .Y(_168_)
  );
  NOR _446_ (
    .A(lane_0_sintetizado[8]),
    .B(_044_),
    .Y(_169_)
  );
  NOR _447_ (
    .A(_168_),
    .B(_169_),
    .Y(_000_[8])
  );
  NAND _448_ (
    .A(_017_),
    .B(_044_),
    .Y(_170_)
  );
  NAND _449_ (
    .A(_006_),
    .B(_170_),
    .Y(_171_)
  );
  NOR _450_ (
    .A(lane_0_sintetizado[9]),
    .B(_044_),
    .Y(_172_)
  );
  NOR _451_ (
    .A(_171_),
    .B(_172_),
    .Y(_000_[9])
  );
  NAND _452_ (
    .A(_018_),
    .B(_044_),
    .Y(_173_)
  );
  NAND _453_ (
    .A(_006_),
    .B(_173_),
    .Y(_174_)
  );
  NOR _454_ (
    .A(lane_0_sintetizado[10]),
    .B(_044_),
    .Y(_175_)
  );
  NOR _455_ (
    .A(_174_),
    .B(_175_),
    .Y(_000_[10])
  );
  NAND _456_ (
    .A(_019_),
    .B(_044_),
    .Y(_176_)
  );
  NAND _457_ (
    .A(_006_),
    .B(_176_),
    .Y(_177_)
  );
  NOR _458_ (
    .A(lane_0_sintetizado[11]),
    .B(_044_),
    .Y(_178_)
  );
  NOR _459_ (
    .A(_177_),
    .B(_178_),
    .Y(_000_[11])
  );
  NAND _460_ (
    .A(_020_),
    .B(_044_),
    .Y(_179_)
  );
  NAND _461_ (
    .A(_006_),
    .B(_179_),
    .Y(_180_)
  );
  NOR _462_ (
    .A(lane_0_sintetizado[12]),
    .B(_044_),
    .Y(_181_)
  );
  NOR _463_ (
    .A(_180_),
    .B(_181_),
    .Y(_000_[12])
  );
  NAND _464_ (
    .A(_021_),
    .B(_044_),
    .Y(_182_)
  );
  NAND _465_ (
    .A(_006_),
    .B(_182_),
    .Y(_183_)
  );
  NOR _466_ (
    .A(lane_0_sintetizado[13]),
    .B(_044_),
    .Y(_184_)
  );
  NOR _467_ (
    .A(_183_),
    .B(_184_),
    .Y(_000_[13])
  );
  NAND _468_ (
    .A(_022_),
    .B(_044_),
    .Y(_185_)
  );
  NAND _469_ (
    .A(_006_),
    .B(_185_),
    .Y(_186_)
  );
  NOR _470_ (
    .A(lane_0_sintetizado[14]),
    .B(_044_),
    .Y(_187_)
  );
  NOR _471_ (
    .A(_186_),
    .B(_187_),
    .Y(_000_[14])
  );
  NAND _472_ (
    .A(_023_),
    .B(_044_),
    .Y(_188_)
  );
  NAND _473_ (
    .A(_006_),
    .B(_188_),
    .Y(_189_)
  );
  NOR _474_ (
    .A(lane_0_sintetizado[15]),
    .B(_044_),
    .Y(_190_)
  );
  NOR _475_ (
    .A(_189_),
    .B(_190_),
    .Y(_000_[15])
  );
  NAND _476_ (
    .A(_024_),
    .B(_044_),
    .Y(_191_)
  );
  NAND _477_ (
    .A(_006_),
    .B(_191_),
    .Y(_192_)
  );
  NOR _478_ (
    .A(lane_0_sintetizado[16]),
    .B(_044_),
    .Y(_193_)
  );
  NOR _479_ (
    .A(_192_),
    .B(_193_),
    .Y(_000_[16])
  );
  NAND _480_ (
    .A(_025_),
    .B(_044_),
    .Y(_194_)
  );
  NAND _481_ (
    .A(_006_),
    .B(_194_),
    .Y(_195_)
  );
  NOR _482_ (
    .A(lane_0_sintetizado[17]),
    .B(_044_),
    .Y(_196_)
  );
  NOR _483_ (
    .A(_195_),
    .B(_196_),
    .Y(_000_[17])
  );
  NAND _484_ (
    .A(_026_),
    .B(_044_),
    .Y(_197_)
  );
  NAND _485_ (
    .A(_006_),
    .B(_197_),
    .Y(_198_)
  );
  NOR _486_ (
    .A(lane_0_sintetizado[18]),
    .B(_044_),
    .Y(_199_)
  );
  NOR _487_ (
    .A(_198_),
    .B(_199_),
    .Y(_000_[18])
  );
  NAND _488_ (
    .A(_027_),
    .B(_044_),
    .Y(_200_)
  );
  NAND _489_ (
    .A(_006_),
    .B(_200_),
    .Y(_201_)
  );
  NOR _490_ (
    .A(lane_0_sintetizado[19]),
    .B(_044_),
    .Y(_202_)
  );
  NOR _491_ (
    .A(_201_),
    .B(_202_),
    .Y(_000_[19])
  );
  NAND _492_ (
    .A(_028_),
    .B(_044_),
    .Y(_203_)
  );
  NAND _493_ (
    .A(_006_),
    .B(_203_),
    .Y(_204_)
  );
  NOR _494_ (
    .A(lane_0_sintetizado[20]),
    .B(_044_),
    .Y(_205_)
  );
  NOR _495_ (
    .A(_204_),
    .B(_205_),
    .Y(_000_[20])
  );
  NAND _496_ (
    .A(_029_),
    .B(_044_),
    .Y(_206_)
  );
  NAND _497_ (
    .A(_006_),
    .B(_206_),
    .Y(_207_)
  );
  NOR _498_ (
    .A(lane_0_sintetizado[21]),
    .B(_044_),
    .Y(_208_)
  );
  NOR _499_ (
    .A(_207_),
    .B(_208_),
    .Y(_000_[21])
  );
  NAND _500_ (
    .A(_030_),
    .B(_044_),
    .Y(_209_)
  );
  NAND _501_ (
    .A(_006_),
    .B(_209_),
    .Y(_210_)
  );
  NOR _502_ (
    .A(lane_0_sintetizado[22]),
    .B(_044_),
    .Y(_211_)
  );
  NOR _503_ (
    .A(_210_),
    .B(_211_),
    .Y(_000_[22])
  );
  NAND _504_ (
    .A(_031_),
    .B(_044_),
    .Y(_212_)
  );
  NAND _505_ (
    .A(_006_),
    .B(_212_),
    .Y(_213_)
  );
  NOR _506_ (
    .A(lane_0_sintetizado[23]),
    .B(_044_),
    .Y(_214_)
  );
  NOR _507_ (
    .A(_213_),
    .B(_214_),
    .Y(_000_[23])
  );
  NAND _508_ (
    .A(_032_),
    .B(_044_),
    .Y(_215_)
  );
  NAND _509_ (
    .A(_006_),
    .B(_215_),
    .Y(_216_)
  );
  NOR _510_ (
    .A(lane_0_sintetizado[24]),
    .B(_044_),
    .Y(_217_)
  );
  NOR _511_ (
    .A(_216_),
    .B(_217_),
    .Y(_000_[24])
  );
  NAND _512_ (
    .A(_033_),
    .B(_044_),
    .Y(_218_)
  );
  NAND _513_ (
    .A(_006_),
    .B(_218_),
    .Y(_219_)
  );
  NOR _514_ (
    .A(lane_0_sintetizado[25]),
    .B(_044_),
    .Y(_220_)
  );
  NOR _515_ (
    .A(_219_),
    .B(_220_),
    .Y(_000_[25])
  );
  NAND _516_ (
    .A(_034_),
    .B(_044_),
    .Y(_221_)
  );
  NAND _517_ (
    .A(_006_),
    .B(_221_),
    .Y(_222_)
  );
  NOR _518_ (
    .A(lane_0_sintetizado[26]),
    .B(_044_),
    .Y(_223_)
  );
  NOR _519_ (
    .A(_222_),
    .B(_223_),
    .Y(_000_[26])
  );
  NAND _520_ (
    .A(_035_),
    .B(_044_),
    .Y(_224_)
  );
  NAND _521_ (
    .A(_006_),
    .B(_224_),
    .Y(_225_)
  );
  NOR _522_ (
    .A(lane_0_sintetizado[27]),
    .B(_044_),
    .Y(_226_)
  );
  NOR _523_ (
    .A(_225_),
    .B(_226_),
    .Y(_000_[27])
  );
  NAND _524_ (
    .A(_036_),
    .B(_044_),
    .Y(_227_)
  );
  NAND _525_ (
    .A(_006_),
    .B(_227_),
    .Y(_228_)
  );
  NOR _526_ (
    .A(lane_0_sintetizado[28]),
    .B(_044_),
    .Y(_229_)
  );
  NOR _527_ (
    .A(_228_),
    .B(_229_),
    .Y(_000_[28])
  );
  NAND _528_ (
    .A(_037_),
    .B(_044_),
    .Y(_230_)
  );
  NAND _529_ (
    .A(_006_),
    .B(_230_),
    .Y(_231_)
  );
  NOR _530_ (
    .A(lane_0_sintetizado[29]),
    .B(_044_),
    .Y(_232_)
  );
  NOR _531_ (
    .A(_231_),
    .B(_232_),
    .Y(_000_[29])
  );
  NAND _532_ (
    .A(_038_),
    .B(_044_),
    .Y(_233_)
  );
  NAND _533_ (
    .A(_006_),
    .B(_233_),
    .Y(_234_)
  );
  NOR _534_ (
    .A(lane_0_sintetizado[30]),
    .B(_044_),
    .Y(_235_)
  );
  NOR _535_ (
    .A(_234_),
    .B(_235_),
    .Y(_000_[30])
  );
  NAND _536_ (
    .A(_039_),
    .B(_044_),
    .Y(_236_)
  );
  NAND _537_ (
    .A(_006_),
    .B(_236_),
    .Y(_237_)
  );
  NOR _538_ (
    .A(lane_0_sintetizado[31]),
    .B(_044_),
    .Y(_238_)
  );
  NOR _539_ (
    .A(_237_),
    .B(_238_),
    .Y(_000_[31])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _540_ (
    .C(clk),
    .D(_000_[0]),
    .Q(lane_0_sintetizado[0])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _541_ (
    .C(clk),
    .D(_000_[1]),
    .Q(lane_0_sintetizado[1])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _542_ (
    .C(clk),
    .D(_000_[2]),
    .Q(lane_0_sintetizado[2])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _543_ (
    .C(clk),
    .D(_000_[3]),
    .Q(lane_0_sintetizado[3])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _544_ (
    .C(clk),
    .D(_000_[4]),
    .Q(lane_0_sintetizado[4])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _545_ (
    .C(clk),
    .D(_000_[5]),
    .Q(lane_0_sintetizado[5])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _546_ (
    .C(clk),
    .D(_000_[6]),
    .Q(lane_0_sintetizado[6])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _547_ (
    .C(clk),
    .D(_000_[7]),
    .Q(lane_0_sintetizado[7])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _548_ (
    .C(clk),
    .D(_000_[8]),
    .Q(lane_0_sintetizado[8])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _549_ (
    .C(clk),
    .D(_000_[9]),
    .Q(lane_0_sintetizado[9])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _550_ (
    .C(clk),
    .D(_000_[10]),
    .Q(lane_0_sintetizado[10])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _551_ (
    .C(clk),
    .D(_000_[11]),
    .Q(lane_0_sintetizado[11])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _552_ (
    .C(clk),
    .D(_000_[12]),
    .Q(lane_0_sintetizado[12])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _553_ (
    .C(clk),
    .D(_000_[13]),
    .Q(lane_0_sintetizado[13])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _554_ (
    .C(clk),
    .D(_000_[14]),
    .Q(lane_0_sintetizado[14])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _555_ (
    .C(clk),
    .D(_000_[15]),
    .Q(lane_0_sintetizado[15])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _556_ (
    .C(clk),
    .D(_000_[16]),
    .Q(lane_0_sintetizado[16])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _557_ (
    .C(clk),
    .D(_000_[17]),
    .Q(lane_0_sintetizado[17])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _558_ (
    .C(clk),
    .D(_000_[18]),
    .Q(lane_0_sintetizado[18])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _559_ (
    .C(clk),
    .D(_000_[19]),
    .Q(lane_0_sintetizado[19])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _560_ (
    .C(clk),
    .D(_000_[20]),
    .Q(lane_0_sintetizado[20])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _561_ (
    .C(clk),
    .D(_000_[21]),
    .Q(lane_0_sintetizado[21])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _562_ (
    .C(clk),
    .D(_000_[22]),
    .Q(lane_0_sintetizado[22])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _563_ (
    .C(clk),
    .D(_000_[23]),
    .Q(lane_0_sintetizado[23])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _564_ (
    .C(clk),
    .D(_000_[24]),
    .Q(lane_0_sintetizado[24])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _565_ (
    .C(clk),
    .D(_000_[25]),
    .Q(lane_0_sintetizado[25])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _566_ (
    .C(clk),
    .D(_000_[26]),
    .Q(lane_0_sintetizado[26])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _567_ (
    .C(clk),
    .D(_000_[27]),
    .Q(lane_0_sintetizado[27])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _568_ (
    .C(clk),
    .D(_000_[28]),
    .Q(lane_0_sintetizado[28])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _569_ (
    .C(clk),
    .D(_000_[29]),
    .Q(lane_0_sintetizado[29])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _570_ (
    .C(clk),
    .D(_000_[30]),
    .Q(lane_0_sintetizado[30])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _571_ (
    .C(clk),
    .D(_000_[31]),
    .Q(lane_0_sintetizado[31])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _572_ (
    .C(clk),
    .D(_001_[0]),
    .Q(lane_1_sintetizado[0])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _573_ (
    .C(clk),
    .D(_001_[1]),
    .Q(lane_1_sintetizado[1])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _574_ (
    .C(clk),
    .D(_001_[2]),
    .Q(lane_1_sintetizado[2])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _575_ (
    .C(clk),
    .D(_001_[3]),
    .Q(lane_1_sintetizado[3])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _576_ (
    .C(clk),
    .D(_001_[4]),
    .Q(lane_1_sintetizado[4])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _577_ (
    .C(clk),
    .D(_001_[5]),
    .Q(lane_1_sintetizado[5])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _578_ (
    .C(clk),
    .D(_001_[6]),
    .Q(lane_1_sintetizado[6])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _579_ (
    .C(clk),
    .D(_001_[7]),
    .Q(lane_1_sintetizado[7])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _580_ (
    .C(clk),
    .D(_001_[8]),
    .Q(lane_1_sintetizado[8])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _581_ (
    .C(clk),
    .D(_001_[9]),
    .Q(lane_1_sintetizado[9])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _582_ (
    .C(clk),
    .D(_001_[10]),
    .Q(lane_1_sintetizado[10])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _583_ (
    .C(clk),
    .D(_001_[11]),
    .Q(lane_1_sintetizado[11])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _584_ (
    .C(clk),
    .D(_001_[12]),
    .Q(lane_1_sintetizado[12])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _585_ (
    .C(clk),
    .D(_001_[13]),
    .Q(lane_1_sintetizado[13])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _586_ (
    .C(clk),
    .D(_001_[14]),
    .Q(lane_1_sintetizado[14])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _587_ (
    .C(clk),
    .D(_001_[15]),
    .Q(lane_1_sintetizado[15])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _588_ (
    .C(clk),
    .D(_001_[16]),
    .Q(lane_1_sintetizado[16])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _589_ (
    .C(clk),
    .D(_001_[17]),
    .Q(lane_1_sintetizado[17])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _590_ (
    .C(clk),
    .D(_001_[18]),
    .Q(lane_1_sintetizado[18])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _591_ (
    .C(clk),
    .D(_001_[19]),
    .Q(lane_1_sintetizado[19])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _592_ (
    .C(clk),
    .D(_001_[20]),
    .Q(lane_1_sintetizado[20])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _593_ (
    .C(clk),
    .D(_001_[21]),
    .Q(lane_1_sintetizado[21])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _594_ (
    .C(clk),
    .D(_001_[22]),
    .Q(lane_1_sintetizado[22])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _595_ (
    .C(clk),
    .D(_001_[23]),
    .Q(lane_1_sintetizado[23])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _596_ (
    .C(clk),
    .D(_001_[24]),
    .Q(lane_1_sintetizado[24])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _597_ (
    .C(clk),
    .D(_001_[25]),
    .Q(lane_1_sintetizado[25])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _598_ (
    .C(clk),
    .D(_001_[26]),
    .Q(lane_1_sintetizado[26])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _599_ (
    .C(clk),
    .D(_001_[27]),
    .Q(lane_1_sintetizado[27])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _600_ (
    .C(clk),
    .D(_001_[28]),
    .Q(lane_1_sintetizado[28])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _601_ (
    .C(clk),
    .D(_001_[29]),
    .Q(lane_1_sintetizado[29])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _602_ (
    .C(clk),
    .D(_001_[30]),
    .Q(lane_1_sintetizado[30])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _603_ (
    .C(clk),
    .D(_001_[31]),
    .Q(lane_1_sintetizado[31])
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _604_ (
    .C(clk),
    .D(_002_),
    .Q(selector)
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _605_ (
    .C(clk),
    .D(_003_),
    .Q(valid_0_sintetizado)
  );
  (* src = "byteStriping_sintetizado.v:9" *)
  DFF _606_ (
    .C(clk),
    .D(_004_),
    .Q(valid_1_sintetizado)
  );
endmodule
