/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "relojes_est.v:2" *)
module relojes_est(clk4f_out_e, clk2f_out_e, clk_out_e, clk32f, rst);
  (* src = "relojes_est.v:12" *)
  wire _00_;
  (* src = "relojes_est.v:12" *)
  wire _01_;
  (* src = "relojes_est.v:12" *)
  wire _02_;
  (* src = "relojes_est.v:12" *)
  wire [6:0] _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  (* src = "relojes_est.v:4" *)
  output clk2f_out_e;
  (* src = "relojes_est.v:6" *)
  input clk32f;
  (* src = "relojes_est.v:4" *)
  output clk4f_out_e;
  (* src = "relojes_est.v:4" *)
  output clk_out_e;
  (* src = "relojes_est.v:11" *)
  wire [6:0] cont;
  (* src = "relojes_est.v:7" *)
  input rst;
  NOR _33_ (
    .A(cont[0]),
    .B(rst),
    .Y(_03_[0])
  );
  NOT _34_ (
    .A(cont[0]),
    .Y(_04_)
  );
  NOT _35_ (
    .A(cont[1]),
    .Y(_05_)
  );
  NOR _36_ (
    .A(_05_),
    .B(_04_),
    .Y(_06_)
  );
  NOT _37_ (
    .A(rst),
    .Y(_07_)
  );
  NOR _38_ (
    .A(cont[1]),
    .B(cont[0]),
    .Y(_08_)
  );
  NOT _39_ (
    .A(_08_),
    .Y(_09_)
  );
  NAND _40_ (
    .A(_09_),
    .B(_07_),
    .Y(_10_)
  );
  NOR _41_ (
    .A(_10_),
    .B(_06_),
    .Y(_03_[1])
  );
  NOT _42_ (
    .A(cont[2]),
    .Y(_11_)
  );
  NAND _43_ (
    .A(cont[1]),
    .B(cont[0]),
    .Y(_12_)
  );
  NOR _44_ (
    .A(_12_),
    .B(_11_),
    .Y(_13_)
  );
  NAND _45_ (
    .A(_12_),
    .B(_11_),
    .Y(_14_)
  );
  NAND _46_ (
    .A(_14_),
    .B(_07_),
    .Y(_15_)
  );
  NOR _47_ (
    .A(_15_),
    .B(_13_),
    .Y(_03_[2])
  );
  NOT _48_ (
    .A(cont[3]),
    .Y(_16_)
  );
  NOR _49_ (
    .A(_13_),
    .B(_16_),
    .Y(_17_)
  );
  NAND _50_ (
    .A(_06_),
    .B(cont[2]),
    .Y(_18_)
  );
  NOR _51_ (
    .A(_18_),
    .B(cont[3]),
    .Y(_19_)
  );
  NOR _52_ (
    .A(_19_),
    .B(_17_),
    .Y(_20_)
  );
  NOR _53_ (
    .A(_20_),
    .B(rst),
    .Y(_03_[3])
  );
  NAND _54_ (
    .A(_08_),
    .B(_11_),
    .Y(_21_)
  );
  NOR _55_ (
    .A(_21_),
    .B(cont[3]),
    .Y(_22_)
  );
  NOR _56_ (
    .A(_22_),
    .B(clk_out_e),
    .Y(_23_)
  );
  NAND _57_ (
    .A(_22_),
    .B(clk_out_e),
    .Y(_24_)
  );
  NAND _58_ (
    .A(_24_),
    .B(_07_),
    .Y(_25_)
  );
  NOR _59_ (
    .A(_25_),
    .B(_23_),
    .Y(_02_)
  );
  NOT _60_ (
    .A(clk2f_out_e),
    .Y(_26_)
  );
  NOR _61_ (
    .A(_21_),
    .B(_26_),
    .Y(_27_)
  );
  NAND _62_ (
    .A(_21_),
    .B(_26_),
    .Y(_28_)
  );
  NAND _63_ (
    .A(_28_),
    .B(_07_),
    .Y(_29_)
  );
  NOR _64_ (
    .A(_29_),
    .B(_27_),
    .Y(_00_)
  );
  NOR _65_ (
    .A(_08_),
    .B(clk4f_out_e),
    .Y(_30_)
  );
  NAND _66_ (
    .A(_08_),
    .B(clk4f_out_e),
    .Y(_31_)
  );
  NAND _67_ (
    .A(_31_),
    .B(_07_),
    .Y(_32_)
  );
  NOR _68_ (
    .A(_32_),
    .B(_30_),
    .Y(_01_)
  );
  DFF _69_ (
    .C(clk32f),
    .D(_01_),
    .Q(clk4f_out_e)
  );
  DFF _70_ (
    .C(clk32f),
    .D(_00_),
    .Q(clk2f_out_e)
  );
  DFF _71_ (
    .C(clk32f),
    .D(_02_),
    .Q(clk_out_e)
  );
  DFF _72_ (
    .C(clk32f),
    .D(_03_[0]),
    .Q(cont[0])
  );
  DFF _73_ (
    .C(clk32f),
    .D(_03_[1]),
    .Q(cont[1])
  );
  DFF _74_ (
    .C(clk32f),
    .D(_03_[2]),
    .Q(cont[2])
  );
  DFF _75_ (
    .C(clk32f),
    .D(_03_[3]),
    .Q(cont[3])
  );
endmodule
